### ISSUE TITLE
Review: POLYGON wbtc-curve-polygon-2

### ISSUE THREAD

**Issue by dapp-whisperer** [Badger-Finance/badger-strategies#1]
# Strategy Review
* [Spec](https://github.com/GalloDaSballo/wbtc-curve-polygon-2#readme)
* [Code](https://github.com/GalloDaSballo/wbtc-curve-polygon-2/commit/1a2d1f3508bb3d2f84b779b9aced840fdb52bf8c)
* [Release](https://github.com/GalloDaSballo/wbtc-curve-polygon-2/releases/tag/0.1)

**Comment by sajanrajdev** [comment]
Please also review the following changes to the strategy: https://github.com/GalloDaSballo/wbtc-curve-polygon-2/pull/2/files

**Comment by GalloDaSballo** [comment]
Merged

**Comment by GalloDaSballo** [comment]
Added more protected tokens
<img width="729" alt="Screenshot 2021-08-02 at 19 58 26" src="https://user-images.githubusercontent.com/13383782/127904072-b80f65d8-6af4-41de-85f1-af959d64692f.png">

**Comment by GalloDaSballo** [comment]
All tests passing
<img width="1253" alt="Screenshot 2021-08-02 at 19 58 44" src="https://user-images.githubusercontent.com/13383782/127904113-789af757-af73-4517-90fb-65441a54e504.png">

**Comment by GalloDaSballo** [comment]
LGTM

Takes want and stake it into gauge
Farm from Gauge
Compound wMATIC into wBTC and provide more liquidity (more want)
Take fee and then send CRV to badger tree

Liquidity for pair -> wMATIC -> wETH and wETH -> wBTC confirmed on Quickswap

**Comment by sajanrajdev** [comment]
Deployment and Production tests update:

Controller: 0x12097e9755aBf710166D0027c1a2ef7609833D74
Registry: 0x22765948A3d5048F3644b81792e4E1aA7ea3da4a

wBTC/RenBTC Curve:

Strategy: 0xF8F02D0d41C79a1973f65A440C98acAc7eAA8Dc1
Sett: 0x7B6bfB88904e4B3A6d239d5Ed8adF557B22C10FC
Want: 0xf8a57c1d3b9629b77b6726a042ca48990a84fb49

Status: Wired up and unpaused

Added to registry under Author: 0xeE8b29AA52dD5fF2559da2C50b1887ADee257556

**Comment by sajanrajdev** [comment]
Test assets deposited and operating functions tested and working in production:
- sett.earn(): https://polygonscan.com/tx/0x155e2a191175576d82ebb4bae631c90abb70af5d827a1525ae3b6834dddfbeea
- strategy.harvest(): https://polygonscan.com/tx/0x704ed8ef4911984eaa1af0074cf92dc24d17a31ce0cb054da24ba852005768be
- strategy.tend(): https://polygonscan.com/tx/0xfce4c1a1f493d6a187b1c40a10ca15ac101bdf4480514aab2c8a82fea94f71ee

**Comment by sajanrajdev** [comment]
Production parameters were updated to the following for both the strategy and vault where applies:

governance = 0x4977110Ed3CD5eC5598e88c8965951a47dd4e738
strategist = 0x4977110Ed3CD5eC5598e88c8965951a47dd4e738
controller = 0xc00e71719d1494886942d6277daea20494cf0eec
keeper = 0x46fa8817624eea8052093eab8e3fdf0e2e0443b2
guardian = 0xCD3271021e9b35EF862Dd98AFa826b8b5198826d

withdrawalFee = 50
