### ISSUE TITLE
MAINNET - bveCVX - cvx.1.2.1

### ISSUE THREAD

**Issue by GalloDaSballo** [Badger-Finance/badger-strategies#10]
# Strategy Review

Code (Audit Fixes) + CVX as Want: https://github.com/GalloDaSballo/vested-cvx/tree/cvx.1

## Description
Locks CVX -> CVX into Convex Locker
Sends cvxCRV to badgerTree

## Due Diligence Document  (Link, but could also just be a .md file in repo)
No document afaik

## Deployed Contract (If present)
See Below

## Review By
* Ongoing:  Alex | CodeArena

## Review by Security Board
* Peer reviewed by: Alex | C2 | Tabish | 0xThunder
* Previous version reviewed by CodeArena code diffs available via commits

**Comment by GalloDaSballo** [comment]
Contracts Deployed, wired up and verified

Controller:
0xbaBF5401a6c255aF3Ae83fF806191C404eef8D9B

Vault:
0xE143aA25Eec81B4Fc952b38b6Bca8D2395481377

Strat Logic:
0xBB5f557F6A13c12a25F85B3F4aB9905D4093702D

Strat Proxy:
0x87fB47c2B9EB41d362BAb44F5Ec81514b6b1de13

**Comment by GalloDaSballo** [comment]
Waiting on Strategy to be approved for both bCVX and bcvxCRV to run a deposit and harvest

**Comment by GalloDaSballo** [comment]
Changed Controller Address, see above

**Comment by GalloDaSballo** [comment]
Changelog:
c4.1 -> Fixes issue with math in `manualRebalance` also adds check to `maximumBoost` for Locker
c4.2 -> Gas tweaks and external setters

**Comment by GalloDaSballo** [comment]
NOTE: Pending Upgrade on Proxy

**Comment by GalloDaSballo** [comment]
Latest Code: https://github.com/GalloDaSballo/vested-cvx/releases/tag/c4.2

**Comment by GalloDaSballo** [comment]
Fix for compilation: https://github.com/GalloDaSballo/vested-cvx/releases/tag/c.4.3

**Comment by GalloDaSballo** [comment]
Updated Logic: https://etherscan.io/address/0xfc13209cafe8fb3bb5fbd929ec9f11a39e8ac041#code

**Comment by GalloDaSballo** [comment]
Waiting on Cookies for automated harvests and deposits

**Comment by GalloDaSballo** [comment]
Waiting on Wiring Confirmation by @sajanrajdev

**Comment by GalloDaSballo** [comment]
New Addresses (CVX as want): 

Controller was deployed at:  
0xc259d2d0fCe2aC1162b67EFc7b102D4D8DC907E2
Vault was deployed at:  
0xba7d171786A6F3D2F92A91424d5c797355a44De6

Strat Logic:
0x424Ed5fEcf078632Aea0DA477091d8D9c6F6aec3

Strategy Proxy:  
0x3ff634ce65cDb8CC0D569D6d1697c41aa666cEA9

**Comment by GalloDaSballo** [comment]
TODO Set 0% performance and 0.1% withdraw? for locking cvx vaults

**Comment by GalloDaSballo** [comment]
Config:

Setting 0% Performance Fee Governance
s.setPerformanceFeeGovernance(0, {"from": a[0]})
0xdd109c672b79de09b8ac46e6ae71ef7d5c0d4db1021897f50237c4595adf9789

Setting 0% Performance Fee Strategist
s.setPerformanceFeeStrategist(0, {"from": a[0]})
0x4eadc8e7cb41ba4b48faed96e974e87ab3115334d6ee82c10cff0a433cdd982a

Setting withdrawal fee to 10 BPS
s.setWithdrawalFee(10, {"from": a[0]})
0x2bba02b84898b8a5519027812564615a3f221775dcd87a71ee6dddb307727ed5

**Comment by GalloDaSballo** [comment]
GuestList:

Deployed and verified at:
https://etherscan.io/address/0x809990849d53a5109e0cb9c446137793b9f6f1eb#readProxyContract

NOTE: AT TIME OF WIRING GOVERNANCE IS EOA owned by Saj

**Comment by GalloDaSballo** [comment]
Harvest:

s.harvest({"from": a[0]})
Transaction sent: 0xc4f271c998c36b9d89996bbac5a2fd1564461c7abf036ecb80c39e95c1127104

**Comment by GalloDaSballo** [comment]
Setup:

Running 'scripts/3_production_setup.py::main'...
You are using the 'mainnet' network
Account (demo): demo
Enter password for "demo": 
You are using: 'dev' [0x283C857BA940A61828d9F4c09e3fceE2e7aEF3f7]
Strategy:  veCVX Voting Strategy
Vault:  Badger Vested Escrow Convex Token
Transaction sent: 0x31f68521b2c4c7b1ba9c6c8d1c4eda8384fe1f6641c79c663feb97a43b6bebec
  Gas price: 95.187721919 gwei   Gas limit: 40040   Nonce: 96
  MyStrategy.setController confirmed   Block: 13264061   Gas used: 36317 (90.70%)

Transaction sent: 0x90878027b83087c181444d70c7130764e13810e174eae1c985af18a769a1259b
  Gas price: 92.447320211 gwei   Gas limit: 42257   Nonce: 97
  SettV4.setController confirmed   Block: 13264063   Gas used: 38302 (90.64%)

Controller existing or set at:  0x63cF44B2548e4493Fd099222A1eC79F3344D9682
Fees existing or set at:  0, 0, 10
Keeper existing or set at:  0x711A339c002386f9db409cA55b6A35a604aB6cF6
Guardian existing or set at:  0x29F7F8896Fb913CF7f9949C623F896a154727919
Strategist existing or set at:  0xB65cef03b9B89f99517643226d76e286ee999e77
Transaction sent: 0x467a0b5b1d4c801c95964d059e7b61d6bc51e303430fc40397114562e26263e1
  Gas price: 82.329064979 gwei   Gas limit: 37829   Nonce: 98
  MyStrategy.setGovernance confirmed   Block: 13264078   Gas used: 34339 (90.77%)

Transaction sent: 0xcb916ea195b228ce83fe76e8966098690bcf3d6a6ed8427f68fdca487c58f62b
  Gas price: 77.656432708 gwei   Gas limit: 37745   Nonce: 99
  Waiting for confirmation... -

**Comment by sajanrajdev** [comment]
The guestlist was configured as follows:
```Guestlist: 0x809990849D53a5109e0cb9C446137793B9f6f1Eb
User Deposit Cap @150K: 18472906403940886699507 CVX
Total Deposit Cap @2m: 246305418719211822660098 CVX
Open for everyone (no whitelist)```

**Comment by sajanrajdev** [comment]
Transactions to wire up vault/strategy to controller where posted to the devMultisig through a 2 day TimeLock:

```Events In This Transaction
--------------------------
├── GovernanceTimelock (0x21CF9b77F88Adf8F8C98d7E33Fe601DC57bC0893)
│   ├── QueueTransaction
│   │   ├── txHash: 0x74017719d5958565a740897a450ba0ed14c4aa726e84d5f3592b810ba1058d29
│   │   ├── target: 0x63cF44B2548e4493Fd099222A1eC79F3344D9682
│   │   ├── value: 0
│   │   ├── signature: setVault(address,address)
│   │   ├── data: 0x0000000000000000000000004e3fbd56cd56c3e72c1403e103b45db9da5b9d2b000000000000000000000000fd05d3c7fe2924020620a8be4961bbaa747e6305
│   │   └── eta: 1632365401
│   ├── QueueTransaction
│   │   ├── txHash: 0x4c549c714fcc6e95275baac73a04d7795198ada2e99ffd230381511408c84cfc
│   │   ├── target: 0x63cF44B2548e4493Fd099222A1eC79F3344D9682
│   │   ├── value: 0
│   │   ├── signature: approveStrategy(address,address)
│   │   ├── data: 0x0000000000000000000000004e3fbd56cd56c3e72c1403e103b45db9da5b9d2b0000000000000000000000003ff634ce65cdb8cc0d569d6d1697c41aa666cea9
│   │   └── eta: 1632365403
│   └── QueueTransaction
│       ├── txHash: 0x2c79cfa8ebed2a12668ba96c4eca9bdb61f4c3567bb56144264923f897c6b24a
│       ├── target: 0x63cF44B2548e4493Fd099222A1eC79F3344D9682
│       ├── value: 0
│       ├── signature: setStrategy(address,address)
│       ├── data: 0x0000000000000000000000004e3fbd56cd56c3e72c1403e103b45db9da5b9d2b0000000000000000000000003ff634ce65cdb8cc0d569d6d1697c41aa666cea9
│       └── eta: 1632365403
│
└── Gnosis Safe (0xB65cef03b9B89f99517643226d76e286ee999e77)
    └── ExecutionSuccess
        ├── txHash: 0x0edb71409543efee2e22873fc3095e839da3b4f524a3667a9edfd564658a1d8c
        └── payment: 0```

Signers will be able to confirm and execute production wire up by Thu Sep 23 2021 02:50:01 GMT+0000.

**Comment by sajanrajdev** [comment]
Transactions were posted again in order to give signers more time to sign. New ETA: Thu Sep 23 2021 21:04:51 GMT+0000 - Sign deadline is EOD Tuesday Sept 21, 2021.

**Comment by sajanrajdev** [comment]
Controller wire up was executed through the timelock. 

Controller used;
native.controller = `0x63cF44B2548e4493Fd099222A1eC79F3344D9682`

Vault wire up confirmation - controller.vaults(want): 
![image](https://user-images.githubusercontent.com/25463788/134587010-5fe97693-fb8b-4fa2-bff8-3ff26ee6082e.png)

vault.controller():
![image](https://user-images.githubusercontent.com/25463788/134587495-9f7c54ea-eabe-4adc-9e48-30b2453b2262.png)

Strategy wire up confirmation - controller.strategies(want): 
![image](https://user-images.githubusercontent.com/25463788/134586928-e45415d1-780f-4a57-93b0-16514c7fe9db.png)

strategy.controller():
![image](https://user-images.githubusercontent.com/25463788/134587465-f1c8ea25-cd20-43cf-b681-773c3ec36ab8.png)

**Comment by GalloDaSballo** [comment]
Confirmed settings

Strat and vault are using "controller" from registry
"controller" is wired to use strat and vault for the CVX token

**Comment by GalloDaSballo** [comment]
- [X] ProxyAdmin - 
- [X] Wiring of Controller - Checked, see above
- [X] Governace Parameters - Checked - Governance of Controller is timelock, Governance of Vault is devMultiSig
- [X] Fees - Confirmed by Po

<img width="606" alt="Screenshot 2021-09-24 at 15 46 00" src="https://user-images.githubusercontent.com/13383782/134684915-3e079144-f305-4de7-bd8e-b330f85e4b1a.png">

<img width="637" alt="Screenshot 2021-09-24 at 15 46 07" src="https://user-images.githubusercontent.com/13383782/134684930-dd7223d5-ea28-473e-9937-c538561383d2.png">

**Comment by GalloDaSballo** [comment]
Reviewed parameters, LGTM

**Comment by dapp-whisperer** [comment]
Signing off on parameters & proxyAdmins

**Comment by GalloDaSballo** [comment]
guestList:
https://etherscan.io/address/0x809990849D53a5109e0cb9C446137793B9f6f1Eb#readProxyContract

**Comment by GalloDaSballo** [comment]
Guestlist: 0x809990849D53a5109e0cb9C446137793B9f6f1Eb
User Deposit Cap @150K: 18472906403940886699507
Total Deposit Cap: @2m: 246305418719211822660098
Open for everyone (no whitelist)

**Comment by GalloDaSballo** [comment]
Updated code to handle bribes, with tests and upgrade tests:
https://github.com/GalloDaSballo/vested-cvx/tree/cvx.1.1

**Comment by GalloDaSballo** [comment]
@sajanrajdev @petrovska-petro Please review the above, if looks good do publish screenshots of tests passing

**Comment by petrovska-petro** [comment]
1.1.1 release deployed: https://etherscan.io/address/0xa8884bd2273e442afc5dea88bdb9c124fe5ae680#contracts

**Comment by GalloDaSballo** [comment]
TODO: Upgrade Strat to allow to specify a target contract for claiming rewards
Use something like
`claimConvexRewards(address contract, ...rest)`

This way we can specify the target that way
