### ISSUE TITLE
ARBITRUM Curve tricrypto

### ISSUE THREAD

**Issue by shuklaayush** [Badger-Finance/badger-strategies#12]
# Strategy Review
**Note:** This is the same strategy as #11 but with a different Curve LP token

Release:
https://github.com/shuklaayush/arbitrum-tricrypto-curve-strat/tree/b0.3

Description
Deposit tricrypto cLP
Stake them in gauge
Harvest CRV
50% sent to badgerTree
Rest auto-compounded -> CRV -> wBTC -> more cLP

## Due Diligence Document  (Link, but could also just be a .md file in repo)
Same as from Mainnet

## Deployed Contract (If present)
Not yet

## Review By
* Ongoing: 
  - [x] @GalloDaSballo 
  - [x] @dapp-whisperer 
  - [x] @sajanrajdev 
* Completed:

## Review by Security Board
* Not started

## Test Checks (screenshot of all test passing)
![image](https://user-images.githubusercontent.com/27727946/133663984-3aa36a83-c739-46b6-ba1b-a90c5b2c9e74.png)

**Comment by dapp-whisperer** [comment]
**Tricrypto Deploy**
Strategy Logic: 0x98dd0cBd5d32bA198A445dE0c4F0aE6B5B56261A
Strategy Proxy: 0xE83A790fC3B7132fb8d7f8d438Bc5139995BF5f4
Vault Proxy: 0x4591890225394BF66044347653e112621AF7DDeb

**Comment by GalloDaSballo** [comment]
Update for Strategy
Update strategy to use SWAPR_ROUTER
Added test to try upgrading

https://github.com/GalloDaSballo/arbitrum-tricrypto-curve-strat/releases/tag/upgrade.1
