### ISSUE TITLE
 ARBITRUM - Swapr WBTC / WETH swprLP

### ISSUE THREAD

**Issue by GalloDaSballo** [Badger-Finance/badger-strategies#13]
# Strategy Review
Take WBTC/WETH swprLP, stake in stakingContract
50% autocompound
50% sent to badgerTree as Helper Vault

### Code Link 
https://github.com/GalloDaSballo/arbitrum-wbtc-eth-swapr/tree/v1.0

## Due Diligence Document  (Link, but could also just be a .md file in repo)
See below

## Deployed Contract (If present)
Deploy info bewlo

## Reviews
[X] Security Board / Auditor
[X] @shuklaayush
[] @sajanrajdev 
[] @dapp-whisperer 

## Test Checks (screen shot of all test passing)

<img width="1207" alt="Screenshot 2021-09-28 at 15 49 05" src="https://user-images.githubusercontent.com/13383782/135099925-596c8e1d-9932-434b-988f-c8fd50b88ea7.png">

**Comment by GalloDaSballo** [comment]
Verification of the source code for initial `stakingContract`

>>> from brownie import network
 
>>> network.web3.eth.get_code("0xe2A7CF0DEB83F2BC2FD15133a02A24B9981f2c17")
HexBytes('0x363d3d373d3d3d363d73d28629981518e2b2cd2d5125b371f9810bf37ba25af43d82803e903d91602b57fd5bf3')

**Comment by shuklaayush** [comment]
### Comments
- Tests should check that the helper vault balance of `badgerTree` increases
- `_beforeHelper` in `harvest()` isn't being used anywhere. I guess the intention was to use it to process the reward fees: `_processRewardsFees(_afterHelper.sub(_beforeHelper), WETH_SWAPR_LP);`
https://github.com/GalloDaSballo/arbitrum-wbtc-eth-swapr/blob/rfc.0/contracts/MyStrategy.sol#L258-L259

---
`stakingContract` minimal proxy points to the same ERC20StakingRewardsDistribution logic contract as in #16 

![image](https://user-images.githubusercontent.com/27727946/135136482-d43f5614-3913-4aab-aa69-7c0e8c350cd8.png)
https://arbiscan.io/address/0xd28629981518e2b2cd2d5125b371f9810bf37ba2#code

**Comment by GalloDaSballo** [comment]
Updated `confirm_harvest` to check increase of HELPER_VAULT in badgerTree

<img width="915" alt="Screenshot 2021-09-28 at 20 15 45" src="https://user-images.githubusercontent.com/13383782/135142989-7ba77f50-b6ab-47b9-9508-c5bb7bb200ca.png">

Strat is now using `_afterHelper` to determine earned rewards
<img width="761" alt="Screenshot 2021-09-28 at 20 16 11" src="https://user-images.githubusercontent.com/13383782/135143052-b1e2fc5e-be44-4660-9514-01ae3f36edc8.png">

New Release:
https://github.com/GalloDaSballo/arbitrum-wbtc-eth-swapr/tree/rfc.1

@shuklaayush lkm if it LG

**Comment by shuklaayush** [comment]
I'm nit-picking, but `_afterHelper` variable name is a bit misleading here since it's actually the helper lp _gained_

Anyways, tests passing
![image](https://user-images.githubusercontent.com/27727946/135153851-94c34dd7-bff4-42a2-ac5c-a9d83965e90e.png)

LGTM

**Comment by GalloDaSballo** [comment]
Renamed

While at it also changed fee capture for the portion we send to badgerTree to be in Helper Vault so it auto-compounds for governance and strategist as well

Changed code 
<img width="824" alt="Screenshot 2021-09-28 at 21 59 33" src="https://user-images.githubusercontent.com/13383782/135157187-bd46d3d9-17ce-4146-aab0-172f929f01c5.png">

Test passing
<img width="946" alt="Screenshot 2021-09-28 at 21 59 43" src="https://user-images.githubusercontent.com/13383782/135157205-34faad98-8a90-4f97-8514-3b25527efd12.png">

Latest Release:
https://github.com/GalloDaSballo/arbitrum-wbtc-eth-swapr/tree/rfc.2

**Comment by GalloDaSballo** [comment]
Removed the extra logic that is no longer needed:
https://github.com/GalloDaSballo/arbitrum-wbtc-eth-swapr/tree/rfc.3

<img width="1202" alt="Screenshot 2021-09-28 at 22 10 54" src="https://user-images.githubusercontent.com/13383782/135158598-1d61ce91-558c-43f9-8f75-f96d687069e1.png">

**Comment by GalloDaSballo** [comment]
Audit by Thunder:
https://gist.github.com/pauliax/49b7ffcdb382d58159e3f6794411bd73

**Comment by GalloDaSballo** [comment]
Course of action:
- Fix on Github
- Do not redeploy
- If we end upgrading we can have those fixes then
- Use recommendations for newer vaults

**Comment by GalloDaSballo** [comment]
NOTE: Since there's no deployment, we'll fix and then deploy

**Comment by GalloDaSballo** [comment]
Implemented fixes, please do a peer review @dapp-whisperer @shuklaayush 

https://github.com/GalloDaSballo/arbitrum-wbtc-eth-swapr/tree/v1.0

**Comment by shuklaayush** [comment]
Looks good

**Comment by GalloDaSballo** [comment]
Deployment:

Controller Proxy was deployed at:  0x60A47583d59ba9F1A2Cf7558fB9A393A9d4C6f4D
Vault Proxy was deployed at:  0xaf9aB64F568149361ab670372b16661f4380e80B
Strategy Logic deployed at: 0xD1a9dd43518e389bB467efc6574F7f658B28d224
Strategy Proxy was deployed at:  0x43942cEae98CC7485B48a37fBB1aa5035e1c8B46


(It doesn't have the suggested tweak above, that will save us a little gas per call, hopefully not a deal breaker)

**Comment by GalloDaSballo** [comment]
Code is all verified

**Comment by GalloDaSballo** [comment]
Operation:

**Deposit**
v.depositAll({"from": a[0]})
https://arbiscan.io/tx/0xf6d4d5f741b6966b0a38fb0863e3fa56c5673cc6809ef004dafd4e57ead6609e

**Earn**
https://arbiscan.io/tx/0x592d1701cea0845a4b908eed7889a0d177b53b3cc98e4b38f0e534f4c062e8e2

**Harvest**
TODO: Tomorrow

**Comment by GalloDaSballo** [comment]
TODO: Swap stakingContract before pushing this to live

**Comment by GalloDaSballo** [comment]
Rewards are very small, added a second deposit
Harvest at EOD / around time of switching rewards contrat

**Comment by GalloDaSballo** [comment]
Update:

Changed Staking Contrac to: `0x418A639F01FAee054D3A823c227c7dC179C209Fa`

>>> s.setStakingContract("0x418A639F01FAee054D3A823c227c7dC179C209Fa", {"from": a[0]})
Transaction sent: 0xae0eb1737f3406720ea2c4af1246d1d2961096fbfd421ca561be180bf97e357f
  Gas price: 1.600363672 gwei   Gas limit: 2349741   Nonce: 77
  MyStrategy.setStakingContract confirmed   Block: 1794099   Gas used: 1718617 (73.14%)

<Transaction '0xae0eb1737f3406720ea2c4af1246d1d2961096fbfd421ca561be180bf97e357f'>

Will harvest later today with goal of seeing if SWAPR is also accured

**Comment by GalloDaSballo** [comment]
**Update**

Approved vault access:
https://github.com/Badger-Finance/badger-strategies/issues/16#issuecomment-931482976

Harvest:
>>> s.harvest({"from": a[0]})
Transaction sent: 0x9d1e22eaaccbd2a05dd570f20454b620e562ba9efdab14ceb47d4df920957166
  Gas price: 1.600363672 gwei   Gas limit: 5117954   Nonce: 80
  MyStrategy.harvest confirmed   Block: 1794564   Gas used: 3406802 (66.57%)

<Transaction '0x9d1e22eaaccbd2a05dd570f20454b620e562ba9efdab14ceb47d4df920957166'>

**Comment by GalloDaSballo** [comment]
@Darruma do you see the event for tree?

**Comment by GalloDaSballo** [comment]
Waiting for final review by @dapp-whisperer

**Comment by GalloDaSballo** [comment]
Config:

Set all parameters to production
<img width="730" alt="Screenshot 2021-09-30 at 22 34 22" src="https://user-images.githubusercontent.com/13383782/135526425-99bd423e-5d6b-49d5-8dd0-b746d3793552.png">


Run this script to verify:
https://github.com/GalloDaSballo/arbitrum-wbtc-eth-swapr/blob/main/scripts/3_production_setup.py

**Comment by GalloDaSballo** [comment]
GuestList (to connect via multisig):

Guestlist was deployed at:  `0xA4C14b78dBbE45fBbB7e98AEC2f6971DA7ab1c74`

Transaction sent: 0xde05a20ec89d1d1d539c864900a5376da8041cfc0a57fddb05c0c080cef98cc1
  Gas price: 1.585294126 gwei   Gas limit: 1085868   Nonce: 100
  VipCappedGuestListWrapperUpgradeable.setTotalDepositCap confirmed   Block: 1826406   Gas used: 873898 (80.48%)

Transaction sent: 0xef559f7fcfe10ac5bd20c37f9da52b344e7887c217ef6e8260b16506558811bf
  Gas price: 1.585294126 gwei   Gas limit: 833696   Nonce: 101
  VipCappedGuestListWrapperUpgradeable.setGuestRoot confirmed   Block: 1826409   Gas used: 664084 (79.66%)

Transaction sent: 0xe35a8c8ae4426d32c005d0722938c82f852fe9a3e5d5da3535a5c921dd9f49d3
  Gas price: 1.585294126 gwei   Gas limit: 867192   Nonce: 102
  VipCappedGuestListWrapperUpgradeable.transferOwnership confirmed   Block: 1826410   Gas used: 691767 (79.77%)

Cap Math:
0.01ETH + wBTC -> 0.000000026009090987
310 ETH is the amount
31000 * 0.000000026009090987
wBTC CAP 
0.00080628182

**Comment by GalloDaSballo** [comment]
GuestList (to connect to vault via multisig):

Guestlist was deployed at:  0x0c41A8613fbeFCC8d6e5dF1020DBb336F875247F

Transaction sent: 0xdb2fad51fcde1ef1f7110a36ddbc90fc4a8589fcdcf770ce8d4aa7c8c25f7c3a
  Gas price: 1.585294126 gwei   Gas limit: 1129315   Nonce: 104
  VipCappedGuestListWrapperUpgradeable.setUserDepositCap confirmed   Block: 1826748   Gas used: 908425 (80.44%)

Transaction sent: 0x28e5cc7e0ee1a95bb8877b141da3c22cdbcdf47cc7b0d5a63732bcee24f72036
  Gas price: 1.585294126 gwei   Gas limit: 1085884   Nonce: 105
  VipCappedGuestListWrapperUpgradeable.setTotalDepositCap confirmed   Block: 1826750   Gas used: 873914 (80.48%)

Transaction sent: 0x6329d3a7d08adc1bc37eb7e171fcfbe8ca541a5652b7499987985960fe5d2ec2
  Gas price: 1.585294126 gwei   Gas limit: 833713   Nonce: 106
  VipCappedGuestListWrapperUpgradeable.setGuestRoot confirmed   Block: 1826751   Gas used: 664098 (79.66%)

Transaction sent: 0x8bf6ebe73a5b7196f3bf69aab3ad677115c7e291dc5e9f9a5969810f0c46f738
  Gas price: 1.585294126 gwei   Gas limit: 867210   Nonce: 107
  VipCappedGuestListWrapperUpgradeable.transferOwnership confirmed   Block: 1826753   Gas used: 691781 (79.77%)


Settings:
    # NOTE: Input your vault address and guestlist parameters below:
    vaultAddr = "0xaf9aB64F568149361ab670372b16661f4380e80B"
    merkleRoot = "0x0000000000000000000000000000000000000000000000000000000000000000"
    totalCap = 0.00080628182 * 10 ** 18 ## 320 * 2 =640 eth which is roughly 2MLN usd
    userCap = MaxUint256

Math:
0.01ETH + wBTC -> 0.000000026009090987
310 ETH is the amount
31000 * 0.000000026009090987
wBTC CAP 
0.00080628182
