### ISSUE TITLE
Review: aTricrypto-Curve-Polygon-Strategy

### ISSUE THREAD

**Issue by sajanrajdev** [Badger-Finance/badger-strategies#2]
### Strategy Review

- [Spec](https://github.com/sajanrajdev/aTricrypto-Polygon-Curve-Strategy#polygon-curve-atricrypto-liquidity-pool-yield-strategy)
- [Code](https://github.com/sajanrajdev/aTricrypto-Polygon-Curve-Strategy/blob/main/contracts/MyStrategy.sol)

**Comment by GalloDaSballo** [comment]
See fixes:
https://github.com/sajanrajdev/aTricrypto-Polygon-Curve-Strategy/pull/1

**Comment by GalloDaSballo** [comment]
Chain.sleep to get interest
<img width="541" alt="Screenshot 2021-08-02 at 20 37 25" src="https://user-images.githubusercontent.com/13383782/127908109-9e68431d-14d4-4f18-a528-4a0709f6c668.png">

Use of interfaces
<img width="723" alt="Screenshot 2021-08-02 at 20 37 30" src="https://user-images.githubusercontent.com/13383782/127908116-424e3158-6019-4c0c-a4ae-10fc7781a476.png">

More protectedTokens
<img width="767" alt="Screenshot 2021-08-02 at 20 38 17" src="https://user-images.githubusercontent.com/13383782/127908186-b097b0a0-95e3-45a9-bb80-b7fd74b3b37f.png">

**Comment by GalloDaSballo** [comment]
LGTM

Will stake in gauge
Will harvest, if anything is there it will take 20% fee and swap from wMATIC to WBTC and invest
Will take 20% fee for CRV and send rest to BadgerTree

Checked liquidity (just like prev strat)

Tests are passing
<img width="1118" alt="Screenshot 2021-08-02 at 20 43 29" src="https://user-images.githubusercontent.com/13383782/127908765-a9830026-2663-46da-8d12-3a99b45ab2a7.png">

**Comment by sajanrajdev** [comment]
> See fixes:
> [sajanrajdev/aTricrypto-Polygon-Curve-Strategy#1](https://github.com/sajanrajdev/aTricrypto-Polygon-Curve-Strategy/pull/1)

Changes merged, thanks!

**Comment by sajanrajdev** [comment]
Deployment and Production tests update:

Controller: 0x12097e9755aBf710166D0027c1a2ef7609833D74
Registry: 0x22765948A3d5048F3644b81792e4E1aA7ea3da4a

aTricrypto Curve:

Strategy: 0xDb0C3118ef1acA6125200139BEaCc5D675F37c9C
Sett: 0x85E1cACAe9a63429394d68Db59E14af74143c61c
Want: 0x8096ac61db23291252574d49f036f0f9ed8ab390

Status: Wired up and unpaused

Added to registry under Author: 0xeE8b29AA52dD5fF2559da2C50b1887ADee257556

**Comment by axejintao** [comment]
@sajanrajdev is that the correct want?
0xE7a24EF0C5e95Ffb0f6684b813A78F2a3AD7D171

**Comment by sajanrajdev** [comment]
Test assets deposited and operating functions tested and working in production:
- sett.earn(): https://polygonscan.com/tx/0x13650cf40c677db1e898ad1ae196c790d93e9303346e9c2174c1164714164062
- strategy.harvest(): https://polygonscan.com/tx/0x339a8f165b67d983cf27b612bac961cb7cd0245a1240790fc4dc196209fd3740
- strategy.tend(): https://polygonscan.com/tx/0x093d7695f62af7c5acf24499f6f28953418e89a9ecdbd571ba28b55493cc7588

**Comment by sajanrajdev** [comment]
Production parameters were updated to the following for both the strategy and vault where applies:

governance = 0x4977110Ed3CD5eC5598e88c8965951a47dd4e738
strategist = 0x4977110Ed3CD5eC5598e88c8965951a47dd4e738
controller = 0xc00e71719d1494886942d6277daea20494cf0eec
keeper = 0x46fa8817624eea8052093eab8e3fdf0e2e0443b2
guardian = 0xCD3271021e9b35EF862Dd98AFa826b8b5198826d

withdrawalFee = 50

**Comment by GalloDaSballo** [comment]
Deprecated as aTricrypto3 is now the standard
