### ISSUE TITLE
Vaults 1.5

### ISSUE THREAD

**Issue by GalloDaSballo** [Badger-Finance/badger-strategies#20]
Initial Approval:
https://discord.com/channels/785315893960900629/809190717263970330/897482415835074620

Spec / Notes from Dapp:
https://docs.google.com/document/d/13NTTevfdtJF0PMMsqqCE_I2XF1A6pHLBPFNxbK0b4qY/edit

New Notes and Code:
https://github.com/tabshaikh/badger-sett-1.5

**Comment by GalloDaSballo** [comment]
TODO: 
- Add Audit to repo
- Push final touches to V1.5 and Mix

**Comment by sajanrajdev** [comment]
Review of latest changes - Integration with BadgerRewards: https://github.com/Badger-Finance/badger-vaults-1.5/tree/feat-rewards

- Adds hooks to `notifyTransfer` on the badgerRewards contract whenver _mint(), _burn() or _transfer() is called. The Mint and Burn hooks properly utilize the Address(0) as needed to be recognized as deposit and withdrawal by the rewards contract and handled accordingly.
- Modifies the transfer to the tree operation to call `badgerRewards.addReward()` instead during a TreeDistribution event.
- Tests were adapted to reflect these changes and a new test was added to asses the badgerRewards proper accounting of vault interactions.

All tests are passing: 
![image](https://user-images.githubusercontent.com/25463788/160726942-7aefb59b-642b-4a65-988c-f0bf73702fa1.png)

LGTM

**Comment by GalloDaSballo** [comment]
Vaults 1.5 is live
