### ISSUE TITLE
MAINNET - ibBTC CRV LP Convex Strat

### ISSUE THREAD

**Issue by GalloDaSballo** [Badger-Finance/badger-strategies#25]
# Strategy Review
Convex StakingOptimizer Strat for ibBTC CRV LP

### Code Link 
https://github.com/Badger-Finance/strategy-convex-staking-optimizer/blob/v1.3/contracts/StrategyConvexStakingOptimizer.sol

## Due Diligence Document  (Link, but could also just be a .md file in repo)
DD Inherited by Convex Old Strats

## Deployed Contract (If present)
TODO @sajanrajdev  Please add this

## Review By
* Ongoing: 
[] @GalloDaSballo 
[] @dapp-whisperer 
[] @shuklaayush 
Shadow Reviewer:
[] @tabshaikh 

* Completed:

**Comment by GalloDaSballo** [comment]
Addresses:

Vault Proxy:
https://etherscan.io/address/0xaE96fF08771a109dc6650a1BdCa62F2d558E40af#readProxyContract

Vault Logic:
https://etherscan.io/address/0xa762292a6a7fd944db1fe9389921e6f639b4c9e8#code

Controller Proxy:
https://etherscan.io/address/0xe505f7c2ffcce7ae4b076456bc02a70d8fe8d4d2#readProxyContract

Strategy Proxy:
https://etherscan.io/address/0x6D4BA00Fd7BB73b5aa5b3D6180c6f1B0c89f70D1#code

Strategy Logic:
https://etherscan.io/address/0x424d836778309a88b7dc46fa48e41d658db270eb#code

**Comment by GalloDaSballo** [comment]
Wiring confirmed via going through contracts, waiting on @sajanrajdev governance delegation to verify production parameters

**Comment by sajanrajdev** [comment]
Proxy admin on contracts set to the Timelock proxy admin for the Vault and Strategy and the Governance proxyAdmin for the Controller:
![image](https://user-images.githubusercontent.com/25463788/142003365-2d8d3f55-d49b-4557-bebe-1ae16e7f74bc.png)

  "devProxyAdmin": "0x20Dce41Acca85E8222D6861Aa6D23B6C941777bF",
  "devUngatedProxyAdmin": "0x9215cBDCDe25629d0e3D69ee5562d1b444Cf69F9",

**Comment by sajanrajdev** [comment]
Approve conract access was called on the Vault for the Tech Ops multisig;
`0xaE96fF08771a109dc6650a1BdCa62F2d558E40af.approveContractAddress('0x86cbD0ce0c087b482782c181dA8d191De18C8275')`

Tx: https://etherscan.io/tx/0x4878a0d292ed0af345d24afb91921edfeb6d1debbc0faa8adb1d872a2f007ee0

**Comment by GalloDaSballo** [comment]
Can confirm Logics are the one I already reviewed:
https://github.com/Badger-Finance/strategy-convex-staking-optimizer/pull/12


Waiting to Confirm: Tests, Config and Governance settings

**Comment by GalloDaSballo** [comment]
Vault added to registry (under developer key): 
https://etherscan.io/tx/0xdd359e3dd8dcfa1aba2f069ec073789145e42bed8eb1a8097381e4248712d878


@axejintao @mitche50

**Comment by sajanrajdev** [comment]
earn() called on Vault before delegation: https://etherscan.io/tx/0x88237fd7b623e5d56d471e01d202ea9e52ee23a76c324d7ecc98fd6ee0748a46

**Comment by sajanrajdev** [comment]
- Strategist set to devMultisig on controller: https://etherscan.io/tx/0xd23e7927a332b8b3739c781427c4f611170d67d4bc18193e8f92d1747e5cf229

- Keeper set to Keeper_acl on controller: https://etherscan.io/tx/0xdb7504f664fb0037f0c9a514cb4d1ca18c6e6fc386e57f8a056b8d0bb7450e53

**Comment by sajanrajdev** [comment]
Confirmed controller.rewards() points to devMultisig: 
![image](https://user-images.githubusercontent.com/25463788/142034099-928b54bd-94e8-4861-96d9-2aa270b23403.png)

**Comment by sajanrajdev** [comment]
Delegated governance to TechOps:
- Vault: https://etherscan.io/tx/0xe3d7ea24b3b72fb30eb03d856e915ecaab41e2b2a9198304acbc4073a8342c46
- Controller: https://etherscan.io/tx/0x2dcf13839344e40cf5973052757d3e72a427b445ec321a8db7f0098e2e680f39
- Strategy: https://etherscan.io/tx/0xef809db765b8560d4fa83f1224c048da675415f639295ec0ba5455fa385ba3d9

**Comment by sajanrajdev** [comment]
Governance delegated from TechOps to devMultisig for the three contracts:
- https://etherscan.io/tx/0xde7396e04a727fd34fedf389d5105f53c22816938f5e1973a06e5e336a59310f
- https://etherscan.io/tx/0x928e7873d75882fda0afdca5d861a835310f8c90d89e41a1526742bb60d0b1c5
- https://etherscan.io/tx/0xdef0e54f83f4d25c51ae80abc5056172d2dd0d8172a56de6107a58ab90a56865

**Comment by sajanrajdev** [comment]
With governance delegated, ran parameters check script once more and now all parameters pass correctly for this strat:

Script: https://github.com/Badger-Finance/strategy-convex-staking-optimizer/blob/main/scripts/5_production_parameters_check.py

Result:
![image](https://user-images.githubusercontent.com/25463788/142244773-638921a5-ca70-412c-a920-513a2d23cb08.png)
