### ISSUE TITLE
cvxCRV - Lock CVX - Version 1.2

### ISSUE THREAD

**Issue by GalloDaSballo** [Badger-Finance/badger-strategies#29]
# Strategy Review
Locks CVX instead of dumping

### Code Link 
https://github.com/Badger-Finance/strategy-convex-helpers/pull/2

## Review By
* Ongoing: 
[X] @sajanrajdev 
[X] @shuklaayush 
[X] @tabshaikh 
* Completed:

## Review by Security Board
* Not started / ongoing / completed

**Comment by GalloDaSballo** [comment]
TODO: Write upgrade test

**Comment by GalloDaSballo** [comment]
Update:
Code + Test for Upgrade:
https://github.com/Badger-Finance/strategy-convex-helpers/pull/3

**Comment by GalloDaSballo** [comment]
Ticket:
https://github.com/Badger-Finance/badger-ape/issues/853

**Comment by GalloDaSballo** [comment]
TODO: Deploy and Verify

**Comment by GalloDaSballo** [comment]
TODO:
https://github.com/Badger-Finance/strategy-convex-helpers/pull/2#discussion_r778981476
https://github.com/Badger-Finance/strategy-convex-helpers/pull/2#discussion_r778992262
https://github.com/Badger-Finance/strategy-convex-helpers/pull/2#discussion_r778992027

**Comment by GalloDaSballo** [comment]
Update: 
https://github.com/Badger-Finance/strategy-convex-helpers/pull/4

**Comment by GalloDaSballo** [comment]
Merge:
https://github.com/Badger-Finance/strategy-convex-helpers/pull/4

**Comment by GalloDaSballo** [comment]
Running Tests again and deploying and verifying

**Comment by GalloDaSballo** [comment]
Deployed:
https://etherscan.io/address/0xDaf39C0432955AE7e5E1195BCdD58f3fADeE64c2

**Comment by GalloDaSballo** [comment]
Tests are passing (I've removed bCVX tests to make it faster)
<img width="1198" alt="Screenshot 2022-01-07 at 17 24 54" src="https://user-images.githubusercontent.com/13383782/148574223-ee0fbc28-d780-44d1-862e-daaee09cbeb6.png">

**Comment by shuklaayush** [comment]
Changes lgtm. Adds a couple of constants and changes cvxCrv `harvest` to deposit into bveCvx instead of autocompounding
![image](https://user-images.githubusercontent.com/27727946/148575194-f9f6ae61-e8ec-409f-866a-34aa1e467c57.png)

---

Looks like harvest tests are failing on the repo because cvxCrv has lost it's peg (temporarily?). Increased `crvCvxCrvSlippageToleranceBps` to 10% to confirm all tests are still passing
![image](https://user-images.githubusercontent.com/27727946/148583298-f1d51162-ce6f-4e06-a94a-d985fc302fc2.png)

**Comment by GalloDaSballo** [comment]
> Changes lgtm. Adds a couple of constants and changes cvxCrv `harvest` to deposit into bveCvx instead of autocompounding ![image](https://user-images.githubusercontent.com/27727946/148575194-f9f6ae61-e8ec-409f-866a-34aa1e467c57.png)
> 
> Looks like harvest tests are failing on the repo because cvxCrv has lost it's peg (temporarily?). Increased `crvCvxCrvSlippageToleranceBps` to 10% to confirm all tests are still passing ![image](https://user-images.githubusercontent.com/27727946/148583298-f1d51162-ce6f-4e06-a94a-d985fc302fc2.png)

Agreed, I ran test without bCVX as we'll pause harvest on that (and it's outside scope for this review)
