### ISSUE TITLE
Review: POLYGON ibBTC-wBTC-SLP-Polygon-Strategy

### ISSUE THREAD

**Issue by sajanrajdev** [Badger-Finance/badger-strategies#3]
### Strategy Review

- [Spec](https://github.com/sajanrajdev/ibBTC-wBTC-SLP-Polygon-Strategy#ibbtcwbtc-sushi-liquidity-pool-yield-strategy)
- [Code](https://github.com/sajanrajdev/ibBTC-wBTC-SLP-Polygon-Strategy/blob/main/contracts/MyStrategy.sol)

**Comment by GalloDaSballo** [comment]
LGTM

Will receive Sushi, take a 20% performance fee and airdrop the rest to badgertree


Will receive wMATIC and swap 50% to wBTC and 50% to ibBTC
Will take a 20% Performance Feet on want

Verified Liquidity for wMATIC -> wETH, wETH -> wBTC and wBTC -> ibBTC

Not sure if we should just swap all to wBTC and then swap half the wBTC to ibBTC
<img width="867" alt="Screenshot 2021-08-02 at 17 22 09" src="https://user-images.githubusercontent.com/13383782/127885206-4e15befb-5ca6-46e2-b17d-c2350d7ae081.png">

I think this is fine (and easier to re-use in the future)

@dapp-whisperer what do you think?

**Comment by GalloDaSballo** [comment]
Changes to strat:
Added more protected tokens

Fixed tests
https://github.com/sajanrajdev/ibBTC-wBTC-SLP-Polygon-Strategy/pull/1

**Comment by sajanrajdev** [comment]
@GalloDaSballo, merged!

**Comment by sajanrajdev** [comment]
Deployment and Production tests update:

Controller: 0x12097e9755aBf710166D0027c1a2ef7609833D74
Registry: 0x22765948A3d5048F3644b81792e4E1aA7ea3da4a

ibBTC/wBTC SLP:

Strategy: 0xDed61Bd8a8c90596D8A6Cf0e678dA04036146963
Sett: 0xEa8567d84E3e54B32176418B4e0C736b56378961
Want: 0x8F8e95Ff4B4c5E354ccB005c6B0278492D7B5907

Status: Wired up and upaused

Added to registry under Author: 0xeE8b29AA52dD5fF2559da2C50b1887ADee257556

Test assets deposited and operating functions tested and working in production:
- sett.earn(): https://polygonscan.com/tx/0x72fd1069da85260af0cfe54165b537cb07785104a2518e804f4009dcb756fd97
- strategy.harvest(): https://polygonscan.com/tx/0xc5c31ffc1035d8edc0861aab326da68dbb961a81532d28d3547150e36b2628b5
- strategy.tend(): https://polygonscan.com/tx/0x1003c40e25321fb4c325d315520e9b7b5d387345ce7d497151f1a752a18ba5da

**Comment by sajanrajdev** [comment]
The following adjustments were made to the strategy and are now deployed:
- The `pid` variable was turned into a constant.
- The `sl` (slippage tolerance) variable's value was set on init.
- The strategy's name was changed to match the standard format.
- Unused fee variables were removed.

The changes can be found on the latest commit: https://github.com/sajanrajdev/ibBTC-wBTC-SLP-Polygon-Strategy/commit/a946f17020005cac54115efe39ed8cfa3de63bd8

All tests are passing and the strat was tested in production as shown above.

**Comment by GalloDaSballo** [comment]
LGTM

All tests passing
<img width="1200" alt="Screenshot 2021-08-09 at 15 06 31" src="https://user-images.githubusercontent.com/13383782/128710964-90f1fb6e-ca97-4896-af2f-b176d7a54c06.png">

The strat will deposit ibBTC/wBTC SLP in MasterChefV2 and harvest rewards
wMatic is compounded back
SUSHI is sent to badger tree
20% Perf fee

Harvest returns uint256
Harvest emits basic event
BadgerTree emission event is set up as well

NOTICES:
<img width="306" alt="Screenshot 2021-08-09 at 15 04 26" src="https://user-images.githubusercontent.com/13383782/128710660-c781e52e-0374-4ff6-b2db-36783c527b6a.png">
Sl may cause issues, keep that in mind for debugging
Keep this in mind for the future

**Comment by sajanrajdev** [comment]
Production parameters were updated to the following for both the strategy and vault where applies:

governance = 0x4977110Ed3CD5eC5598e88c8965951a47dd4e738
strategist = 0x4977110Ed3CD5eC5598e88c8965951a47dd4e738
controller = 0xc00e71719d1494886942d6277daea20494cf0eec
keeper = 0x46fa8817624eea8052093eab8e3fdf0e2e0443b2
guardian = 0xCD3271021e9b35EF862Dd98AFa826b8b5198826d

withdrawalFee = 50
