### ISSUE TITLE
MAINNET - CRV MIM-3Crv LP

### ISSUE THREAD

**Issue by sajanrajdev** [Badger-Finance/badger-strategies#30]
# Strategy Review

### Description
According to the BIP 80 (See [Forum](https://forum.badger.finance/t/bip-80-restitution-of-non-recoverable-assets-via-rembadger-sett/5362)), a MIM-3Crv strategy must be developed in order to aid the hack restitution efforts. The performance fee of this strategy will be used to buy BADGER and incentivize the remBADGER vault.

This strategy will be based on the StrategyConvexStakingOptimizer V1.3 (latest - same as ibBTC Crv) but will contain a few adjustments to its harvest() function. The harvest function should process fees on the harvested tokens directly: CVX, CRV and cvxCRV.

### Code Link 
Issue: https://github.com/sajanrajdev/strategy-convex-stables/issues/1
PR: https://github.com/sajanrajdev/strategy-convex-stables/pull/2

## Due Diligence Document  (Link, but could also just be a .md file in repo)
https://docs.google.com/document/d/1KmbS1X0aixBRHBvfIPsPnDnRo1ksXuESYq9shzndrOU/edit#heading=h.sqpkuofen9jn

## Review By
* Ongoing: 
* [] @GalloDaSballo 
* [] @dapp-whisperer 
* [] @shuklaayush 
* [] @tabshaikh 

## Review by Security Board
* Ongoing

## Test Checks (screen shot of all test passing)

![image](https://user-images.githubusercontent.com/25463788/149010037-a51fddd7-7b23-4937-8a63-d238249ceb39.png)

**Comment by sajanrajdev** [comment]
@GalloDaSballo @shuklaayush @tabshaikh @dapp-whisperer, PR with the implementations for the Stablecoin strategies is ready for review: Badger-Finance/strategy-convex-staking-optimizer#19

**Comment by sajanrajdev** [comment]
New implementations are ready for review at the following PR: sajanrajdev/strategy-convex-stables#2

**Comment by sajanrajdev** [comment]
Logic deployed and verified: https://etherscan.io/address/0x3bb555e488e0758339a0de464e0fa866268c9b93#code

**Comment by sajanrajdev** [comment]
Contracts deployed:
```
Controller: 0x3F61344BA56df00dad9bBcA05d98CA2AeC43Ba0B

MIM-3Crv LP
Strategy: 0x8DE00c817C595BD5D8caD37c4bE65ed1bB11502F
Vault: 0x19E4d89e0cB807ea21B8CEF02df5eAA99A110dA5
Want: 0x5a6A4D54456819380173272A5E8E9B9904BdF41B
```

**Comment by sajanrajdev** [comment]
There was a bug within the logic which was fixed in the following [PR](https://github.com/Badger-Finance/strategy-convex-stables/pull/3). The logic was re-deployed, a new strategy proxy was setup and it was wired-up to the controller.

The new strategy address is: 0x6D1de7B7F586f17d573BB57ce39159ff6245A285

**Comment by sajanrajdev** [comment]
Production tests and fees/strategist setup:
Deposit: https://etherscan.io/tx/0x45de866582e0df51ea9635f000b45f5c0693160f30bda12fcf832ede289930a2

Gov Perf Fee to 0: https://etherscan.io/tx/0x9c507d97797c6b671668eda954f93b1f39b01efde01a48ddc248c02effb85cf9
Strat Perf Fee to 20%: https://etherscan.io/tx/0xe4811959defd96318f53050168fe841e8a4d5dc33f2ae2b9b11da2a4dcccc967
setStrategist: https://etherscan.io/tx/0xbec7c951783d4846f8c61f0d7a79efa7633ecc7face6603c7a920b934d2ed398

Migrate: https://etherscan.io/tx/0x021af5e61a5567b2ecf6bda64e33b0a64f6cf0760b3584dac2e7e4257113fa65
Earn: https://etherscan.io/tx/0xfa0f961c5c86985432c25351ec5affa8967fe7c3c8b29701cbdc7543915911f5
Harvest: https://etherscan.io/tx/0x131a667fc7a08271cb2f75421c82cd22c3e897931ef6918959935bc11877bffc

**Comment by sajanrajdev** [comment]
Harvests properly process performance fee on CVX and cvxCRV and distribute the rest to the tree in the form of bcvxCRV and bveCVX.

**Comment by GalloDaSballo** [comment]
Production tests and fees/strategist setup:
Deposit: https://etherscan.io/tx/0x45de866582e0df51ea9635f000b45f5c0693160f30bda12fcf832ede289930a2

Gov Perf Fee to 0: https://etherscan.io/tx/0x9c507d97797c6b671668eda954f93b1f39b01efde01a48ddc248c02effb85cf9
Strat Perf Fee to 20%: https://etherscan.io/tx/0xe4811959defd96318f53050168fe841e8a4d5dc33f2ae2b9b11da2a4dcccc967
setStrategist: https://etherscan.io/tx/0xbec7c951783d4846f8c61f0d7a79efa7633ecc7face6603c7a920b934d2ed398

Migrate: https://etherscan.io/tx/0x021af5e61a5567b2ecf6bda64e33b0a64f6cf0760b3584dac2e7e4257113fa65
Earn: https://etherscan.io/tx/0xfa0f961c5c86985432c25351ec5affa8967fe7c3c8b29701cbdc7543915911f5
Harvest: https://etherscan.io/tx/0x131a667fc7a08271cb2f75421c82cd22c3e897931ef6918959935bc11877bffc

**Comment by sajanrajdev** [comment]
Delegation:
Controller Gov: https://etherscan.io/tx/0x032dd4d7fc0bb916663a3d4df03839ea3eae144dd4ac73abb8788842bacb629e

Change Strat ProxyAdmin: https://etherscan.io/tx/0xa9ae8b6855888ef38357d8d129025f17d4e8c906ca6bb4c1cfc12c427f7ba665
Strategy Gov: https://etherscan.io/tx/0x50abd7d7c5b9f4a89d326f14c4f997fd8fe120d19770f21709216c4d0445bb37
Vault Gov: https://etherscan.io/tx/0x9a48c5e882ddb5f930c2a4c7ae440de5560c1f92cfa35b284c3e4d6e339c2043

**Comment by GalloDaSballo** [comment]
Controller Gov: https://etherscan.io/tx/0x032dd4d7fc0bb916663a3d4df03839ea3eae144dd4ac73abb8788842bacb629e

MIM-3Crv

Change Strat ProxyAdmin: https://etherscan.io/tx/0xa9ae8b6855888ef38357d8d129025f17d4e8c906ca6bb4c1cfc12c427f7ba665
Strategy Gov: https://etherscan.io/tx/0x50abd7d7c5b9f4a89d326f14c4f997fd8fe120d19770f21709216c4d0445bb37
Vault Gov: https://etherscan.io/tx/0x9a48c5e882ddb5f930c2a4c7ae440de5560c1f92cfa35b284c3e4d6e339c2043

**Comment by GalloDaSballo** [comment]
Live and earning, closing until we need edits

**Comment by sajanrajdev** [comment]
Caps were removed:
-Total: https://etherscan.io/tx/0x3b18c2855c3c62067be464430dc627a788c98b2820cac0ece72d1ffc3cd7a93c
- User: https://etherscan.io/tx/0x7e5be886f081f8849e21f1478426d30f40465ac826600f00124bf56cb45bd444
