### ISSUE TITLE
MAINNET - CRV Frax-3Crv LP

### ISSUE THREAD

**Issue by sajanrajdev** [Badger-Finance/badger-strategies#31]
# Strategy Review

### Description
According to the BIP 80 (See [Forum](https://forum.badger.finance/t/bip-80-restitution-of-non-recoverable-assets-via-rembadger-sett/5362)), a Frax-3Crv strategy must be developed in order to aid the hack restitution efforts. The performance fee of this strategy will be used to buy BADGER and incentivize the remBADGER vault.

This strategy will be based on the StrategyConvexStakingOptimizer V1.3 (latest - same as ibBTC Crv) but will contain a few adjustments to its harvest() function. The harvest function should process fees on the harvested tokens directly: CVX, CRV and cvxCRV.

### Code Link 
Issue: https://github.com/sajanrajdev/strategy-convex-stables/issues/1
PR: https://github.com/sajanrajdev/strategy-convex-stables/pull/2

## Due Diligence Document  (Link, but could also just be a .md file in repo)
https://docs.google.com/document/d/1KmbS1X0aixBRHBvfIPsPnDnRo1ksXuESYq9shzndrOU/edit#heading=h.sqpkuofen9jn

## Review By
* Ongoing: 
* [] @GalloDaSballo 
* [] @dapp-whisperer 
* [] @shuklaayush 
* [] @tabshaikh 

## Review by Security Board
* Ongoing

## Test Checks (screen shot of all test passing)

![image](https://user-images.githubusercontent.com/25463788/149010101-23f4bcde-2695-46d3-90d9-baa3790c8a14.png)

**Comment by sajanrajdev** [comment]
@GalloDaSballo @shuklaayush @tabshaikh @dapp-whisperer, PR with the implementations for the Stablecoin strategies is ready for review: Badger-Finance/strategy-convex-staking-optimizer#19

**Comment by GalloDaSballo** [comment]
As per discussion the strategy will change to harvest rewards with the goal of selling the for BADGER separately.
As such we will re-view the strategy after those changes have taken place

**Comment by sajanrajdev** [comment]
New implementations are ready for review at the following PR: sajanrajdev/strategy-convex-stables#2

**Comment by GalloDaSballo** [comment]
Tests are passing.
Code takes CRV_LP and stakes on Convex, claiming CVX and CRV which it then buys cvxCRV with.
Emits bCVX and bcvxCRV for depositors.
Issues performance fee as cvxCRV and CVX

**Comment by sajanrajdev** [comment]
Logic deployed and verified: https://etherscan.io/address/0x3bb555e488e0758339a0de464e0fa866268c9b93#code

**Comment by sajanrajdev** [comment]
Contracts deployed:
```
Controller: 0x3F61344BA56df00dad9bBcA05d98CA2AeC43Ba0B

Frax-3Crv LP
Strategy: 0xA4772a2504aCCBEd8Db04F393A21BfA621AC621D
Vault: 0x15cBC4ac1e81c97667780fE6DAdeDd04a6EEB47B
Want: 0xd632f22692FaC7611d2AA1C0D552930D43CAEd3B
```

**Comment by sajanrajdev** [comment]
There was a bug within the logic which was fixed in the following [PR](https://github.com/Badger-Finance/strategy-convex-stables/pull/3). The logic was re-deployed, a new strategy proxy was setup and it was wired-up to the controller.

The new strategy address is: 0xf1e6aB438136D391fdafff5263f129d434BC6efB

**Comment by sajanrajdev** [comment]
Contract access granted for new strat on bcvxCRV: https://etherscan.io/tx/0xc82431a4bbc6f0469ed23f7a2c2c24b99e4fb1fb1faaf891f41e3831f6746316

**Comment by sajanrajdev** [comment]
Production tests:
Deposit: https://etherscan.io/tx/0x93bea588d35917ff85b26277d7a1c80ae6e14169b7a2207aebf9d21a64210fdb

Migrate: https://etherscan.io/tx/0x9f11940a6827c654d9c92b42674490c54193aed970e42fd9e895762bc6ff9983
Earn: https://etherscan.io/tx/0x5e254605170d04d4466d0aca19f9d1b46e23ea91f873e167610bd52069c1f431
Harvest: https://etherscan.io/tx/0x068e727a260eb09373ca183211261b6f84c496e673a9aa7835520297b141f80d

Gov Perf Fee to 0: https://etherscan.io/tx/0x6a5d5cb03bd4bcfd1aa9994d6f4f7eae36e1fd97ee3898f32db89aec3d048ef0
Strat Perf Fee to 20%: https://etherscan.io/tx/0x6fd25ddd4fa83cca6a967b0ecfc0fd37a7044ad9531024b0de85c0fb4aba71a4
setStrategist: https://etherscan.io/tx/0x2bfc2ea1d509ce678e19cfd37d39a1dd258b15685870f2b512d067184079da2f

**Comment by sajanrajdev** [comment]
Harvests properly process performance fee on CVX and cvxCRV and distribute the rest to the tree in the form of bcvxCRV and bveCVX.

**Comment by GalloDaSballo** [comment]
Deposit: https://etherscan.io/tx/0x93bea588d35917ff85b26277d7a1c80ae6e14169b7a2207aebf9d21a64210fdb

Gov Perf Fee to 0: https://etherscan.io/tx/0x6a5d5cb03bd4bcfd1aa9994d6f4f7eae36e1fd97ee3898f32db89aec3d048ef0
Strat Perf Fee to 20%: https://etherscan.io/tx/0x6fd25ddd4fa83cca6a967b0ecfc0fd37a7044ad9531024b0de85c0fb4aba71a4
setStrategist: https://etherscan.io/tx/0x2bfc2ea1d509ce678e19cfd37d39a1dd258b15685870f2b512d067184079da2f

Migrate: https://etherscan.io/tx/0x9f11940a6827c654d9c92b42674490c54193aed970e42fd9e895762bc6ff9983
Earn: https://etherscan.io/tx/0x5e254605170d04d4466d0aca19f9d1b46e23ea91f873e167610bd52069c1f431
Harvest: https://etherscan.io/tx/0x068e727a260eb09373ca183211261b6f84c496e673a9aa7835520297b141f80d

**Comment by sajanrajdev** [comment]
Delegation:
Controller Gov: https://etherscan.io/tx/0x032dd4d7fc0bb916663a3d4df03839ea3eae144dd4ac73abb8788842bacb629e

Change Strat ProxyAdmin:
https://etherscan.io/tx/0xb0a9720408de0017151b6cd5ce7c6418f2cb0b57aa543ecc219a117eccf4ef65
Strategy Gov: https://etherscan.io/tx/0x5c90eab7896a83784d67e022728f2119532ffc41ba27b74862dafef503ef06e3
Vault Gov: https://etherscan.io/tx/0xfba8ff414fc7ad85abfd63d3a5d3c7384b6a3d658fda7bb5c1069d9e52feecc2

**Comment by GalloDaSballo** [comment]
Controller Gov: https://etherscan.io/tx/0x032dd4d7fc0bb916663a3d4df03839ea3eae144dd4ac73abb8788842bacb629e


FRAX-3Crv:

Change Strat ProxyAdmin:
https://etherscan.io/tx/0xb0a9720408de0017151b6cd5ce7c6418f2cb0b57aa543ecc219a117eccf4ef65
Strategy Gov: https://etherscan.io/tx/0x5c90eab7896a83784d67e022728f2119532ffc41ba27b74862dafef503ef06e3
Vault Gov: https://etherscan.io/tx/0xfba8ff414fc7ad85abfd63d3a5d3c7384b6a3d658fda7bb5c1069d9e52feecc2

**Comment by GalloDaSballo** [comment]
Live and earning, closing until we need edits

**Comment by sajanrajdev** [comment]
Caps were removed:
- Total: https://etherscan.io/tx/0x57f312db3212cafa96e81149e386a99ae052bc5e7d1c84de62a3f65faab98094
- User: https://etherscan.io/tx/0x6c971b6655ed28c74950de5b0ed8cf7de95f2bb4e75a29d5e03f5026ec553400
