### ISSUE TITLE
remBadger -  BADGER denominated increasing Vault

### ISSUE THREAD

**Issue by GalloDaSballo** [Badger-Finance/badger-strategies#32]
# Strategy Review

### Description
Initial Work: https://github.com/GalloDaSballo/remBadger

### Code Link 
Commit / Hash / Repo should be known from this.

## Due Diligence Document  (Link, but could also just be a .md file in repo)
https://docs.google.com/document/d/1KmbS1X0aixBRHBvfIPsPnDnRo1ksXuESYq9shzndrOU/edit#heading=h.xs8bufgp35wg

## Review By
* Ongoing: 
* Completed:

## Review by Security Board
* Not started / ongoing / completed

**Comment by GalloDaSballo** [comment]
Initial Release:
https://github.com/GalloDaSballo/remBadger/releases/tag/rfc.0

@shuklaayush @tabshaikh @sajanrajdev 
What do you think?

**Comment by GalloDaSballo** [comment]
Update:
https://github.com/GalloDaSballo/remBadger/releases/tag/rfc.1
@shuklaayush @tabshaikh @sajanrajdev 

Updated with more realistic lifecycle check:
https://github.com/GalloDaSballo/remBadger/blob/rfc.1/tests/test_remBadger_lifecycle.py

**Comment by tabshaikh** [comment]
LGTM remBadger.sol has functions (mintExtra - can be run only once, addMoreWant - deposit want) and test_remBadger_lifecycle.py. first mints then transfers badger to so ppfs > 1e18. also deposit is bricked and can be only run by governance

**Comment by sajanrajdev** [comment]
The new vault contract builds on top of the SettV4h contract so it includes the GAC and blackilist implementations. The following functions were added:
- `mintExtra`: mints an specific amount of extra shares to dilute the ppfs - also calls `brickDeposits()` in the process. (Only governance)
- `brickDeposits`: sets a flag to stop all deposits (including through mintExtra. 
- `addWant`: adds an specific amount of want to vault without minting new shares (increases ppfs) - emits an event with the amount for accounting. (Permissionessly)

Tests accurately simulate the expected lifecycle of the vault and ensures its restrictions. All tests are passing:
![image](https://user-images.githubusercontent.com/25463788/149562951-fbbcb58f-b257-4878-af84-3a41d75f36ab.png)

LGTM

**Comment by shuklaayush** [comment]
LG. Governance can mint some extra bTokens once and deposits can be bricked
Not a fan of `addWant` since it requires donating via an approval

**Comment by GalloDaSballo** [comment]
NOTE: as recommended by @shuklaayush we should just transfer the BADGER to the vault

**Comment by GalloDaSballo** [comment]
Update:
Removed `addWant`
https://github.com/GalloDaSballo/remBadger/releases/tag/rc.0

**Comment by GalloDaSballo** [comment]
Deployment:
Controller Proxy was deployed at:  0x4AD3ba40A8a65f0583602E1cfc37Efe7f7EA423f

RemBadger deployed at: 0x37336199B3e7C9B0FC61d4289e98Ad494cc7d52c
Vault Proxy was deployed at:  0x6aF7377b5009d7d154F36FE9e235aE1DA27Aea22

BrikedStrategy deployed at: 0x19331060810F29BbfC1b2Ea4d22C3E933E149cA1
Strategy was deployed at:  0xD8d8aE4A5363edb6C3E01759576Da04bcc3a947e

**Comment by GalloDaSballo** [comment]
Dev Wireup:
Transaction sent: 0xf5e8ebbc0917c48f24365ce1dcd7c5b9d6bf5341c2dd7e3a7022c993dc60fd63
  Gas price: 100.845467552 gwei   Gas limit: 59576   Nonce: 149
  Controller.approveStrategy confirmed   Block: 14036353   Gas used: 53805 (90.31%)

Transaction sent: 0x30fb679a3a6538f01f9f8366b3320474d16c55bceb28e3200da562fa8d7b9165
  Gas price: 98.606938617 gwei   Gas limit: 62378   Nonce: 150
  Controller.setStrategy confirmed   Block: 14036356   Gas used: 56314 (90.28%)

Transaction sent: 0x2a31c80bbf7ff1216ba1d816558e3c84f5b01b0ab464962ac0e350bc8dd534eb
  Gas price: 95.219300204 gwei   Gas limit: 59778   Nonce: 151
  Controller.setVault confirmed   Block: 14036359   Gas used: 53987 (90.31%)

**Comment by GalloDaSballo** [comment]
Update:
Contracts verified

Controller:
https://etherscan.io/address/0x4AD3ba40A8a65f0583602E1cfc37Efe7f7EA423f#code

RemBadger Logic:
https://etherscan.io/address/0x37336199b3e7c9b0fc61d4289e98ad494cc7d52c
RemBadger Proxy:
https://etherscan.io/address/0x6aF7377b5009d7d154F36FE9e235aE1DA27Aea22#code

BrikedStrategy Logic:
https://etherscan.io/address/0x19331060810F29BbfC1b2Ea4d22C3E933E149cA1#code
BrikedStrategy Proxy:
https://etherscan.io/address/0xD8d8aE4A5363edb6C3E01759576Da04bcc3a947e#code

**Comment by GalloDaSballo** [comment]
Review:
Please review @shuklaayush @sajanrajdev @tabshaikh and lmk if it looks good (code is not tampered, security profile is same)

And I'll proceed with minting and scripting

**Comment by shuklaayush** [comment]
Deployed code is same as the repo. Lg

**Comment by GalloDaSballo** [comment]
Prod Wireup:
NOTE: Controller is Restitution Controller: 0x3F61344BA56df00dad9bBcA05d98CA2AeC43Ba0B
The controller is currently under @sajanrajdev control, will wait for him to renounce before finishing the minting of shares

**Comment by GalloDaSballo** [comment]
TODO:
[] Controller Governance Ownership
[] Mint
[] Give Governance to Multi

**Comment by GalloDaSballo** [comment]
Blocker:
Controller accepting Strategy and Vault
Send governance of Controller to DevMultisig

**Comment by GalloDaSballo** [comment]
Blocker:
Send governance of Controller to DevMultisig

TODO:
[] Mint
[] Give Governance to Multi

**Comment by GalloDaSballo** [comment]
Controller governance was set to multisig

**Comment by GalloDaSballo** [comment]
Finalized:
Minted 2k Shares
Sent shares to Msig
Sent governance to Msig (vault and strat)

Transaction sent: 0xaf9dbb15c3d9f6da67e23e9dcab5ef676bae2025007a3056fcfcfcc5e38a0461
  Gas price: 167.431870271 gwei   Gas limit: 112420   Nonce: 159
  RemBadger.mintExtra confirmed   Block: 14050261   Gas used: 101087 (89.92%)

Transaction sent: 0xa6bbeb1e76c60c8d5d1813b07c2892ffaed8ff644eebe585674156daed5ee2e1
  Gas price: 164.926418314 gwei   Gas limit: 89015   Nonce: 160
  RemBadger.transfer confirmed   Block: 14050283   Gas used: 75351 (84.65%)

Transaction sent: 0x26d45621a8d64f84649ff899e20068e77d7d7f38e37d6413ebb2432c993dc2b1
  Gas price: 164.336441285 gwei   Gas limit: 37721   Nonce: 161
  RemBadger.setGovernance confirmed   Block: 14050285   Gas used: 34242 (90.78%)

Transaction sent: 0xcfb3c40ace9c0464f13caf1b5b619567d75f1deab2c53ec970faac76190a12b6
  Gas price: 164.166580987 gwei   Gas limit: 37779   Nonce: 162
  BrikedStrategy.setGovernance confirmed   Block: 14050286   Gas used: 34294 (90.78%)

Last step is for Governance to seed and airdrop

**Comment by sajanrajdev** [comment]
Added to the registry under ops_deployer2: https://etherscan.io/tx/0x0bae0ccda349e08661c29c3307e667455d34043b8b5b0291fe47a84b97293558

**Comment by GalloDaSballo** [comment]
Code is deployed, minted and has been seeded.
Last step is to Airdrop

Deployed Release:
https://github.com/GalloDaSballo/remBadger/releases/tag/1.0

Closing issue until further changes necessary
