### ISSUE TITLE
[MAINNET] ConvexStaking - CVX/ETH, cvxCRV / CRV

### ISSUE THREAD

**Issue by GalloDaSballo** [Badger-Finance/badger-strategies#34]
# Strategy Review

2 new  "standard" convex vaults
1. CVX/ETH
2. CRV/ETH

Similar to the stablecoin strats
Use CRVLP and stakes in Convex
Rewards are emitted as bveCVX and bcvxCRV
Difference: 10% perf fee, keep .1% withdrawal

1 new locked CVX vault
Need a vault that will take bveCVX as the want asset.  We will then need to vote on votium for the pool with the highest bribe each round.  Those funds will be used to buy CVX and converted to bveCVX (through buying or minting).  10% of the bveCVX should be directed to emit to bveCVX holders (perf fee) and the rest deposited into [bribe]veCVX (need a better name) and distributed to [bribe]veCVX holders.  This can be done through the tree or autocompounded into the vault.  there will not be a liquidity pool for this so it is ok for ppfs to increase.

## Dev
@sajanrajdev 

### Code Link 
Commit / Hash / Repo should be known from this.

## Due Diligence Document  (Link, but could also just be a .md file in repo)
This document evaluates the protocols that are interacted with as strategy positions.

## Review By
* Ongoing: 
* Completed:

## Review by Security Board
* Not started / ongoing / completed

**Comment by sajanrajdev** [comment]
Implementations for the CVX/ETH and CRV/cvxCRV Curve Lps srats are ready for review: https://github.com/Badger-Finance/strategy-convex-staking-optimizer/pull/22

@shuklaayush @GalloDaSballo @tabshaikh, please review when you get a chance.

**Comment by GalloDaSballo** [comment]
Code was great, but DAO decided not to continue, closing
