### ISSUE TITLE
remDIGG - Empty DIGG denominated Vault with 1 time minting and BrikedStrategy

### ISSUE THREAD

**Issue by GalloDaSballo** [Badger-Finance/badger-strategies#35]
# Strategy Review
https://snapshot.org/#/badgerdao.eth/proposal/0x8c814efa246058e85cc0166663c26918a4e5eca90308f9b77a4d8b97d54d9570

### Description
Fork of remBADGER
One Time mint of 52.94 DIGG (9 decimals)

### Code Link 
https://github.com/GalloDaSballo/remDIGG/tree/1.0

## Review By
* Ongoing: 
* Completed:

## Review by Security Board
Doesn't apply (no strategy)

## TODO
[] Deploy and Verify
[] Mint and send to devMulti
[] Wireup for Prod
[] Setup restitutionController
[] Aidrop

**Comment by GalloDaSballo** [comment]
@shuklaayush @tabshaikh @sajanrajdev @jorijnsmit Please review and lmk what you think, changes are minimal and test is just one

**Comment by GalloDaSballo** [comment]
TODO Fix: Change the name of contracts to remDIGG

**Comment by GalloDaSballo** [comment]
Updated Code:
https://github.com/GalloDaSballo/remDIGG/tree/rfc.1

**Comment by sajanrajdev** [comment]
Fork of remBADGER with nothing but the contract name and version changed.

Confirmed the want token to be DIGG.

Lifecycle test adjusted to reflect the actual amount of shares to be minted and the amount of DIGG to be seeded. The rest of the tests remained the same and all tests are passing:
![image](https://user-images.githubusercontent.com/25463788/151818339-65427d13-cf65-4a77-a3db-658327f05759.png)

**Comment by shuklaayush** [comment]
Lg. Not much to review. Might want to change the first letter in name/ticker to lowercase for consistency
![image](https://user-images.githubusercontent.com/27727946/151841074-3f4f4325-bdcb-42a2-a14f-247a7b9c06ac.png)
![image](https://user-images.githubusercontent.com/27727946/151841092-b334f696-435d-49cf-813b-951eebdef633.png)

**Comment by GalloDaSballo** [comment]
Update:

> Lg. Not much to review. Might want to change the first letter in name/ticker to lowercase for consistency ![image](https://user-images.githubusercontent.com/27727946/151841074-3f4f4325-bdcb-42a2-a14f-247a7b9c06ac.png) ![image](https://user-images.githubusercontent.com/27727946/151841092-b334f696-435d-49cf-813b-951eebdef633.png)

Fixed casing:
https://github.com/GalloDaSballo/remDIGG/tree/rfc.2

**Comment by tabshaikh** [comment]
LGTM

**Comment by jorijnsmit** [comment]
looks good based on diffs, only thing that changed is label changes.

concerns i had for boosting in regards to remdigg not rebasing vs digg rebasing can be solved outside of the contract.

✅

**Comment by GalloDaSballo** [comment]
TODO:
[] Deploy and Verify
[] Mint and send to devMulti
[] Wireup for Prod
[] Setup restitutionController
[] Aidrop

**Comment by GalloDaSballo** [comment]
Will mint and send later, see Scripts to simulate operations:
1) Setup with `restitutionController`
https://github.com/GalloDaSballo/remDIGG/blob/main/scripts/1_production_deploy.py
2) Setup of fees, mint and renounce to governance
https://github.com/GalloDaSballo/remDIGG/blob/main/scripts/rem_badger_mint_and_renounce.py

@sajanrajdev @shuklaayush @tabshaikh Pls lmk what you think and I'll run it tomorrow!

**Comment by GalloDaSballo** [comment]
Deploy:
RemDIGG Logic: https://etherscan.io/address/0x776a1f1107f8f805cae0440d51b22ac33af3ee61#code

**Comment by GalloDaSballo** [comment]
@sajanrajdev @shuklaayush @tabshaikh You can just run
https://github.com/GalloDaSballo/remDIGG/blob/main/scripts/rem_badger_mint_and_renounce.py

And verify it will:
- Mint
- Set fees to 0
- Send minted tokens to devMulti
- Set ownership to devMulti
To confirm script works

**Comment by shuklaayush** [comment]
Lgtm. Script does what it's supposed to do
![image](https://user-images.githubusercontent.com/27727946/151983772-a4bccaf7-547c-4d7c-b589-4898f97d71b6.png)

**Comment by sajanrajdev** [comment]
@GalloDaSballo @shuklaayush @tabshaikh, the controller wire-up script is ready for review: https://github.com/Badger-Finance/badger-multisig/pull/73

**Comment by tabshaikh** [comment]
LGTM

**Comment by GalloDaSballo** [comment]
Update: 
Changing script to use 18 decimals as the math was done that way

**Comment by GalloDaSballo** [comment]
Ran updated Script:
https://github.com/GalloDaSballo/remDIGG/blob/1.1/scripts/3_production_setup.py

The script is the same but uses 18 decimals instead of 9, also fixes the exact amount to mint

Result:
Transaction sent: 0x65a84dd48101048d9db1af9d947a24b2021ad144e415ebc1ceaf062b179e225c
  Gas price: 117.647512363 gwei   Gas limit: 112499   Nonce: 179
  RemDIGG.mintExtra confirmed   Block: 14127147   Gas used: 101158 (89.92%)

Transaction sent: 0x4f25a71d7670846ac3749de5b854dca769bc45085ef2fba4f6b7f3da6e40ce30
  Gas price: 104.607748678 gwei   Gas limit: 89581   Nonce: 180
  RemDIGG.transfer confirmed   Block: 14127157   Gas used: 75858 (84.68%)

Transaction sent: 0x91c352b69082fe6c63b4c42ef776fe74fb8337046f8c77e2892cc1be0c32b7a3
  Gas price: 105.058473175 gwei   Gas limit: 37836   Nonce: 181
  RemDIGG.setGovernance confirmed   Block: 14127160   Gas used: 34345 (90.77%)

**Comment by GalloDaSballo** [comment]
Added to Registry:
https://etherscan.io/tx/0xa22dc2609791c2999b45c41e55761bdbd2a7a137bfc9e1de82b3edd688a3dc91

**Comment by sajanrajdev** [comment]
Confirmed script was adjusted to mint 52.9420355 with 18 decimals.

- Shares were mint and transferred to the devMulti
- Governance was delegated to the devMulti

**Comment by sajanrajdev** [comment]
Confirmed proxyAdmins for both remDIGG and the bricked strategy to be the devProxyAdmin (Timelock):
![image](https://user-images.githubusercontent.com/25463788/152185624-c5185893-3708-4145-ab2e-c62cfe193afb.png)

**Comment by GalloDaSballo** [comment]
Basically done, closing, re-open if we need further edits or checks
