### ISSUE TITLE
MAINNET - UST-Wormhole Curve LP

### ISSUE THREAD

**Issue by sajanrajdev** [Badger-Finance/badger-strategies#36]
# Strategy Review

### Description
![image](https://user-images.githubusercontent.com/25463788/153303145-d97f4ad1-779a-4326-bcda-493fc1510500.png)

A new StrategyConvexStakingOptimizer vault is required for the [UST-Wormhole Curve LP](https://curve.fi/factory/53/deposit). On Convex:
![image](https://user-images.githubusercontent.com/25463788/153303060-f3a6f7c7-8e30-469d-9463-995c1ddc1d00.png)

### Code Link 
The config setup and tests adaptation can be found on the following PR: https://github.com/Badger-Finance/strategy-convex-staking-optimizer/pull/25

## Review By
* Ongoing: 
- [x] @GalloDaSballo 
- [x] @tabshaikh 
- [x] @shuklaayush 
- [ ] @dapp-whisperer 

* Completed:

## Review by Security Board
* Ongoing

## Test Checks (screen shot of all test passing)
![image](https://user-images.githubusercontent.com/25463788/153303328-f6b04d87-fb4e-444b-ae1b-3fef0ff76a7d.png)

**Comment by GalloDaSballo** [comment]
LGTM

**Comment by GalloDaSballo** [comment]
Abandoned / w/e
