### ISSUE TITLE
[FTM] SEX/wFTM LP Solidex Helper Strategy

### ISSUE THREAD

**Issue by sajanrajdev** [Badger-Finance/badger-strategies#38]
# Strategy Review

### Description
Strategy that takes Solidly's SEX/wFTM LP as want and deposits it on Solidex for SEX and SOLID yield. 
- Autocompunds all SEX
- Converts al SOLID into SOLID/SOLIDsex LP and deposits on Badger's helper for this token [[See issue](https://github.com/Badger-Finance/badger-strategies/issues/39)]. Distributes this helper through the badgerTree.

### Code Link 
WIP: https://github.com/sajanrajdev/strategy-solidex-helpers/blob/main/contracts/StrategySolidexSexWftmHelper.sol

## Review By
* Ongoing: 
* Completed:

## Review by Security Board
* Not started / ongoing / completed

**Comment by GalloDaSballo** [comment]
Tests are passing, code LG

**Comment by sajanrajdev** [comment]
Logic deployed: https://ftmscan.com/address/0x50040a781198763c8d653bdc2188777972f93cd0#code

**Comment by sajanrajdev** [comment]
Vault deployed: https://ftmscan.com/address/0x7cc6049a125388b51c530e51727a87ae101f6417#readProxyContract

**Comment by sajanrajdev** [comment]
Strat deployed: https://ftmscan.com/address/0x99f4db590ee266011631985589AEde1EBbDDc137

**Comment by sajanrajdev** [comment]
setVault: https://ftmscan.com/tx/0xf07063026e8818d8cb204ebb755ae420687c472b4d0023ef76b0e1d3c87705b6
approveStrategy: https://ftmscan.com/tx/0x00af0957404fa1844134d83cff062d849c8226ee278f7b91677617ba33b85845
setStrategy: https://ftmscan.com/tx/0x7fdca01caa1a86dd96e10a496ac7ef4369f319377024dedfb5de2a1941c791f6

**Comment by sajanrajdev** [comment]
Vault added to the registry: https://ftmscan.com/tx/0x43c8f3cc993a3af8de7453b958ce20e9f47cc52fa486753192a0f0d57ce540ce

**Comment by GalloDaSballo** [comment]
Closing to aggregate
