### ISSUE TITLE
Review: POLYGON wBTC-USDC-Quick-Polygon-Strategy

### ISSUE THREAD

**Issue by sajanrajdev** [Badger-Finance/badger-strategies#4]
### Strategy Review

- [Spec](https://github.com/GalloDaSballo/wbtc-usdc-Badger-Strategy#quickswap-wbtc-usdc-liquidity-pool-yield-farming-polygon-mainnet)
- [Code](https://github.com/GalloDaSballo/wbtc-usdc-Badger-Strategy/blob/main/contracts/MyStrategy.sol)

**Comment by GalloDaSballo** [comment]
Tests are not passing

Something seems broken, haven't figured out what

**Comment by GalloDaSballo** [comment]
Will review PR 3 by Saj

**Comment by GalloDaSballo** [comment]
https://github.com/GalloDaSballo/wbtc-usdc-Badger-Strategy/pull/3

**Comment by GalloDaSballo** [comment]
Merged into main

Release: https://github.com/GalloDaSballo/wbtc-usdc-Badger-Strategy/tree/p0.1

Tests are passing:
<img width="810" alt="Screenshot 2021-08-06 at 16 41 18" src="https://user-images.githubusercontent.com/13383782/128527676-573c6111-ac9f-43a1-a726-bf44e2851c85.png">

Verified Liquidity, 7MLN for QUICK USDC and 7MLN for QUICK WETH

Strat receives USDC-WBTC QUICK LP and auto compounds QUICK rewards

LGTM

Only thing that may require babysitting is `sl`

**Comment by sajanrajdev** [comment]
Deployment and Production tests update:

Controller: 0x12097e9755aBf710166D0027c1a2ef7609833D74
Registry: 0x22765948A3d5048F3644b81792e4E1aA7ea3da4a

wBTC/USDC Quickswap:

Strategy: 0x809990849D53a5109e0cb9C446137793B9f6f1Eb
Sett: 0x6B2d4c4bb50274c5D4986Ff678cC971c0260E967
Want: 0xF6a637525402643B0654a54bEAd2Cb9A83C8B498

Status: Wired up and unpaused

Added to registry under Author: 0xeE8b29AA52dD5fF2559da2C50b1887ADee257556

**Comment by sajanrajdev** [comment]
Test assets deposited and operating functions tested and working in production:
- sett.earn(): https://polygonscan.com/tx/0xd0bd2665afcc53036f85c8a6c51405317ecd741359c3639ad1630b67c134fe18
- strategy.harvest(): https://polygonscan.com/tx/0x252d2ec0824b6eabcae0c5242c766abdb66a2abb940a45a8dc35d9051d0fc985
- strategy.tend(): https://polygonscan.com/tx/0x8e9bc479c42002bef83d47c114f9e449c8d5a8f1ffe7a86607957c5b0016175b

**Comment by axejintao** [comment]
@GalloDaSballo should we close this?
