### ISSUE TITLE
[FTM] Helper Vaults Thread

### ISSUE THREAD

**Issue by GalloDaSballo** [Badger-Finance/badger-strategies#40]
# Strategy Review

### Description
Helper vaults for FTM launch, auto-compouding into more want

- SOLID/SOLIDsex LP Solidex Helper Strategy
https://github.com/Badger-Finance/badger-strategies/issues/39

- SEX/wFTM LP Solidex Helper Strategy
- https://github.com/Badger-Finance/badger-strategies/issues/38

- oxDAO/usdc - HELPER
-

- renbtc/btc - HELPER
- https://github.com/GalloDaSballo/strategy-solidex-weve-usdc/tree/rfc.0

- Weve/USDC - Helper
- https://github.com/sajanrajdev/strategy-solidex-weve-usdc

### Code Link 
Commit / Hash / Repo should be known from this.

## Due Diligence Document  (Link, but could also just be a .md file in repo)
This document evaluates the protocols that are interacted with as strategy positions.

## Review By
* Ongoing: 
* Completed:

## Review by Security Board
* Not started / ongoing / completed

**Comment by shuklaayush** [comment]
Overall, both lgtm. Tests are passing after making [some fixes](https://github.com/sajanrajdev/strategy-solidex-helpers/pull/1)

Small nit:
- Not sure if we're expecting solidsex to maintain peg but if we do, then it might make sense to add a slippage check here:
https://github.com/sajanrajdev/strategy-solidex-helpers/blob/main/contracts/StrategySolidexSexWftmHelper.sol#L219-L223

**Comment by Tritium-VLK** [comment]
15% performance fees

**Comment by GalloDaSballo** [comment]
https://github.com/GalloDaSballo/strategy-solidex-weve-usdc/tree/rfc.0

Tests are passing
<img width="792" alt="Screenshot 2022-03-03 at 01 15 01" src="https://user-images.githubusercontent.com/13383782/156471497-7c7a01ed-98f5-455e-a7d4-d42eb7fbbf93.png">


They verify profitability (100% auto-compound)

Harvest could get rekt, which applies to all Helper Vaults (see: [Peer Review](https://docs.google.com/document/d/1YX_Arux6_1M2P39k5kxOm0ZmidF4K8JtV1uAhyy5kNU/edit))

To avoid rekt we may create a onChain price check to get the exchange that gives back then best price

Also we could further generalize the strat to use tokenA and tokenB after being given the LP token from Solidly, making all Helper Strats have the same logic @shuklaayush @sajanrajdev What do you think?

**Comment by GalloDaSballo** [comment]
In line with the goal of generalizing the helper vaults to have one template that handles slippage checks, here the first trial deployment for renBTC/wBTC Solidex Strat

**Comment by GalloDaSballo** [comment]
Controller Proxy:
0x72ac086a5d7e1221a6d47438c45ed199e9bff423

Vault Proxy:
0xb6d63a4e5ca740e96c26adabcac73be78ee39dc5

Strategy logic:
0x2b7f219d0f574d1bb7893bdddb67e40f4aa8d10d

Strategy Proxy:
0x711555f2b421da9a86a18dc163d04699310fe297

**Comment by GalloDaSballo** [comment]
Earn:
>>> v.depositAll({"from": a[0]})
Transaction sent: 0x8e2fc52db3038d10e1172043ccf0be46762f62fbb82a79c700d5c55ea5153c5e
  Gas price: 344.7226 gwei   Gas limit: 256242   Nonce: 16
  SettV4.depositAll confirmed   Block: 32466919   Gas used: 202370 (78.98%)

<Transaction '0x8e2fc52db3038d10e1172043ccf0be46762f62fbb82a79c700d5c55ea5153c5e'>
>>> v.earn({"from": a[0]})
Transaction sent: 0x34a20b322922ddb70468274f1248237423fcd014a385328ba0238ae1d7c175b2
  Gas price: 406.9026 gwei   Gas limit: 895195   Nonce: 17
  SettV4.earn confirmed   Block: 32466939   Gas used: 694375 (77.57%)

**Comment by GalloDaSballo** [comment]
Code is here:
https://github.com/GalloDaSballo/strategy-ftm-solidex-renbtc-wbtc-helper-templatized/tree/rc.0

@sajanrajdev @shuklaayush @dapp-whisperer 
Please break it and if you can't I'll deploy the rest of the vaults tomorrow

**Comment by sajanrajdev** [comment]
Already deployed, wired-up and added to registry:
```
SEX/wFTM LP:
Want: 0xFCEC86aF8774d69e2e4412B8De3f4aBf1f671ecC
Vault: 0x7cc6049a125388B51c530e51727A87aE101f6417
Strategy: 0x99f4db590ee266011631985589AEde1EBbDDc137

SOLID/SOLIDsex LP:
Want: 0x62E2819Dd417F3b430B6fa5Fd34a49A377A02ac8
Vault: 0xC7cBF5a24caBA375C09cc824481F5508c644dF28
Strategy: 0x7AfB2E386b7990507009f81B3c486c8C596501a4

WEVE/USDC LP:
Want: 0xD9A4108CBB40a12dE16dFFDc54aE5065878816d7
Vault: 0xd9770deC6fdA576450e66f0c441B6b8755F7184A
Strategy: 0xd6479e4477a41EadB0fc0DAB31a992efc7EFdAcd

OXD/USDC LP:
Want: 0xEaFB5Ae6eEa34954eE5e5a27B068B8705CE926a6
Vault: 0x3BA15548226aA045aD6fe9DC9Bec1f0891532D60
Strategy: 0xe850B254461Ba7D6148C07ABF9f171fb9e03BB00
```

**Comment by sajanrajdev** [comment]
wBTC/renBTC wiring up to helper controller:
strat.setController: https://ftmscan.com/tx/0x85673b477d9b1b15428c9f9c9e014e17a629c7b9908103eddab51f83455084cf
vault.setController: https://ftmscan.com/tx/0x041d3b18f9b4a00334994dc92ef30594afa520f160a381ff6fc632a36a77fb10
approveStrategy: https://ftmscan.com/tx/0x4ea25144747b52941c5d80ed525fa95d7d54223a5bf135807cc17ca49e40d277
setStrategy: https://ftmscan.com/tx/0xbbd11316de2f6ce0ebcd8f8dd41060c8dec891a8b8eaf6a89f8f21b113e356f0
setVault: https://ftmscan.com/tx/0xc468c01d332df5b8e029ff56b25efc2ed87a0947bcc288f9a11f7d96fa6569fc

**Comment by sajanrajdev** [comment]
Guestlists set as follows:
```
Solidex Helpers Guestlists params:

SEX/wFTM LP:
Guestlist: 0x1003DE64B024Ee9d6d1Bed367348BB34B2aAc3F6
User Cap: 13338362989420668691568
Total Cap: 400150889682620060747057

SOLID/SOLIDsex LP:
Guestlist: 0x0eC330A6f4e93204B9AA62a4e7A0C78D7849821E
User Cap: 20807635287287570583634
Total Cap: 624229058618627117509040

WEVE/USDC LP:
Guestlist: 0xa47883569D0DE5c985bf4C08Cc0A9bCB4B48016c
User Cap: 167215102148477195
Total Cap: 5016453064454315859

OXD/USDC LP:
Guestlist: 0x347dFC2FcC5d769923947e900d4C8621C99511D7
User Cap: 3426885564247159
Total Cap: 102806566927414772

wBTC/renBTC LP:
Guestlist: 0x50Dd8A61Bdd11Cf5539DAA83Bc8E0F581eD8110a
User Cap: 122411824
Total Cap: 3672354730
```

**Comment by sajanrajdev** [comment]
Contract delegation for March 7th, 2022 launch:

Controller: https://ftmscan.com/tx/0xb82aba047b3104da10920d07980d07cdca829430bfc4f7b4b6229a1b2731b436

WeVe/USDC:
Vault: https://ftmscan.com/tx/0xbfce73c3cbe1bab9a1f9324941177047af112f3bde1b6f7ec3ecc8a4a6c016c1
Strategy: https://ftmscan.com/tx/0xdaec509c128e80c9598bd7b95161efbc3aa6d1f8100cf38fa12eb9f613bd7e71

renBTC/wBTC:
Vault: https://ftmscan.com/tx/0x702c30b0fb1a6b9c9db9ba0d03c1cc73a1a607b10c4cf572bdb5e86da155217b
Strategy: https://ftmscan.com/tx/0x244d3d817c059fdc18ad788760dc1dd8536918af6c7d2d98de3948d04518beca

**Comment by sajanrajdev** [comment]
Change performance fees to 6.9%:

SEX/wFTM to 6.9%: https://ftmscan.com/tx/0x88aaee5bd414f932525218e4d5226a5cd23e52fdd0794cd8d485ddc62b37da99
SOLID/SOLIDsex to 6.9%: https://ftmscan.com/tx/0xeaeef524acbf6365c7f08bb75e8233c46e628bbec1462ce695a54b6c3503174e

renBTC/wBTC and WeVe/USDC done atomically: https://ftmscan.com/tx/0x702efd4434a1aef6fd0d52876881a334acd4da67ed443fc68a6bc05bef551cd9

**Comment by sajanrajdev** [comment]
Delegation of remaining Helpers:

SEX/wFTM:
Vault: https://ftmscan.com/tx/0x08f42109773a1fafa649cd14536c500abc276234209ee59f2154684029bc3fb0
Strat: https://ftmscan.com/tx/0x942df65eab48a77fe496d12efe53eb208c0cf5d3b0edf2cfb3c9dcc360aa89d0

SOLID/SOLIDsex:
Vault: https://ftmscan.com/tx/0x712ef00f367ebe7d5cf19d46478365e151dd72c9e7c99dc818dcc8a8e0004803

**Comment by sajanrajdev** [comment]
**NOTE**; A mistake was made when delegating governance of the SOLID/SOLIDsex Strategy and it was delegated to its own address by accident. This effectively removes governance from the strategy. As per discussion with @GalloDaSballo, it was decided to leave it as it is for the time being since governance should not be required moving forward. In case that it is, we will upgrade the strategy to patch this variable when time comes.

A function was added to the logic to patch the governance address to the correct one and an upgrade test script was written for this. These changes can be found on the following PR: https://github.com/sajanrajdev/strategy-solidex-helpers/pull/2. This can be used as needed when the time comes.

**Comment by GalloDaSballo** [comment]
Helpers Made it, closing
