### ISSUE TITLE
[FTM] Ecosystem Emitting Vaults

### ISSUE THREAD

**Issue by GalloDaSballo** [Badger-Finance/badger-strategies#41]
# Strategy Review

### Description
Solidex Staking Start, emitting Helper Vaults

1. Crv/wftm
2. Usdc/MIM
3. BOO/xBOO
4. Scream/wftm
5. TOMB/wFTM
6. wFTM/renbtc 

## Due Diligence Document  (Link, but could also just be a .md file in repo)
This document evaluates the protocols that are interacted with as strategy positions.

## Review By
* Ongoing: 
* Completed:

## Review by Security Board
* Not started / ongoing / completed

**Comment by Tritium-VLK** [comment]
15% performance fees

**Comment by shuklaayush** [comment]
I did a generic version for non-autocompounding 100% helper emitting vaults

https://github.com/shuklaayush/strategy-solidex-staker/blob/v0.1.0/contracts/StrategySolidexStaker.sol

![image](https://user-images.githubusercontent.com/27727946/156587230-93e4a928-0d7a-47b2-9ca6-6199a4fe57a6.png)

**Comment by GalloDaSballo** [comment]
Code receive want, stakes with Solidex

Takes Solid -> SolidSex and LPs and emits Helper Vault
Takes Sex -> wFTM and LPs and emits Helper Vault

Paths are logical and one swap each

**Comment by GalloDaSballo** [comment]
![Uploading Screenshot 2022-03-04 at 16.46.46.png…]()
All tests are passing

LGTM, let's go!!

**Comment by shuklaayush** [comment]
Controller: 0x16c7D5F373a61bb3c93E5f46E1B6987Cf1223524

crv/wftm (0xED7Fd242ce91a541ABcaE52f3d617dacA7fe6e34)
Vault: [0x60c5A975Bd0511e45D4C9Ae5592c8CA412BE2310](https://ftmscan.com/address/0x60c5A975Bd0511e45D4C9Ae5592c8CA412BE2310)
Strategy: [0xF2DeF12E2559D75Ec8FC3aAa3EFe91a8ccd8B00e](https://ftmscan.com/address/0xF2DeF12E2559D75Ec8FC3aAa3EFe91a8ccd8B00e)

usdc/mim (0xbcab7d083Cf6a01e0DdA9ed7F8a02b47d125e682)
Vault: [0x561f4dBaFA71ad05694C7ea1b894b9D99f684281](https://ftmscan.com/address/0x561f4dBaFA71ad05694C7ea1b894b9D99f684281)
Strategy: [0x2B6F3533edfd42812Ea3F9E02cC18B99a23BE731](https://ftmscan.com/address/0x2B6F3533edfd42812Ea3F9E02cC18B99a23BE731)

boo/xboo (0x5804F6C40f44cF7593F73cf3aa16F7037213A623)
Vault: [0xFce6e3115D84c94df98BD286C1C67279dc021361](https://ftmscan.com/address/0xFce6e3115D84c94df98BD286C1C67279dc021361)
Strategy: [0x2B6F3533edfd42812Ea3F9E02cC18B99a23BE731](https://ftmscan.com/address/0x2B6F3533edfd42812Ea3F9E02cC18B99a23BE731)

scream/wftm (0x86dD79265814756713e631Dde7E162bdD538b7B1)
Vault: [0x77e803F7d0B6d85731F68CfE1f1CA4c48de105F4](https://ftmscan.com/address/0x77e803F7d0B6d85731F68CfE1f1CA4c48de105F4)
Strategy: [0x2B6F3533edfd42812Ea3F9E02cC18B99a23BE731](https://ftmscan.com/address/0x2B6F3533edfd42812Ea3F9E02cC18B99a23BE731)

tomb/wftm (0x60a861Cd30778678E3d613db96139440Bd333143)
Vault: [0x3f96f8cA67AcDE9041AD62125C5a4D062b07872c](https://ftmscan.com/address/0x3f96f8cA67AcDE9041AD62125C5a4D062b07872c)
Strategy: [0x7EC44d9143c4A38908E5be4f7c6331f5805715D2](https://ftmscan.com/address/0x7EC44d9143c4A38908E5be4f7c6331f5805715D2)

wftm/renbtc (0x4A81E80f7d77B4D1440A7Fef12bD47e0344F215B)
Vault: [0x609A51e13fd0896c0c02f0B642756533b29f36Ab](https://ftmscan.com/address/0x609A51e13fd0896c0c02f0B642756533b29f36Ab)
Strategy: [0xdD2f894375CdC8E4E574F0ccB9B65D617CEafee5](https://ftmscan.com/address/0xdD2f894375CdC8E4E574F0ccB9B65D617CEafee5)

**Comment by sajanrajdev** [comment]
Approve Contract Access called on SEX and SOLID helpers for all the strategies above.
SEX/wFTM:
![image](https://user-images.githubusercontent.com/25463788/156833027-2f097d18-4a62-4a31-a2a5-44cbeb82bd46.png)

SOLID/SOLIDsex:
![image](https://user-images.githubusercontent.com/25463788/156833075-cc2d164a-9a26-4e23-8aac-a709ae8c5e60.png)

**Comment by shuklaayush** [comment]
Earns:
https://ftmscan.com/tx/0x1b5f3acae8a4c00249711152596ffb56730a39636f79c3145282fa56ca94378f
https://ftmscan.com/tx/0xae224b75c3eae9af5888760f59f79e438034f7595407fd568b33f60501e11c07
https://ftmscan.com/tx/0xb6356167a81146504134f7049786054c3144efdf453aba53acf09693fb19df3b
https://ftmscan.com/tx/0xefcd7cb6db385e6787fb98d7ab6da9c460a2e8abeb461b49c63bbea123d0753e
https://ftmscan.com/tx/0x55fb0f9b361019a4abc4a17086f6ceaf92a3247444361d7e1535ccadb993c2ef
https://ftmscan.com/tx/0x6edf9096ae763130f1fa1ea49bd7ca7106b5614382c9f34ad843055dce8a4a41

Harvests:
https://ftmscan.com/tx/0x238b9eeafc93fed9a9bc888e60163231035b8dfd42c415bf4ac26ba335883f2c
https://ftmscan.com/tx/0xab22188238737c19971081788d1af2196ba91ae3c98219b61b0fad92dbd0e4be
https://ftmscan.com/tx/0xd64f00527b83eaca466f7e47093d13f840ef68b6e9ab0eed5779e3fc477bc797
https://ftmscan.com/tx/0xdd789bc8251dcd7728af68702fab208e950bc057820f3800af5cb17c6be8636c
https://ftmscan.com/tx/0xed5887fb90b1e9e30632ec475a2c80943323d3c0d919aeea12f2e3d923f28a5e
https://ftmscan.com/tx/0x01808e0a6067907bbaf2d7177a594c51b4af61936ac4534f17802efc9a1b09b4

**Comment by shuklaayush** [comment]
Updated governance performance fees to 960bps on all starts:
https://ftmscan.com/tx/0x44f1809ef4565f6e6ea517a967c8a9d536b7db406d61ae08e1ea91a2c4266f9c
https://ftmscan.com/tx/0x3704a79fefa70000a69a21b874a3af24d54f2bebb4d0f982e6c08c59bc2ecef2
https://ftmscan.com/tx/0xb5dd0fd29982c9d30ad565adb6172a883b68cf6193dfabfb12dbd676aa588d0d
https://ftmscan.com/tx/0xc086d4a37bf25f1ea340c1f21bad14204f77078a6294d36acc57ba5ac74c527d
https://ftmscan.com/tx/0x7bf2733415758a505e0223987afc725bbf3fa126823a4282c1e67c101716d628
https://ftmscan.com/tx/0x404759d7f0d83b6ae5262c4c47ca89e0b64fd9d75cfc0f68048086de2daf6cc0

**Comment by shuklaayush** [comment]
Delegated governance to `0x4c56ee3295042f8A5dfC83e770a21c707CB46f5b`
https://ftmscan.com/tx/0xfcc0c33c4bff5ae5021edad60b5646e3323e24c56642d829231a25bda538ef43
https://ftmscan.com/tx/0x42b700a3ec019ce73a8f7920f94922621cc7e173ef8f9075a8cddc2025c2d421
https://ftmscan.com/tx/0xb639a0fc1f27bd1d272c48d6e1a7b8cb53c5b615b4f1641833a048bc0cc02226
https://ftmscan.com/tx/0x3cc8bfac8724e6d9a3d6678bb447d4e9450b0d3c64e96cbe2bdb58759893fd9d
https://ftmscan.com/tx/0x90ac173e90e5e320340adaae3d2ea9f3ee6492e31893457907563de949cdb331
https://ftmscan.com/tx/0x1a6339b3dba449531e1fd58f8cad0aee8928f601773a6be90c5899222d09e944
https://ftmscan.com/tx/0xdcf50a83de7dea0255cdcf8b27efbcd2bd45bf80aa1d2530f72094effdd576d8
https://ftmscan.com/tx/0x48f2a86f1fa2fa66c691c73ba9b9c0b6a5386eb3cd07f52ecad43492c8982635
https://ftmscan.com/tx/0xdbdd6563ea9294ef3014514977b9a942dd27065f63b8d4f7e6195b929f287c14
https://ftmscan.com/tx/0xba1f5a8b80c9696f4ad335b97e4f1c87c97179e117c718848195167a20494cff
https://ftmscan.com/tx/0xd1d4a68eb72883c4bbc75ec4e022313c1ae27f27ad8b793770bbccfcd2a6afd0
https://ftmscan.com/tx/0x5efd7f7a01a2bbda426dc0b3d09f8cbd9b2eacaac5f939f7d319b25841c53265
https://ftmscan.com/tx/0x10686283607f5d2a00d55e61e9ce18b13fdefb87c8912109d5fa5ec440e0ea6e

**Comment by GalloDaSballo** [comment]
Also Peer Reviewed by Watchpug:
https://www.hacknote.co/17c261f7d8fWbdml/17fd5e8b96fnNMiP
