### ISSUE TITLE
[FTM] DCA Emitting Vaults 

### ISSUE THREAD

**Issue by GalloDaSballo** [Badger-Finance/badger-strategies#42]
# Strategy Review

### Description
Solidex Staking Strats, emitting wBTC/renBTC Helper Vaults

- Usdc/MIM
- Deployed, Earned, Harvested, with secure "old" logic

- wFTM/renbtc 
- Deployed and verified with new logic

- Crv/wftm
- Deployed and verified with new logic
https://github.com/Badger-Finance/badger-strategies/issues/42#issuecomment-1059366178

### Code Link 
https://github.com/GalloDaSballo/strategy-ftm-solidex-DCA-templatized/tree/rc.0

## Due Diligence Document  (Link, but could also just be a .md file in repo)
Solidex DD

## Deployed Contract (If present)
See below

## Review By
* Ongoing: 
* Completed:

**Comment by GalloDaSballo** [comment]
Initial Code with all Tests Passing:
https://github.com/GalloDaSballo/strategy-ftm-solidex-DCA-templatized/tree/rfc.0
<img width="913" alt="Screenshot 2022-03-04 at 00 49 36" src="https://user-images.githubusercontent.com/13383782/156672479-697afc2d-8e34-41c3-820a-557c9a1ee313.png">

Probably overkill on the 10 protected tokens, but I think the code is basically done

@shuklaayush @sajanrajdev What do you think?

**Comment by GalloDaSballo** [comment]
Deployment:
Controller
https://ftmscan.com/tx/0x36214fc0cda294c021ecf92e9894c6c189c3f77d47eb7dcab10ffa257692ba81

Vault
https://ftmscan.com/tx/0xeaeeca3e47fb6a90d21953001caab768c689c1a2943025acbb5447f53d622611

Strategy Logic:
https://ftmscan.com/tx/0x08ad97625b74e6c4f2c44740ee41c6fad3c8098748b6bff5c0a3db702f0d8307

Strategy Proxy:
https://ftmscan.com/tx/0x9663832be3276f300d25f0eb624fdf698445c01f0ae3c66082b92430ef552508

**Comment by GalloDaSballo** [comment]
Update:
Earn
https://ftmscan.com/tx/0x89d130575a187514766d87771e9e205ab82decf46f6a703aa8a009da0b88f566

**Comment by GalloDaSballo** [comment]
Harvest:
https://ftmscan.com/tx/0x3c5f3ba001080bf032e350484a49b56665a31de1c549ec2bb01eca3d424173c9

**Comment by GalloDaSballo** [comment]
Removed token0 and token1, deploying the other 2 vaults with DCA Controller: `0x85386c3ce0679b035a9f8f17f531c076d0b35954`

**Comment by GalloDaSballo** [comment]
Test
WANT = "0x4A81E80f7d77B4D1440A7Fef12bD47e0344F215B" ## "wFTM/renBTC"
TARGET_VAULT = "0xb6d63a4e5ca740e96c26adabcac73be78ee39dc5" ## b wBTC / renBTC Helper
NOTE: Commented out the try/catch due to bug

<img width="931" alt="Screenshot 2022-03-04 at 17 48 00" src="https://user-images.githubusercontent.com/13383782/156804620-ce455c5f-0d84-4b5c-b7f4-77c251c77635.png">


Deployment:
Vault Proxy: 0x9a28eeFB2c5F8311f37c39314D78Be85C54B5da6
Strategy Logic: 0xbaBF5401a6c255aF3Ae83fF806191C404eef8D9B
Strategy Proxy was deployed at:  0xE143aA25Eec81B4Fc952b38b6Bca8D2395481377

```
>>> wire_up_test_controller(controller, vault, strategy, dev)
Transaction sent: 0x52b82fb1eebf16d484924dbe3bba96bd524ed083cc28fc60ed610afc41ae718c
  Gas price: 340.8466 gwei   Gas limit: 51719   Nonce: 45
  Controller.approveStrategy confirmed   Block: 32547560   Gas used: 47206 (91.27%)

Transaction sent: 0x336a64bc4561c4634eb05a05863ccd68c9f22914bd2bc86dd5fa92270ceb215f
  Gas price: 401.5626 gwei   Gas limit: 53853   Nonce: 46
  Controller.setStrategy confirmed   Block: 32547567   Gas used: 49137 (91.24%)

Transaction sent: 0xcc014f803875a0a13fcb8b1e0b55bc18ee47a6ae71b71faec1eb2b959f45d2e1
  Gas price: 401.4355 gwei   Gas limit: 52705   Nonce: 47
  Controller.setVault confirmed   Block: 32547573   Gas used: 48098 (91.26%)
```

**Comment by GalloDaSballo** [comment]
Test
WANT = "0xED7Fd242ce91a541ABcaE52f3d617dacA7fe6e34" ## "wFTM/CRV"
TARGET_VAULT = "0xb6d63a4e5ca740e96c26adabcac73be78ee39dc5" ## b wBTC / renBTC Helper
WHALE = "0x97b90a72631fcb579fdcd2274085d181d5a11c54"

<img width="897" alt="Screenshot 2022-03-04 at 18 03 27" src="https://user-images.githubusercontent.com/13383782/156807493-7fd0d7fe-b997-428f-b1fe-7efec93f4dc7.png">
All tests passing (commented try catch as always)


Vault Proxy was deployed at:  0x4145a9B8B7bdC76F14e65c26f9c71e23B9069b25
Strategy Proxy was deployed at:  0x8bfc9dF1228D73BcaE1B553D0e472d5D4447D971

```
Transaction sent: 0x794850ffeb357f4ef76ba73260143897ebd436c693becd446ea969d5e569574d
  Gas price: 335.4661 gwei   Gas limit: 51719   Nonce: 51
  Controller.approveStrategy confirmed   Block: 32548176   Gas used: 47206 (91.27%)

Transaction sent: 0x8a833c8b858b55ab6d307d927855ad03c6e6ceaef50ba817acd82d2a2f2f043b
  Gas price: 336.3124 gwei   Gas limit: 53853   Nonce: 52
  Controller.setStrategy confirmed   Block: 32548181   Gas used: 49137 (91.24%)

Transaction sent: 0x9d8cc628d66f725d81c1e37d75e7f6163ca2befdfe4787a2ee2e7644885a757f
  Gas price: 335.4661 gwei   Gas limit: 52705   Nonce: 53
  Controller.setVault confirmed   Block: 32548189   Gas used: 48098 (91.26%)

Controller wired up!
```

**Comment by GalloDaSballo** [comment]
Address Summary:
```
Controller
0x85386c3ce0679b035a9f8f17f531c076d0b35954

wFTM/CRV
Vault:  0x4145a9B8B7bdC76F14e65c26f9c71e23B9069b25
Strategy: 0x8bfc9dF1228D73BcaE1B553D0e472d5D4447D971

USDC/MIM
Vault: 0x1aaf7f8154704d80e2380b3dbc967fd0486016e0
Strategy: 0x5631baa4c636dd5fe3dbdcd6e31c41f2385d3405

wFTM/RenBTC
Vault: 0x9a28eeFB2c5F8311f37c39314D78Be85C54B5da6
Strategy:  0xE143aA25Eec81B4Fc952b38b6Bca8D2395481377
```

**Comment by GalloDaSballo** [comment]
Added all 3 vaults to registry

**Comment by GalloDaSballo** [comment]
GuestList Math

wFTM/CRV
<img width="1359" alt="Screenshot 2022-03-04 at 18 57 14" src="https://user-images.githubusercontent.com/13383782/156816598-c11c2096-e916-4f15-9a3e-bcd3e4e7ce02.png">
11540344733619781831684155  / 46 Million = Tokens Per Million Dollars (est) * 3 (3 MLN)
0.752631177 * 10^18


USDC / MIM
<img width="1371" alt="Screenshot 2022-03-04 at 18 58 28" src="https://user-images.githubusercontent.com/13383782/156816782-c4c58daa-530b-4199-95d6-3217ca22af65.png">
1.50329575e12

**Comment by sajanrajdev** [comment]
Approved Contract Access for wFTM/renBTC and wFTm/CRV on wBTC/renBTC Sett:
https://ftmscan.com/tx/0xc78808a3ee4994d8533d5e7501db1d5e6d503270b6d89bac65a069df19cddbff
https://ftmscan.com/tx/0xd4b18d522c2211327c1949c5e81f48a48f823e45cb502b67a74495d674aed995

**Comment by GalloDaSballo** [comment]
Guestlist set:
wFTM/CRV ( See Above)
0xf9dc673d0fc82a7bd4da4705413b4c30e368adfb3c72c0fb2d76c5b56e34682d

USDC / MIM (See above)
0x310c6755aef4e66742cb66020a93117244175842445b7968840164522dac4d8a

wFTM / renBTC
0x0363ef7973c90fd30803e3d26b8224b397ff6745f0df22d941b43b41d5643845

**Comment by GalloDaSballo** [comment]
Guestlist:
Removed guestlists, will re-deploy with new settings (agreed with with Saj)

```
wFTM/renBTC LP:
Total: (136494472424048 * 3000,000)/7085.17 = 57794437857121847
User: (136494472424048 * 100,000)/7085.17 = 1926481261904061
Reference: https://ftmscan.com/tx/0xb62bf4327882ebf6d59b320e8543d70d71d7b88c33fc66dba1c6eaa8880615a1

wFTM/CRV LP:
Total: (16336963423148741372661 * 3000,000)/64165.81 = 763816279564556640335141
User: (16336963423148741372661 * 100,000)/64165.81 = 25460542652151888011171
Reference: https://ftmscan.com/tx/0x0d495470271b04833e9b73d510e9d256d7050f196108a2be8a9a4c36132687fc

USDC/MIM LP:
Total: (3549427808475280 * 3000,000)/7099.4 = 1499884979776578302
User: (3549427808475280 * 100,000)/7099.4 = 49996165992552610
Reference: https://ftmscan.com/tx/0x3bf101641f50b149aa5f765f57447a747efb01c04033b08830eb258f07e4ab0a 

```

**Comment by GalloDaSballo** [comment]
Updated GuestLists:
wFTM / renBTC:
0x0d1cf0f3351a9caa07bcec58cba2f277483a7dc3b50ccfa66b4bf6d665e5ff63

wFTM / CRV:
0x85f454a3ef3df3d1e9e7d6a58c1bcf6315f25da9f056baae0c25efd450982421

USDC/ MIM:
0xc158fa182b82fb6da2a7f8ff416d5d2a02231cb903dea2ab5b03a3f53d7233ab

**Comment by GalloDaSballo** [comment]
Bonus Deployment geist/3gCRV :
Vault was deployed at:  0x02330E37fcc7C27eB4632b3E31b951fDE5126c48
Strategy was deployed at:  0x24766758465f8d27395EBa4A8bD016cbC3C3978B

**Comment by sajanrajdev** [comment]
Controller parameters changed to the prodcution parameters:
- Keeper: 0x0680b32b52C5ca8C731490c0C576337058f39337 (keeperACL) -> https://ftmscan.com/tx/0x2ba8193621d17e234c16df63e596e33d6cd482b4c25853501bf455bc3ba8b7a0
- Strategist: 0x4c56ee3295042f8A5dfC83e770a21c707CB46f5b (devMutli) -> https://ftmscan.com/tx/0xee57c582d3fe71c1099b41d9047dce630396f9401b338934398cce13a222d450
- Rewards: 0xf109c50684EFa12d4dfBF501eD4858F25A4300B3 (treasuryOps) -> https://ftmscan.com/tx/0x4240aa050560d8d2a47981b677bc5656a308ef803976a2a61b05e6ab73bce51e

**Comment by GalloDaSballo** [comment]
Delegated governance for 3 vault + strats

wFTM/CRV
https://ftmscan.com/tx/0x51dd5a4776a8b4553344cf3b42f920e1daca94474fccae9ab48e8138aa089a67
https://ftmscan.com/tx/0xb8bae1b7b314b2505966d7c946cbac36331ac3994847d85988eb7de822c6ab1e

USDC/MIM
https://ftmscan.com/tx/0x57f6361d3282e1a9c9c873ba41148c9b0d35230253a03b625dc90643ad7522c5
https://ftmscan.com/tx/0xd66d5fd46028a4c04ba14712d684bb59ac46d388a61aacefe367d82fc358141f

wFTM/RenBTC
https://ftmscan.com/tx/0xabac4d2a39b383815c7a6855e5d80c5349994d1ef0b1a6adc3e36f03b9b8c2ff
https://ftmscan.com/tx/0xfb3ef13bc6e2417393e06cbf075b1368f9d51ccf8e58987998f718174fb5e106

**Comment by sajanrajdev** [comment]
- Guestlist set on GEITS/g3CRV vault: https://ftmscan.com/tx/0x336f051f10006749e5975b323a293efdfea86cb7842ba3f869ddfff94ec66d08
- Perf fees were set to 9.6% on GESIT/g3CRV strat: https://ftmscan.com/tx/0xcd8ec918f0a3430134c0b0388ca48daca4fe1b943547ad71f59b96b1d49e9de7

- GESIT/g3CRV strat and vault were delegated;
vault: https://ftmscan.com/tx/0x54ba3ce180be55677f912b4ca54e696278068dd5795d7984625c0868375b43bd
strat: https://ftmscan.com/tx/0xce4786583cc9e4cb9898e564d186c50b576dcd2d7a92199e985e42dbb347c6b4

**Comment by GalloDaSballo** [comment]
Also Peer Reviewed by WatchPug with no dangerous findings
https://www.hacknote.co/17c261f7d8fWbdml/17fd5e8b96fnNMiP
