### ISSUE TITLE
[FTM] OxDAO oxSolid staker

### ISSUE THREAD

**Issue by shuklaayush** [Badger-Finance/badger-strategies#43]
# Strategy Review

### Description
Stake oxSolid in multirewards contract
Harvest rewards:
- oxd --> deposit in bvlOxd
- oxSolid --> auto-compounded
- solid, wftm etc. --> converted to oxsolid and autocompounded

### Code Link 
https://github.com/shuklaayush/oxsolid-staker/tree/v0.1.2

## Due Diligence Document
WIP

## Review By
* Ongoing: 
* Completed:

## Test Checks (screen shot of all test passing)
![image](https://user-images.githubusercontent.com/27727946/157879058-62ada7b9-a4a8-42bc-ae0c-e530a05e8de9.png)

**Comment by GalloDaSballo** [comment]
Code ultimately just stakes and claims

I think using the seller everywhere would have made the code simpler.
But ultimately is fine as is
<img width="818" alt="Screenshot 2022-03-22 at 16 34 12" src="https://user-images.githubusercontent.com/13383782/159519758-78301d36-3256-4792-987a-6240399203a0.png">

Tests are passing, got a random revert on permissions, when debugging it showed that the tx was working.

I'd say go ahead and deploy

**Comment by sajanrajdev** [comment]
Strategy:
- Stakes oxSOLID on rewards contract
- Autocompounds SOLID and oxSOLID 
- Deposits OXD on bveOXD and distributes it

As discussed with @shuklaayush, the `claimRewardsOnWithdrawAll` will be left but it will be used only for those cases where harvest is broken and migration is required. The preferable migration path is to run a harvest + withdrawAll atomically. Claiming the rewards upon withdrawAll will leave these rewards stuck on the strat as they are protected. 

tl'dr, I recommend to set `claimRewardsOnWithdrawAll` in default to `False` and only toggle it if harvests are broken.

All tests are passing:
![image](https://user-images.githubusercontent.com/25463788/159967266-87170c76-e5f3-4dc2-918f-83c8c71eef8a.png)

**Comment by sajanrajdev** [comment]
Adapted strat to emit bbveOXD/OXD instead of bveOXD. Also introduced a method to dynamically identify the amount of bveOXD and OXD requried for liquidity provision in order to reduce dust: https://github.com/shuklaayush/oxsolid-staker/pull/2

**Comment by sajanrajdev** [comment]
Adapted if/else statement for OXD processing to better identify whether to swap or deposit for bveOXD.

Release: https://github.com/sajanrajdev/oxsolid-staker/releases/tag/v0.0.2-Emit-Helper

All tests are passing: 
![image](https://user-images.githubusercontent.com/25463788/161816737-a123338d-080f-4b5d-8330-75c3091edf97.png)
![image](https://user-images.githubusercontent.com/25463788/161816777-087e89a9-4e59-4c49-a90b-72196e761664.png)

**Comment by sajanrajdev** [comment]
Successfully tested migration on fork:
```
>>> vault = TheVault.at("0xa8bD8655A0dCABE76913D821Ab437562276b3B59", owner=dev)
>>> vault.balance()
600741488426593533298
>>> strat = OxSolidStakerStrategy.at(vault.strategy(), owner=dev)
>>> strat.setClaimRewardsOnWithdrawAll(False)
Transaction sent: 0xe0baa83e3a060e16e36409826725cb1b173a4fa014965e63a7c76cd2a985c289
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 299
  OxSolidStakerStrategy.setClaimRewardsOnWithdrawAll confirmed   Block: 35315557   Gas used: 43323 (0.36%)

<Transaction '0xe0baa83e3a060e16e36409826725cb1b173a4fa014965e63a7c76cd2a985c289'>
>>> strat.harvest()
Transaction sent: 0xda2eba6009e5e6fb2fb020d1b3032f6fd6e56c0cae7e1b87c65259dac355d8b8
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 300
  OxSolidStakerStrategy.harvest confirmed   Block: 35315558   Gas used: 1574071 (13.12%)

<Transaction '0xda2eba6009e5e6fb2fb020d1b3032f6fd6e56c0cae7e1b87c65259dac355d8b8'>
>>> vault.balance()
602210635550722039479
>>> vault.withdrawToVault()
Transaction sent: 0x0037ff6e671b14690aae3a107c5df4ccbcc176725b985ef47d2970214f104612
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 301
  TheVault.withdrawToVault confirmed   Block: 35315559   Gas used: 277536 (2.31%)

<Transaction '0x0037ff6e671b14690aae3a107c5df4ccbcc176725b985ef47d2970214f104612'>
>>> want = interface.ERC20(vault.token())
>>> want.balanceOf(vault)
602210635550722039479
>>> new_strat = OxSolidStakerStrategy.at("0x865B283149eC945BE9A44ADBcf680c26c3E530f3", owner=dev)
Fetching source of 0x46DE3569fA1CD34a0001b4cAC8f146699DF325f8 from api.ftmscan.com...
>>> vault.setStrategy(new_strat)
Transaction sent: 0xad3cb033e93dc98b6bf380e36bd1159f59df747f6464dac4ccfb6fe283870a09
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 302
  TheVault.setStrategy confirmed   Block: 35315560   Gas used: 50282 (0.42%)

<Transaction '0xad3cb033e93dc98b6bf380e36bd1159f59df747f6464dac4ccfb6fe283870a09'>
>>> vault.strategy()
'0x865B283149eC945BE9A44ADBcf680c26c3E530f3'
>>> vault.earn()
Transaction sent: 0x6bbba09fa0a65378cb3c384ea640a41d6814f74ae6413e255de22d154f3cc2f9
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 303
  TheVault.earn confirmed   Block: 35315561   Gas used: 393145 (3.28%)

<Transaction '0x6bbba09fa0a65378cb3c384ea640a41d6814f74ae6413e255de22d154f3cc2f9'>
>>> vault.balance()
602210635550722039479
>>> want.balanceOf(vault)
30110531777536101974
>>> new_strat.harvest()
Transaction sent: 0x6d709cea2e519b76b68a635dd287154c249b2350677d9dbc0ff662a66b1bbbe2
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 304
  OxSolidStakerStrategy.harvest confirmed   Block: 35315562   Gas used: 1592422 (13.27%)

<Transaction '0x6d709cea2e519b76b68a635dd287154c249b2350677d9dbc0ff662a66b1bbbe2'>
```

**Comment by sajanrajdev** [comment]
Migration process: 
old_strat.setClaimRewardsOnWithdrawAll(False): https://ftmscan.com/tx/0x44f9eccc5275d11e294d62cc181d9a740cf25eb91ece881a7a5384912dad6cc3
old_strat.harvest(): https://ftmscan.com/tx/0xedf31bdeb4a7732e62252073ff26833111b920a75a4e4a140b3981cfe5a7aa82
vault.withdrawToVault(): https://ftmscan.com/tx/0xdbd0ae45bc368d1cc085db9154eb122720f0137d7cfe879edfbe385e099d064d
vault.setStrategy(): https://ftmscan.com/tx/0x9165629317c7dacde9681611729a1c5a0f50c18b65a87c1d0da5b1fc694163ce
vault.earn(): https://ftmscan.com/tx/0xb188f09e86c3a87c0a418137af9df3474df8ad03d9a773f377eabc7b42389c38

**Comment by sajanrajdev** [comment]
Harvest on new bOxSOLID strat: https://ftmscan.com/tx/0xfe4634dbbd713d7387c982ea03b557c06de5bf3f0f07d3fa1589cbb86d714e33

LGTM

**Comment by GalloDaSballo** [comment]
Logic LG, harvest LG
GuestList Setup

Let's renounce ownership and ship

**Comment by GalloDaSballo** [comment]
Logic LG, harvest LG
GuestList Setup

Let's renounce ownership and ship

**Comment by sajanrajdev** [comment]
Contract delegation: https://ftmscan.com/tx/0x25d913970b89c12f1fe0b3c25a4bf6d809806af68d6caa92aa765f7b45c78f40

**Comment by shuklaayush** [comment]
Lgtm. Tests passing
Just not convinced with the `OXD --> bBveOxd_Oxd` math. Refer: https://github.com/Badger-Finance/badger-strategies/issues/48#issuecomment-1090549511
