### ISSUE TITLE
[FTM] OxDAO oxd locker

### ISSUE THREAD

**Issue by shuklaayush** [Badger-Finance/badger-strategies#44]
# Strategy Review

### Description
Lock oxd in OxDAO locker

Harvest rewards:
- oxSolid --> deposit in bOxSolid

### Code Link 
https://github.com/shuklaayush/vested-oxd/tree/v0.1.1

## Due Diligence Document
WIP

## Review By
* Ongoing: 
* Completed:

## Test Checks (screen shot of all test passing)
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/27727946/157924597-4401ec84-c5c9-4f39-8e13-db8ea5a895a0.png">

**Comment by GalloDaSballo** [comment]
![Uploading Screenshot 2022-03-22 at 16.38.23.png…]()
Tests are passing

**Comment by sajanrajdev** [comment]
Implementation mirrors the CVX locker core functions.

Locks OXD into OxDAO locker for voting. Receives OxSOLID rewards that are distributed in the form of bOxSOLID through harvest. Charges performance fees on bOxSOLID.

The default voting delegate is set to TechOps.

On-chain voting and bribes claiming mechanics are yet to be implemented.

Tests:
- Migration test was adapted to include the prepareWithdrawAll call - LGTM
- Delegation test - LGTM
- Lifecycle tests set earn amount to be properly earned and locked - LGTM
- Locking test tests that no more than withdrawals are blocked during locked period. Also tests that when locks expired and the strat rebalanced with 0 re-locking, the user can Withdraw All. - LGTM
- All new manual functions' permissions are tested - LGTM

Testing notices:
- There is no test for the `reinvest()` function
- Non of the setter functions are tested nor their permissions (Except for `setProcessLocksOnRebalance`).

Would recommend to remove all the un-used commented out functions for cleanliness.

All tests are passing: 
![image](https://user-images.githubusercontent.com/25463788/159541384-54df6d6e-88c5-47d3-93d2-e8f5f427ee8e.png)

**Comment by shuklaayush** [comment]
Update:

- Removed unused code
- Modified harvest to autocompound everything

Diff: https://github.com/shuklaayush/vested-oxd/compare/v0.0.2...v0.0.3

**Comment by GalloDaSballo** [comment]
Changes LG, hardcoded path for auto-compounding is most liquid and while a generalized solution would be cool, this is acceptable at this time

All tests are passing
<img width="1189" alt="Screenshot 2022-03-23 at 16 16 53" src="https://user-images.githubusercontent.com/13383782/159733102-14cdbe1d-824f-49b1-a201-f705ce378b1d.png">


Sent this PR for syntax: https://github.com/shuklaayush/vested-oxd/pull/1

If PR is merged, i'd say go ahead and deploy

**Comment by GalloDaSballo** [comment]
@shuklaayush @sajanrajdev Hardcoded Voter
https://github.com/GalloDaSballo/ftm-oxd-hardcoded-voter

Will need us to setup a LP pool for the locker

Deploy Locker -> Use that address to setup LP Pool
Use that in the hardcoded voter POOL variable
Deploy rest

This allows to automatically vote for the pool

**Comment by shuklaayush** [comment]
Updated do re-lock autocompounded tokens at the end of the harvest
https://github.com/shuklaayush/vested-oxd/compare/v0.0.3...v0.1.1

**Comment by shuklaayush** [comment]
Harvest tx
https://ftmscan.com/tx/0xb8565a18ee522e1c2ea97847e6ee589f33a281e26eb6b4471516ab3690b15c0c

**Comment by GalloDaSballo** [comment]
Code LG

Check Hardcoded Voter:
https://github.com/GalloDaSballo/ftm-oxd-hardcoded-voter/tree/rc.0
<img width="1152" alt="Screenshot 2022-03-24 at 18 25 38" src="https://user-images.githubusercontent.com/13383782/159974875-d2875b61-1c0c-4871-b7f5-3a752e9003b2.png">

Can deploy and then we just need:
[] delegate to voter
[] give governance to multisig

**Comment by GalloDaSballo** [comment]
Deployment:

HardcodedVoter Deployed at: 0xDC4fbbc2f2E78BFDb94391103f6532C00648B069

NOTE: Anyone can vote (useful to refresh on OXD)
Only governance (multisig) can undo the vote

**Comment by shuklaayush** [comment]
Voter LGTM. Pretty straightforward - votes 100% for the hardocoded pool (bveOxd/oxd volatile pool)

**Comment by shuklaayush** [comment]
Delegated strategy vote to hardcoded voter
https://ftmscan.com/tx/0x30127ed8c0707d1d85c62374ffbe4ad12ce0194290f53a641d549327293a6bfb

**Comment by GalloDaSballo** [comment]
Voter:

Vote has been cast:
https://ftmscan.com/tx/0x8c79a9faff73f1889ba6e7d1250c24062f9f856b2a82b1f3d7ae27904e8e8b72

Voting properly happened on the VotingSnapshot
<img width="495" alt="Screenshot 2022-03-24 at 19 10 49" src="https://user-images.githubusercontent.com/13383782/159982539-292059ef-2944-4c4a-b189-110f39a46fff.png">

**Comment by GalloDaSballo** [comment]
Checked Variables and LG now. Will go out of guarded launch shortly. Closing ticket
