### ISSUE TITLE
[FTM] bveOXD-OXD LP Helper

### ISSUE THREAD

**Issue by sajanrajdev** [Badger-Finance/badger-strategies#48]
# Strategy Review

### Description
Strategy that takes Solidly's bveOXD-OXD Volatile LP as want and stakes it on OxDAO for yield. It autocompounds all OXD into more want and compounds all SOLID/oxSOLID into the bOxSOLID helper and distributes this.

### Code Link 
Repo: https://github.com/sajanrajdev/bveOXD-OXD-Staking-Optimizer

NOTE: Rewards haven't kicked in so harvest tests fail for the moment.

## Review By
* Ongoing: 

- [ ] @GalloDaSballo 
- [ ] @shuklaayush 

* Completed:

## Review by Security Board
* Not started

## Test Checks (screen shot of all test passing)
All tests passing:
![image](https://user-images.githubusercontent.com/25463788/161104451-f90a4348-08ba-461e-9570-9cc7f9651119.png)

Ran harvest flow tests separately:
![image](https://user-images.githubusercontent.com/25463788/161104510-cfc5d88e-4724-4d52-b474-48f5ab282041.png)

Ran permission tests separately:
![image](https://user-images.githubusercontent.com/25463788/161104561-625fc7d9-731e-4488-a298-616094851d91.png)

**Comment by GalloDaSballo** [comment]
Tests are passing, strategy will:
- Deposit and Stake into UserProxy
- Claim Rewards, sell what's necessary to LP OXD /bveOXD
- Emit bOXSolid

No particular risk beside OXD Smart Contract and slippage of LP (mitigated by harvesting often and monitoring pool)

**Comment by GalloDaSballo** [comment]
<img width="672" alt="Screenshot 2022-03-31 at 19 45 54" src="https://user-images.githubusercontent.com/13383782/161117744-225bf60b-97e1-468e-bd33-fbede284c69f.png">

In automated testing I do get a random revert. Using `--interactive` and re-runnign the withdrawal works.

Afaik there are no slippage checks on the userProxy so am blaming this to ganache.

However we will want to check this on deployed code and worst case upgrade

**Comment by GalloDaSballo** [comment]
@sajanrajdev I believe this repo is basically an instance of #45 
Please clarify / consolidate so we can group all code reviews

**Comment by sajanrajdev** [comment]
@GalloDaSballo, this is very similar to https://github.com/Badger-Finance/badger-strategies/issues/45, the difference is that this strategy autocompounds the bveOXD/OXD (It is a helper) and the other one emits it in the form of this helper instead. The other strategy is the LP staker, USDC/DEI for instance, emits bOxSolid and bbveOXD/OXD.

**Comment by sajanrajdev** [comment]
Successfully tested migration on fork:
```
>>> vault = TheVault.at("0xbF2F3a9ba42A00CA5B18842D8eB1954120e4a2A9", owner=dev)
>>> vault.balance()
4188739622206065469729
>>> want = interface.ERC20(vault.token())
>>> want.balanceOf(vault)
2423528937980509041
>>> vault.withdrawToVault()
Transaction sent: 0x7e4dc576daf74e09eda012c06ad7c1085a0eec346fbc33fb19f60bb75f400b6f
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 291
  TheVault.withdrawToVault confirmed   Block: 35310279   Gas used: 984493 (8.20%)

<Transaction '0x7e4dc576daf74e09eda012c06ad7c1085a0eec346fbc33fb19f60bb75f400b6f'>
>>> want.balanceOf(vault)
4188739622206065469729
>>> vault.strategy()
'0xE95ce50Da1Ad4f14FB34ca964E4f019d9C898A9D'
>>> strat = StrategybveOxdOxdStakingOptimizer.at("0x00B154A7fBF57a09DeeC960f152205d5aE9795AE", owner=dev)
Fetching source of 0x5DB2e4ABb7436AC75faD347f47d6506869226f5D from api.ftmscan.com...
>>> vault.setStrategy(strat.address)
Transaction sent: 0xf2dcd4ef821766e631b8d73da5076958f287d8ce9078e5d81c7ef2609464b491
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 292
  TheVault.setStrategy confirmed   Block: 35310280   Gas used: 57549 (0.48%)

<Transaction '0xf2dcd4ef821766e631b8d73da5076958f287d8ce9078e5d81c7ef2609464b491'>
>>> vault.strategy()
'0x00B154A7fBF57a09DeeC960f152205d5aE9795AE'
>>> vault.earn()
Transaction sent: 0x6c962877f23274255aada537b9e68cf165477bed6635f0cfd91441ecb9890d03
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 293
  TheVault.earn confirmed   Block: 35310281   Gas used: 1656566 (13.80%)

<Transaction '0x6c962877f23274255aada537b9e68cf165477bed6635f0cfd91441ecb9890d03'>
>>> want.balanceOf(vault)
209436981110303273487
>>> vault.balance()
4188739622206065469729
>>> strat.harvest()
Transaction sent: 0xc179f9049261febe1336a97abba3a2c435420030139b820baff3933a76df420d
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 294
  StrategybveOxdOxdStakingOptimizer.harvest confirmed   Block: 35310282   Gas used: 1999141 (16.66%)

<Transaction '0xc179f9049261febe1336a97abba3a2c435420030139b820baff3933a76df420d'>
```

**Comment by sajanrajdev** [comment]
Migration process:
old_strat.harvest: https://ftmscan.com/tx/0x68edd4eed78a473979f5b3197c25a2f2ba389ba35eeabd53fcd607d9a302fab6
vault.withdrawToVault(): https://ftmscan.com/tx/0x502588c58b8fbee1dea29c3f819d14935dddd6d6b65c717c99b6358215657333
vault.setStrategy(): https://ftmscan.com/tx/0x41068e983e0f1a7f30461861e3c852bc578348d2c0de981127b1801f6789e06d
vault.earn(): https://ftmscan.com/tx/0x0e698d2ba9300dda110b504d8db4ba85e45f7f74534e41c0372c7c3be5a60d3d

**Comment by sajanrajdev** [comment]
Harvest on new strat: https://ftmscan.com/tx/0x8706c2d6605e280d738aa14f74cfb2ea06c049108d7326d38555bb46a6ab293a

**Comment by GalloDaSballo** [comment]
Reviewed Code, LGTM, ready to go IMO

I'd say renounce ownership and let's release tomorrow in guarded

**Comment by GalloDaSballo** [comment]
Would love @shuklaayush review

**Comment by sajanrajdev** [comment]
Governance delegation: https://ftmscan.com/tx/0xad2744ce0eb48107326deb7443c1424f913690186f8c08e6dc239c848461a53e

**Comment by shuklaayush** [comment]
Tests passing. Looks good. Some minor comments
- Small nit. This line could be removed
https://github.com/sajanrajdev/bveOXD-OXD-Staking-Optimizer/blob/513e8e4b025645fa8a26c48f896e82adc0f3abea/contracts/bveOxdOxdStakingOptimizer.sol#L213
- Something to be careful about is that this doesn't claim rewards during `withdrawAll` so need to harvest before migrating strategies
- Not sure about this math. I tried to come up with a more formal solution (https://hackmd.io/@shuklaayush/BJXApfj7q) since this mIght be useful for future strats <img width="667" alt="image" src="https://user-images.githubusercontent.com/27727946/162033372-49da1b85-549a-4098-90b6-5b0707abd206.png">
Shouldn't be a big deal though since this will just lead to some extra dust
