### ISSUE TITLE
[Pre-Launch-Checklist] FTM OXSOLID and bveOXD/OXD Staker

### ISSUE THREAD

**Issue by GalloDaSballo** [Badger-Finance/badger-strategies#49]
# Strategy Review

### Description
Stake LP into OXD

OXSOLID -> Buy / Lock Based on Ratio
bveOXD/OXD -> Buy / Lock and LP based on Ratio

### Code Link 
#43 
#45 

## Due Diligence Document  (Link, but could also just be a .md file in repo)
DD from peer review of OXD code

## Review By
* Ongoing: 
[] @GalloDaSballo 
[] @sajanrajdev  (DEV)
[] @shuklaayush 

* Completed:

## Review by Security Board
Additional Peer Review TBD

**Comment by sajanrajdev** [comment]
Guestlists were set as follows:
```
bOxSolid
Contract: 0xAB73Ec65a1Ef5a2e5b56D5d6F36Bee4B2A1D3FFb
User Cap: (1000000000000000000*100,000)/0.944632 = 105861330126440772703020
Total Cap:(1000000000000000000*3000,000)/0.944632 = 3175839903793223181090625
Reference: https://www.coingecko.com/en/coins/oxsolid
tx: https://ftmscan.com/tx/0x8b3efaa6d162c27ab32210e2fac0eaeb0f16f62818120fd87578ad11a5c3839b

bbveOXD/OXD
Contract: 0xCce0D2d1Eb2310F7e67e128bcFE3CE870A3D3a3d
User Cap: (6000000000000000000*100,000)/(12*1.94) = 25773195876288659793814
Total Cap: (6000000000000000000*3000,000)/(12*1.94) = 773195876288659793814432
Reference: https://ftmscan.com/tx/0x9e1600e02f39ca6fa26bbd85164ba807b0076ad64c310b66772a5e1526112329
tx: https://ftmscan.com/tx/0xb6f9842a613da2845b5e395d5ce01696ac614c16a6d4cf219f53ea109af5aec8
```

**Comment by sajanrajdev** [comment]
Earns:
- bOxSOLID: https://ftmscan.com/tx/0x964e9ee5268d8c86af55a9f52e0969b3e5f1be52b8623aab9887d019c5ba774c
- bbveOXD/OXD: https://ftmscan.com/tx/0xec318a5f50d67694b2dbc3c2074fc2034f3a0ba1c3edd832cbffba6e6204453f

**Comment by sajanrajdev** [comment]
Harvests:
https://ftmscan.com/tx/0xf2d5f4c9a41f1e0aebc58e8927f1697ed6032024d39f9e0177a23d35787997f9
https://ftmscan.com/tx/0x95be02b683d2c523ad54f2ddd0de600c7794e8b7f9bab44dbe0ac59d528b7cbc

**Comment by sajanrajdev** [comment]
Releases:
- bOxSOLID: https://github.com/sajanrajdev/oxsolid-staker/releases/tag/v0.0.1-Emit-Helper
- bbveOXD/OXD: https://github.com/sajanrajdev/bveOXD-OXD-Staking-Optimizer/releases/tag/v0.0.2

**Comment by GalloDaSballo** [comment]
Discussion back to specific issues
