### ISSUE TITLE
renBtc USDP + Convex Review

### ISSUE THREAD

**Issue by dapp-whisperer** [Badger-Finance/badger-strategies#5]
[](https://github.com/Badger-Finance/badger-system/pull/192)

**Comment by GalloDaSballo** [comment]
Isn't this strat dead because of CVX?

**Comment by GalloDaSballo** [comment]
USDP Just raised Stabiltiy Fee to 10% I wil close this issue next week as I believe this strat is dead

**Comment by GalloDaSballo** [comment]
Closing as I don't think this will fly
