### ISSUE TITLE
[ETH]: Convex CRV Optimizer

### ISSUE THREAD

**Issue by axejintao** [Badger-Finance/badger-strategies#50]
# Strategy Review

### Description

Stake in Convex cvxCRV rewards contract to earn.

Earned Tokens
- 3crv (withdraw for usdc, sell to crv)
- crv (convert to or buy cvxcrv for want)
- cvx (buy bvecvx - not possible to deposit atm)

Harvest Tokens
- bcvxCRV (want)
- bveCVX

### Code Link 

https://github.com/axejintao/vaults-mix/tree/convex-crv-optimizer

## Due Diligence Document  (Link, but could also just be a .md file in repo)

Existing strategy upgrade.

## Review By
* Ongoing: 

- [ ] @sajanrajdev 
- [ ] @GalloDaSballo 
- [ ] @shuklaayush 

* Completed:

## Review by Security Board

* **Not started** / ongoing / completed

## Test Checks (screen shot of all test passing)

https://github.com/axejintao/vaults-mix/tree/convex-crv-optimizer

**Comment by GalloDaSballo** [comment]
Abandoned, in lack of champion, closing
