### ISSUE TITLE
[URGENT] Slippage Tollerant onChain Pricer for VotiumBribesProcessor

### ISSUE THREAD

**Issue by GalloDaSballo** [Badger-Finance/badger-strategies#54]
# Code Review
https://github.com/GalloDaSballo/fair-selling/blob/main/contracts/OnChainPricingMainnetLenient.sol

## Description
Lenient pricer with up to 5% slippage to allow Multi faster operations

## Review By
* Ongoing: 
* Completed:

## Review by Security Board
* Not started / ongoing / completed

**Comment by jorijnsmit** [comment]
diff with old contract: https://www.diffchecker.com/PfyqIcWg

adds a 2% slippage to the onchainprice, adjustable by techops between 0% and 5%.

this makes sense because there is always time between locally running order, and execing tx which carries that order. time in which market moves. also cowswap includes a gas fee in their quote, which onchainpricer does not.

lgtm

**Comment by sajanrajdev** [comment]
New version of the OnChainPricingMainnet with a slippage tolerance to the best quote defaulted at 2%. This can be modified by TechOps at anytime with hardcap of 5%. Compared logics, other features of the contract remain the same in contrast to original optimal pricer.

LGTM

**Comment by GalloDaSballo** [comment]
Deployed at: 
https://etherscan.io/address/0xbab7f98d62479309219b2cc5026d4ad1c6c05674

**Comment by GalloDaSballo** [comment]
Multisig operation: https://gnosis-safe.io/app/eth:0xB65cef03b9B89f99517643226d76e286ee999e77/transactions/multisig_0xB65cef03b9B89f99517643226d76e286ee999e77_0xa9dfd6872da9a2f5ee9e65117300fe87a0609e36b0ace5c600fbaf19865aa261

**Comment by GalloDaSballo** [comment]
Target as expected (Processor)

Signature is valid
<img width="248" alt="Screenshot 2022-05-12 at 19 46 21" src="https://user-images.githubusercontent.com/13383782/168136958-36d8b229-e8d8-4087-8bc4-86d64ea82fa5.png">


Address param is the new one (deployed above)

LGTM

**Comment by GalloDaSballo** [comment]
Live
