### ISSUE TITLE
[bveCVX] Handle upcomming FXS emissions

### ISSUE THREAD

**Issue by Tritium-VLK** [Badger-Finance/badger-strategies#56]
vlCVX will start emitting FXS in the upcoming weeks via the locker contract.  It is unclear when this will start, but there will not be notice.

<img width="1088" alt="image" src="https://user-images.githubusercontent.com/11885129/169396331-9e0134b3-af53-45dd-8037-ec138dce0cab.png">

FXS tokens will be emitted alongside cvxcrv from the locker contract.   Upon consulting the Badger Council, it was loosely decided that for now, these tokens should be auto-compounded: https://discord.com/channels/743271185751474307/976487477089034301/976584180236451920

**New Emitted Token**: FXS(0x3432B6A60D23Ca0dFCa7761B7ab56459D9C964D0)
**Handling**: Sell for bveCVX and emit taking Perf fee (currently 0%)
**Trade Path**: FXS has liquidity on but can be traded to CVX via ETH on curve.  There is also deep liquidity on Sushiswap.

**Note:** Need to figure out some way to deploy handling before FXS exists, or at best know when emissions start and trigger deployment without being informed by users.  @Tritium-VLK will also keep an eye on it.

**Comment by sajanrajdev** [comment]
@Tritium-VLK, by autocompounding you mean emitted through the tree in the form of bveCVX, correct? We shouldn't increase ppfs, would mess up the pool's peg.

**Comment by Tritium-VLK** [comment]
Correct.  I still consider that autocompounding somehow.  Note the Handling section.  Maybe we need another word for emitting yourself but not increasing ppfs.  It's tricky, because it is in effect autocompounding.

**Comment by sajanrajdev** [comment]
Ah, missed that detail from handling. Sounds good, will get to it asap. Will test by transfering FXS to strat atomically with harvest on fork while emissions start.

**Comment by Tritium-VLK** [comment]
NOte that on a bit more talk with the council and looking at BIP-87, the end goal may either be bcvxFXS compounding or selling for 75% bveCVX and 25% BADGER.  SO if you can build in the 75/25 auto-compounding now to match BIP-87 without much effort it may save a future upgrade.

**Comment by sajanrajdev** [comment]
In order to handle the cvxFXS rewards through the strat as stated on the ticket the following paths are required:

cvxFXS -> FXS: 
	- CURVE: https://curve.fi/factory-crypto/18 (39m)
FXS -> ETH:
	- UNI: https://info.uniswap.org/#/pools/0xcd8286b48936cdac20518247dbd310ab681a9fbf (1.35m)
	- CURVE: https://curve.fi/factory-crypto/3 (337k)
	- SUSHI: https://app.sushi.com/analytics/pools/0x61eb53ee427ab4e007d78a9134aacb3101a2dc23?chainId=1 (4.2m)
ETH -> CVX
	- UNI: https://info.uniswap.org/#/pools/0x2e4784446a0a06df3d1a040b03e1680ee266c35a (1.54m)
	- CURVE: https://curve.fi/cvxeth (21.8m)
	- SUSHI: https://app.sushi.com/analytics/pools/0x05767d9ef41dc40689678ffca0608878fb3de906?chainId=1 (846k)
CVX -> bveCVX
	- CURVE: https://curve.fi/factory/52 (136k)
	- Deposit on Vault
ETH -> wBTC
	- UNI: https://info.uniswap.org/#/pools/0x4585fe77225b41b697c938b018e2ac67ac5a20c0 (159m)
	- CURVE: https://curve.fi/tricrypto2 (241m)
	- SUSHI: https://app.sushi.com/analytics/pools/0xceff51756c56ceffca006cd410b03ffc46dd3a58?chainId=1 (20.2m)
wBTC -> BADGER:
	- UNI: https://info.uniswap.org/#/pools/0xe15e6583425700993bd08f51bf6e7b73cd5da91b (5.48m)
	- CURVE: https://curve.fi/factory-crypto/4 (3m)
	- Sushi: https://app.sushi.com/analytics/pools/0x110492b31c59716ac47337e616804e3e3adc0b4a?chainId=1 (1.2m)

The strategy is receiving an avarage of 40 cvxFXS per farvest (~$200) which makes the above processing not worth the gas and dev time.

Alternatively, cvxFXS could be processed as a bribe token by:

- `vestedCVX.sweepRewardToken(cvxFXS)` -> From TechOps, could be done every 2 weeks/1 month for enough cvxFXS to accumulate to make it cost efficient.
- Either:
	- Include cvxFXS on the list when processing bribes with: `bribesProcessor.sellBribeForWeth()`
	- Call `ragequit(cvxFXS)` to send it to the tree (May lead to bad UX as users will end up with dust cvxFXS to claim)
	- Call `ragequit(cvxFXS, True)` to send to governance to process into Badger/bveCVX via Cowswap/scripting (Introduces a lot of manual work + devMultisig operations).

In my opinion, the ideal path would be to handle it as a bribe along with the other tokens. This will sell it for bveCVX/BADGER in batch, process fees on it and lead to better UX. @jorijnsmit @petrovska-petro, would love to get your thoughts on this idea.

CC @Tritium-VLK

**Comment by petrovska-petro** [comment]
> 
Based on the complexity of the path for the swaps and how low apr represents the cvxfxs portion for locked cvx (at the moment 0.26%) will support the idea of triggering `sweepRewardToken(cvxFXS)` and handle on the `sellBribeForWeth` every 2 weeks together with the rest of bribes processing

**Comment by sajanrajdev** [comment]
Confirmed that the swap can be handled throw cowswap:
![image](https://user-images.githubusercontent.com/25463788/175110851-d91fd348-a290-4eaa-ab66-b0e7c9659a54.png)

This is the most cost/time efficient path that provides the best UX. Will move this issue to the multisig repo as it will require some minor modifications to the bribes processing scripts.

**Comment by jorijnsmit** [comment]
processing as a bribe seems to fall in line with trit comment here:

> NOte that on a bit more talk with the council and looking at BIP-87, the end goal may either be bcvxFXS compounding or selling for 75% bveCVX and 25% BADGER. SO if you can build in the 75/25 auto-compounding now to match BIP-87 without much effort it may save a future upgrade.

also with such low volume this sounds like the quickest and most efficient way for everybody.

**Comment by GalloDaSballo** [comment]
Closing:
Resolution -> Send to BribesProcessor and Process
