### ISSUE TITLE
[AURA] bveAURA locking vault

### ISSUE THREAD

**Issue by shuklaayush** [Badger-Finance/badger-strategies#57]
# Strategy Review

### Description

Lock AURA into vlAURA and autocompound auraBal rewards

### Code Link 
https://github.com/Badger-Finance/vested-aura/tree/1.1-rc.2

Primary changes from bveCvx:
- Vaults 1.5
- Autocompounding via balancer pools
- Delegation via locker instead of snapshot
- BribesProcessor can be set by governance

TODOs:
- [x] Replace kovan deployments with mainnet
- [x] Bribe claiming + tests
- [x] Guarded Launch
- [x] Bribeprocessor + tests
- [x] Security Contest + Open Vault

## Due Diligence Document  (Link, but could also just be a .md file in repo)
WIP

## Review By
* Ongoing: 
* Completed:

## Test Checks (screen shot of all test passing)

<img width="893" alt="image" src="https://user-images.githubusercontent.com/27727946/172651946-9f6b1c46-fbd7-418f-b39a-4a13a6ff89ef.png">

**Comment by GalloDaSballo** [comment]
Question:
<img width="730" alt="Screenshot 2022-06-09 at 00 36 27" src="https://user-images.githubusercontent.com/13383782/172728939-6c7f4c25-5076-4f71-8dea-3526a4869264.png">

Are you sure this includes the balances that can be withdrawn by this strat + locked? It's important that balanceOfPool() include all tokens (locked + unlocked but in the locker) as not doing so means the token will rebase down

**Comment by GalloDaSballo** [comment]
Update:
<img width="629" alt="Screenshot 2022-06-09 at 00 39 23" src="https://user-images.githubusercontent.com/13383782/172729249-00d67612-087b-4e6d-b65d-a50522733979.png">

Added this to `initialize` I believe the withdrawalSafetyCheck should be enabled by default

**Comment by GalloDaSballo** [comment]
Integration LG, see above for my 2 thoughts.

Tests are passing

<img width="1115" alt="Screenshot 2022-06-09 at 00 56 01" src="https://user-images.githubusercontent.com/13383782/172730949-42af3b1d-3aad-415c-b400-4628e452373c.png">


Overall GREAT work, would like to see addressed the two above

**Comment by sajanrajdev** [comment]
Review:

General:
- Vaults V1.5

MyStrategy.sol
- Utilizes rewards processor to handle accumulated rewards
- Includes the manualPRocessExpiredLocks
- Introduces bribes claiming from Hidden Hands. HH can transer ETH when claiming (but only when claiming. ETH gets wrapped and processed like any other token.
- Harvests auraBAL which autocompounds into more AURA through Balancer. Note that it re-deposits harvested Aura, hence ppfs will increase - Problematic if LPing.

Tests LGTM and all of them are passing:
![image](https://user-images.githubusercontent.com/25463788/173108148-8412d64d-15cd-4bae-971e-14482c44c394.png)

NOTE: Investingating concern with @shuklaayush around the `LOCKER.balanceOf(address(this))` only increasing starting the following epoch and, hence, the following not being accurate:
```
upkeepNeeded = balanceOfPool() > LOCKER.balanceOf(address(this)); 
```

**Comment by shuklaayush** [comment]
> NOTE: Investingating concern with @shuklaayush around the LOCKER.balanceOf(address(this)) only increasing starting the following epoch and, hence, the following not being accurate:

@sajanrajdev Changed it to this:

```solidity
function checkUpkeep(bytes calldata checkData) external view returns (bool upkeepNeeded, bytes memory performData) {
    (, uint256 unlockable, ,) = LOCKER.lockedBalances(address(this));
    upkeepNeeded = unlockable > 0;
}
```

**Comment by GalloDaSballo** [comment]
LGTM, in addition to peer reviews by core devs we are running c4 contest:
https://code4rena.com/contests/2022-06-badger-vested-aura-contest

Will require to keep in experimental / guarded until contest ends (20th of June)

**Comment by GalloDaSballo** [comment]
Mitigation of various griefs as well as gas optimizations
https://github.com/Badger-Finance/vested-aura/tree/1.1-rc.0

@dapp-whisperer @rayeaster would like your peer review

**Comment by rayeaster** [comment]
> Mitigation of various griefs as well as gas optimizations https://github.com/Badger-Finance/vested-aura/tree/1.1-rc.0
> 
> @dapp-whisperer @rayeaster would like your peer review

LGTM in general. 

BTW, does it make sense to add some events for better tracking of key setters like `manualSetDelegate()`, e.g., governance tx dashboard to show all historical change made to the strategy if desired
https://github.com/Badger-Finance/vested-aura/blob/1.1-rc.0/contracts/MyStrategy.sol#L95

**Comment by shuklaayush** [comment]
New logic: [0x0d724e8aee6f73b35a596c8c947c92c75eac7818](https://etherscan.io/address/0x0d724e8aee6f73b35a596c8c947c92c75eac7818)

**Comment by GalloDaSballo** [comment]
Bribes Processor:
https://github.com/GalloDaSballo/fair-selling/blob/v0.2-rfc.0/contracts/AuraBribesProcessor.sol

@sajanrajdev @shuklaayush @rayeaster Please do a Security Peer Review of the Above

@gosuto-inzasheru @petrovska-petro Please do a "Tech Ops" Review of the Above

**Comment by gosuto-inzasheru** [comment]
pr to change fee destination for graviaura bribes processor: https://github.com/GalloDaSballo/fair-selling/pull/18

**Comment by shuklaayush** [comment]
Can we change bveAura -> graviAura to make the naming consistent?

**Comment by shuklaayush** [comment]
Aura/graviAura metastable pool has a known vuln:
https://github.com/balancer-labs/frontend-v2/pull/2024#pullrequestreview-1030909182

**Comment by GalloDaSballo** [comment]
Updated Processor and Pricer to cover all Balancer tokens (2 cannot be swapped at this time)
https://github.com/GalloDaSballo/fair-selling/releases/tag/v0.2-rc.0

**Comment by GalloDaSballo** [comment]
Deployment:
OnChainPricingMainnetLenient (up to 5% slippage):
https://etherscan.io/address/0x81b2211a3c25e6720a44492bf989c849df509147#readContract

AURA PROCESSOR: TODO

**Comment by sajanrajdev** [comment]
## Pricer review
- Integrates slippage check to the On chain pricer (default 5% - Can be changed by TechOps)
- Integrates Balancer pricing for a predefined list of pools
- Integrates UniV3 pricing
- Tests were modified to verify these functionalities. All related tests are passing except for `tests/on_chain_pricer/test_swap_exec_on_chain.py::test_swap_in_balancer_batch` due to a timeout issue and `tests/on_chain_pricer/test_bribe_tokens_supported.py::test_are_bribes_supported` for SD and FDT as they are not supported. Nevertheless, tests covering correct UniV3 and Balancer pricing as well as single swap through these routes are passing.

LGTM

**Comment by gosuto-inzasheru** [comment]
@shuklaayush can you continue with your review on pricer so we can get moving with https://github.com/Badger-Finance/badger-multisig/issues/663 ?

**Comment by GalloDaSballo** [comment]
> ### Pricer [wip]
> * Looks like the new curve router address is [0x81C46fECa27B31F3ADC2b91eE4be9717d1cd3DD7](https://etherscan.io/address/0x81C46fECa27B31F3ADC2b91eE4be9717d1cd3DD7) (see docs [here](https://curve.readthedocs.io/registry-exchanges.html#deployment-address))
> * `getBalancerV2Pool` could be a bit cleaner if `tokenIn` and `tokenOut` are sorted before comparing
> * Shouldn't uni-v3 quotes have appropriate pool fees instead of dummy for swap to execute? (maybe not required for pricing)
> 
> ```
>  quotes[3] = Quote(SwapType.UNIV3, getUniV3Price(tokenIn, amountIn, tokenOut), dummyPools, dummyPoolFees);
> ```
@rayeaster please address / comment as to why we can keep older registry or should move to neweer

**Comment by rayeaster** [comment]
> > ### Pricer [wip]
> > 
> > * Looks like the new curve router address is [0x81C46fECa27B31F3ADC2b91eE4be9717d1cd3DD7](https://etherscan.io/address/0x81C46fECa27B31F3ADC2b91eE4be9717d1cd3DD7) (see docs [here](https://curve.readthedocs.io/registry-exchanges.html#deployment-address))
> > * `getBalancerV2Pool` could be a bit cleaner if `tokenIn` and `tokenOut` are sorted before comparing
> > * Shouldn't uni-v3 quotes have appropriate pool fees instead of dummy for swap to execute? (maybe not required for pricing)
> > 
> > ```
> >  quotes[3] = Quote(SwapType.UNIV3, getUniV3Price(tokenIn, amountIn, tokenOut), dummyPools, dummyPoolFees);
> > ```
> 
> @rayeaster please address / comment as to why we can keep older registry or should move to neweer

for deployed `pricer v0.2` we only use `get_best_rate` and it is the same btw the new address and previous one used by us
https://www.diffchecker.com/uwRDqkxx

**Comment by GalloDaSballo** [comment]
Urgently needed to change AuraBribesProcessor due to flattening process messing up strings (all hashes are wrong)

Re-deployed. Please also forknet and test via brownie console to ensure this will work:
All settings the same (Verify pls)
https://etherscan.io/address/0xc66c9f87d847ddc964724b789d3113885b08efcf


Please send LGTM: @sajanrajdev @shuklaayush @rayeaster

**Comment by sajanrajdev** [comment]
> Urgently needed to change AuraBribesProcessor due to flattening process messing up strings (all hashes are wrong)
> 
> Re-deployed. Please also forknet and test via brownie console to ensure this will work: All settings the same (Verify pls) https://etherscan.io/address/0xc66c9f87d847ddc964724b789d3113885b08efcf
> 
> Please send LGTM: @sajanrajdev @shuklaayush @rayeaster

## Deployment Review 
- Confirmed that contract logic is correct: https://etherscan.io/address/0xc66c9f87d847ddc964724b789d3113885b08efcf#code#F7#L192
- Confirmed pricer is the same as before (latest version)
- Confirmed manager is delegated to TechOps 

Deployment LGTM

**Comment by rayeaster** [comment]
> Urgently needed to change AuraBribesProcessor due to flattening process messing up strings (all hashes are wrong)
> 
> Re-deployed. Please also forknet and test via brownie console to ensure this will work: All settings the same (Verify pls) https://etherscan.io/address/0xc66c9f87d847ddc964724b789d3113885b08efcf
> 
> Please send LGTM: @sajanrajdev @shuklaayush @rayeaster

the balancer pool seems not quite liquid otherwise LGTM (constants are correct)
https://etherscan.io/address/0xc66c9f87d847ddc964724b789d3113885b08efcf#code#F1#L64
![image](https://user-images.githubusercontent.com/1487283/182191558-9a2750af-0879-4fce-b335-f6a1d0b6d68c.png)

**Comment by shuklaayush** [comment]
LGTM
@rayeaster is right in pointing out that the processor would probably just deposit into graviAura instead of swapping since the swap path is illiquid

**Comment by gosuto-inzasheru** [comment]
> LGTM @rayeaster is right in pointing out that the processor would probably just deposit into graviAura instead of swapping since the swap path is illiquid

could this be solved by making it two hopped? aura > weth > graviaura?
- weth/aura: https://app.balancer.fi/#/pool/0xcfca23ca9ca720b6e98e3eb9b6aa0ffc4a5c08b9000200000000000000000274
- aurabal/graviaura/weth: https://app.balancer.fi/#/pool/0x0578292cb20a443ba1cde459c985ce14ca2bdee5000100000000000000000269

**Comment by GalloDaSballo** [comment]
Solve by using Cowswap

**Comment by GalloDaSballo** [comment]
Bug with Pricer V2 and BribesProcessor V3

<img width="674" alt="Screenshot 2022-08-15 at 21 08 01" src="https://user-images.githubusercontent.com/13383782/184700538-62182ed7-f79a-4e27-b904-9718942ae9b8.png">


TODO:
-> Verify mitigation will work
-> Publish V3 Pricer -> TODO: Add handling of revert case for balancer
-> Test various tokens on live pricerV3
-> Simulation of Integration test
-> Multisig TX to Set it
-> Simulation of after setup test

**Comment by GalloDaSballo** [comment]
## Deployment of PricerV3 + DemoSeller

univ3simulator = 0x45C585F17146e4378a9676349c3d3d8521112598

balancerV2Simulator = 0xfC51b7d4319F1a243aFE29e44CA29F093f9eA7D1

Pricer = 0xd27448046354839A1384D70f30e2f9528E361b03

Demo Seller = 0x75547825A99283379e0E812B7c10F832813326d6


## Test Orders
USDC -> WETH: https://etherscan.io/tx/0xf1f1c32f4fd5fb8dc8a8e8693e598645e6c194ac8395f2983dca2400dd04848c

See all orders: https://explorer.cow.fi/address/0x75547825A99283379e0E812B7c10F832813326d6

**Comment by GalloDaSballo** [comment]
Update:
Re-deploying PricerV3 after Watchpugs Recommendations
https://www.hacknote.co/17c261f7d8fWbdml/doc/182cf5567f8Gdn7B#182cf5567f8Gdn7B

**Comment by GalloDaSballo** [comment]
Deployment of latest V3 Pricer:
https://etherscan.io/address/0x2dc7693444acd1eca1d6de5b3d0d8584f3870c49#code

Libraries are same from pricer above (no changes, see:
https://github.com/GalloDaSballo/fair-selling/pull/35

**Comment by GalloDaSballo** [comment]
Closing as succesful
