### ISSUE TITLE
Create an issue template for strategy reviews

### ISSUE THREAD

**Issue by dapp-whisperer** [Badger-Finance/badger-strategies#6]
The following information should be included
# Strategy Review

### Description
Plaintext logic. Can be a link to README or other doc.

### Code Link 
Commit / Hash / Repo should be known from this.

## Due Diligence Document  (Link, but could also just be a .md file in repo)
This document evaluates the protocols that are interacted with as strategy positions.

## Review By
* Ongoing: 
* Completed:

## Review by Security Board
* Not started / ongoing / completed

## Test Checks (screen shot of all test passing)

**Comment by dapp-whisperer** [comment]
@Tritium-VLK do you know if / how we can create templates like this? This repo is a place to manage strategy reviews inspired by the multisig repo.

**Comment by mitche50** [comment]
Done.  :D
