### ISSUE TITLE
[Safe-Module]: speed module for bribes processing

### ISSUE THREAD

**Issue by petrovska-petro** [Badger-Finance/badger-strategies#63]
# Safe Module Review

### Description

[README](https://github.com/petrovska-petro/bribes_module_speed/blob/main/README.md)

### Code Link 

[Repository](https://github.com/petrovska-petro/bribes_module_speed)

## Due Diligence Document  (Link, but could also just be a .md file in repo)

Will interact thru the safe (in this case techops) with Votium and Cowswap for processing the bribes using the [votium bribes processor](https://github.com/Badger-Finance/badger-multisig/blob/main/helpers/addresses.py#L28)

## Review By
* Ongoing: 
* Completed:

## Review by Security Board
* Not started / ongoing / completed

**Comment by GalloDaSballo** [comment]
@petrovska-petro How would the module be revoked if something goes wrong?

Can you confirm the call will be done via the Safe Address? (No need to change admin in BribesProcessor)

**Comment by petrovska-petro** [comment]
> @petrovska-petro How would the module be revoked if something goes wrong?
> 
> Can you confirm the call will be done via the Safe Address? (No need to change admin in BribesProcessor)

The module can be revoked at any time from the safe. i pushed a test covering this scenario on how the flow would look like.

Confirming that no needs to change admin in the bribes processor. Call will go thru the safe.

**Comment by petrovska-petro** [comment]
> Also can we see a test of an non whitelisted tx failing + removing it from the module?

pushed a test covering the removal of a WL module and trying afterwards to call a tx, which will revert, since it is not WL anymore.

ref to the [tests](https://github.com/petrovska-petro/bribes_module_speed/commit/fa3f80cfaaecd9a2338d730e3f9db41b0fe0f46e). 

locally: `brownie test tests/test_revoke_module.py`

**Comment by GalloDaSballo** [comment]
Closing per the discussion we've had, would rather not give a single signer this type of power
