### ISSUE TITLE
[ETH] byvWBTC GAC and treasury withdrawal fee upgrade

### ISSUE THREAD

**Issue by btcookies** [Badger-Finance/badger-strategies#65]
# Strategy Review

### Description
Upgrading the SimpleWrapperGatedUpgradeable contract for byvWBTC to support GAC pausing and ability to redirect withdrawal fees. To redirect withdrawal fees, new storage variable treasury was created with new setter and event.

Issue described in detail here https://github.com/Badger-Finance/badger-multisig/issues/540. 

### Code Link 
[Commit / Hash / Repo should be known from this.](https://github.com/btcookies/badger-yearn-wbtc)

## Due Diligence Document  (Link, but could also just be a .md file in repo)
This document evaluates the protocols that are interacted with as strategy positions.

## Deployed Contract (If present)
https://etherscan.io/address/0x4b92d19c11435614CD49Af1b589001b7c08cD4D5

## Review By
* Ongoing: 
* Completed:

## Review by Security Board
* Not started / ongoing / completed

## Test Checks (screen shot of all test passing)
<img width="877" alt="Screen Shot 2022-06-22 at 1 44 43 PM" src="https://user-images.githubusercontent.com/31353111/175102752-95f7c07a-af39-4982-9f6d-6b2667625a3b.png">

**Comment by btcookies** [comment]
cc: @sajanrajdev @shuklaayush @GalloDaSballo @axejintao

**Comment by GalloDaSballo** [comment]
@btcookies is there a upgrade test?

**Comment by btcookies** [comment]
@GalloDaSballo I thought I baked it into each of the tests by upgrading, comparing storage vars, testing deposit withdraw etc

**Comment by shuklaayush** [comment]
LGTM
- Adds a `treasury` address storage var that withdrawal fees are transferred to
- Adds GAC pausing and blacklisting to functions

**Comment by GalloDaSballo** [comment]
For some reason `governance` is called `affiliate` beside that LGTM

**Comment by sajanrajdev** [comment]
> For some reason `governance` is called `affiliate` beside that LGTM

This is the name originally introduced by Yearn, the wrapper is based on their [AffiliateToken](https://github.com/yearn/brownie-wrapper-mix/blob/master/contracts/AffiliateToken.sol) contract.

**Comment by sajanrajdev** [comment]
## Review
- Adds a storage variable for the treasury with a setter only callable by Affiliate. The withdrawal function was modified to direct withdrawal fees to this address (And ensures that it is not zero).
- Adds GAC pausability and blacklisting

### Notes
- The `treasury` must be set to Treasury Ops atomically with the upgrade. For as long as the treasury variable is set to `0x0` no withdrawal fees will be charged.

### Testing
Tests are included to confirm a successful upgrade as well of the introduced features and all of the regular operations.
All tests are passing:
![image](https://user-images.githubusercontent.com/25463788/176284485-d8166783-c0b0-473f-a12b-8e783dc864f3.png)

LGTM

**Comment by GalloDaSballo** [comment]
Closing as succesful
