### ISSUE TITLE
[graviAURA upgrade]: Claim bonus AURA from airdrop and LM event non-lockers

### ISSUE THREAD

**Issue by Tritium-VLK** [Badger-Finance/badger-strategies#67]
Note that part of the AURA launch was an airdrop and high emissions on auraBAL for 2 weeks.  Both of these events came with a condition that one must lock the AURA earned or pay a 30% fee.  The 30% is now being distributed to those who lock as per plan.

On my personal wallet `2.3k vlAURA so 62.42/2300  = 0.0271391304 AURA/vlAURA` or about 2.75%.

graviAURA should be upgraded to.
1: Claim this onetime bonus
2: Increase price per share (think just the claim will take care of that)

Here is the TX from me claiming the AURA mentioned above via the UI:
https://etherscan.io/tx/0xd3d6555d84dbba5404a100b22feb8fb95501aa6cf0e6e561cbe86d330d6bffaf

**Timing/urgency:**
Note that this AURA belongs to the current HODLers in the vault.  We will soon ramp up emissions and utility so deposits should start flowing in.  This should be a very simple upgrade, and it would be the fairest to our early staker to upgrade and run this claim as soon as we can.

**Comment by shuklaayush** [comment]
Tx: https://etherscan.io/tx/0xb0d851d60a8a9137454f18788f9a9ddf517b54577cc89bdc590bf10d9c56dc20
