### ISSUE TITLE
Permissionless keepers (we can do it!!!)

### ISSUE THREAD

**Issue by Tritium-VLK** [Badger-Finance/badger-strategies#68]

**Comment by GalloDaSballo** [comment]
Pricer problem -> Must be properly priced (with confidence intervals)
Mev estimator -> Quantify max and min extractable value given the swap size
Statisticlal likelyhood of rekt math -> Given the above, determine if it's acceptable

**Comment by GalloDaSballo** [comment]
"Self" executing Cowswap Orders:

Chainlink Price Request -> Custom Job -> Cowswap API Request -> Returns Order Data -> Validated by Cowswap Seller -> Executed onChain
