### ISSUE TITLE
Launch graviAuraBAL Vault

### ISSUE THREAD

**Issue by Tritium-VLK** [Badger-Finance/badger-strategies#69]
## Launch Checklist
- [x] Strategy development - Strategist
- [x] Strategy fork testing - Strategist/QA Pod
- [x] Strategy review - Solidity Pod/QA pod
- [x] Contracts deployment and initialization - Strategist/QA Pod
- [x] Addition of vault to the Badger Registry - Strategist/QA Pod
- [x] Wire-up of contracts to the UI (On-chain with RegistryV2) - UI/API pod
- [x] Guestlist deployment and setup (If guarded launch) - Strategist/QA Pod
- [x] Test deposit through the UI - Strategist/QA Pod
- [x] Production tests of operational functions (Earn, Harvest, Tend) - Strategist/QA Pod
- [x] Add vault/strategy addresses to the keeper bot - Emissions Pod
- [x] Test a rewards claim (If new reward token is emitted) - Strategist/QA Pod
- [x] APY and balance on UI verification - Strategist/QA Pod
- [x] User Guide and Strategy diagram - Comms pod
- [x] Contract addresses additions to Docs - Comms/QA pod
- [x] Contracts delegation - Strategist/QA Pod
- [x] Contracts' Production parameters and delegation verification - Solidity/QA pod
- [x] Production launch - UI/API Pod
- [x] Announcements - Comms pod

**Comment by sajanrajdev** [comment]
To add more details:
The vault will use the following pool as want: 
![image](https://user-images.githubusercontent.com/25463788/177870012-c6ec6804-3c61-4f04-8359-d60907c5172b.png)

LP token: [33auraBAL-33graviAURA-33WETH](https://etherscan.io/token/0x0578292cb20a443ba1cde459c985ce14ca2bdee5)
PID: 16

![image](https://user-images.githubusercontent.com/25463788/177870401-97c39eb3-39f3-4440-85e6-9a1a4deb3835.png)

**Comment by shuklaayush** [comment]
### Deployment
Vault: [0xf8f5677B6bCecdb9be94AE8f6770a05a6C53C378](https://etherscan.io/address/0xf8f5677B6bCecdb9be94AE8f6770a05a6C53C378)
Strategy: [0xA773b13A64D213291a063a1910b96C117b2438Df](https://etherscan.io/address/0xA773b13A64D213291a063a1910b96C117b2438Df)

**Comment by sajanrajdev** [comment]
## Deployment Review

### Vault
**Parameters**
- Governance is yet to be delegated, all other actors LGTM
- Guestlist is properly set
- Token is correct
- Strategy is correct
- Fees: 0.1% wd, 10% perf - agrees with what stablished on the following [conversation](https://github.com/Badger-Finance/badger-strategies/issues/66#issuecomment-1175361734). Non helper staking optimizer have a 0.1% wd fee and 10% performance -  LGTM

### Strategy
**Parameters**
- PID and want are correct
- Vault is correct
- Slippage protection is 5% - LG

### Guestlist
**Parameters**
- Wrapper points to vault - LG
- Guestroot is 0x0 - LG
- User cap is max uint256 - LG
- Total cap: 30k (pricing based on Balancer ui, LGTM)

### Proxy Admins
All proxy admins point to the Timelock proxyAdmin - LGTM
![image](https://user-images.githubusercontent.com/25463788/178341830-90a470d5-06ff-42f3-a8c8-bb2cbe85016f.png)

### Overall
LGTM

**Comment by sajanrajdev** [comment]
## Launch Checklist
- [ ] Strategy development - Strategist
- [ ] Strategy fork testing - Strategist/QA Pod
- [ ] Strategy review - Solidity Pod/QA pod
- [ ] Contracts deployment and initialization - Strategist/QA Pod
- [ ] Addition of vault to the Badger Registry - Strategist/QA Pod
- [ ] Wire-up of contracts to the UI (On-chain with RegistryV2) - UI/API pod
- [ ] Guestlist deployment and setup (If guarded launch) - Strategist/QA Pod
- [ ] Test deposit through the UI - Strategist/QA Pod
- [ ] Production tests of operational functions (Earn, Harvest, Tend) - Strategist/QA Pod
- [ ] Add vault/strategy addresses to the keeper bot - Emissions Pod
- [ ] Test a rewards claim (If new reward token is emitted) - Strategist/QA Pod
- [ ] APY and balance on UI verification - Strategist/QA Pod
- [ ] User Guide and Strategy diagram - Comms pod
- [ ] Contract addresses additions to Docs - Comms/QA pod
- [ ] Contracts delegation - Strategist/QA Pod
- [ ] Contracts' Production parameters and delegation verification - Solidity/QA pod
- [ ] Production launch - UI/API Pod
- [ ] Announcements - Comms pod

**Comment by dapp-whisperer** [comment]
thanks for checklist Saj, moving to first comment for easy visibility

**Comment by GalloDaSballo** [comment]
Closing as succesful
