### ISSUE TITLE
BalancerStakingOptimizer (WBTC/DIGG/graviAURA)

### ISSUE THREAD

**Issue by Tritium-VLK** [Badger-Finance/badger-strategies#71]
# Strategy Review

### Description
Point the Bal staking optimizer at the DIGG/WBTC/BADGER pool: https://app.balancer.fi/#/pool/0x8eb6c82c3081bbbd45dcac5afa631aac53478b7c000100000000000000000270 and launch a vault.

This vault will participate in boost.  Therefore, it should charge a 20% perf fee and a 0.1% withdraw fee.

Ticket for boost participation: https://github.com/Badger-Finance/badger-rewards/issues/923

### Code Link 
Commit / Hash / Repo should be known from this.

## Due Diligence Document  (Link, but could also just be a .md file in repo)
This document evaluates the protocols that are interacted with as strategy positions.

## Review By
* Ongoing: 
* Completed:

## Review by Security Board
* Not started / ongoing / completed

## Launch Checklist
- [x] Strategy development - Strategist
- [x] Strategy fork testing - Strategist/QA Pod
- [x] Strategy review - Solidity Pod/QA pod [Dapp: cloned strategy - confirming if no extra internal audit needed]
- [x] Contracts deployment and initialization - Strategist/QA Pod
- [x] Addition of vault to the Badger Registry - Strategist/QA Pod
- [x] Wire-up of contracts to the UI (On-chain with RegistryV2) - UI/API pod
- [x] Guestlist deployment and setup (If guarded launch) - Strategist/QA Pod
- [x] Test deposit through the UI - Strategist/QA Pod
- [x] Production tests of operational functions (Earn, Harvest, Tend) - Strategist/QA Pod
- [x] Add vault/strategy addresses to the keeper bot - Emissions Pod
- [x] Test a rewards claim (If new reward token is emitted) - Strategist/QA Pod
- [x] APY and balance on UI verification - Strategist/QA Pod
- [x] User Guide and Strategy diagram - Comms pod
- [x] Contract addresses additions to Docs - Comms/QA pod
- [x] Contracts delegation - Strategist/QA Pod
- [x] Contracts' Production parameters and delegation verification - Solidity/QA pod
- [x] Production launch - UI/API Pod
- [x] Announcements - Comms pod

**Comment by Tritium-VLK** [comment]
Guarded launch of 300k USD or so, treasury also has big bags to deposit to test and/or for a sizeable guarded if desired.

**Comment by hasherror** [comment]
Chad is waiting...tik tock tik tok

**Comment by shuklaayush** [comment]
### Deployment
Vault: [0x371B7C451858bd88eAf392B383Df8bd7B8955d5a](https://etherscan.io/address/0x371B7C451858bd88eAf392B383Df8bd7B8955d5a)

Strategy: [0xD87F2cdE238D0122b3865164359CFF6b2431d927](https://etherscan.io/address/0xD87F2cdE238D0122b3865164359CFF6b2431d927)

Guestlist: [0x807aD276E6D8A06D0021539a73c7172A1eFAfe7E](https://etherscan.io/address/0x807aD276E6D8A06D0021539a73c7172A1eFAfe7E)

**Comment by Tritium-VLK** [comment]
Any chance we can get this loaded into beta but not prod this week?  @sajanrajdev you the person to ping/coordinate that?  Seems like an onchain wire up jobby?

**Comment by sajanrajdev** [comment]
@Tritium-VLK Sounds doable to me, unless @shuklaayush has a concern. Contract LG and we shoud be able to move forward with UI wire-up.

**Comment by sajanrajdev** [comment]
Rewards were not being distributed, simulating on fork showed that it was due to a missing call of `booster.earMarkRewards(18)`. Called manually: https://etherscan.io/tx/0x3fe67857ba989bbdec69bfc78c16979e5e9fa38043842bdc8246ac315265a88f

**Comment by sajanrajdev** [comment]
Test Ops functions:
- Earn: https://etherscan.io/tx/0xcb4b4d7fbd38da260cc8b9a411dadbd5612b0d6e900d8bd29acb72f5330c10ee
- Harvest 1: https://etherscan.io/tx/0x339b55e502c344a4f97d7e0e8abc68345db6134541927b9f43d976fc1e4084cf

**Comment by shuklaayush** [comment]
Governance delegation
https://etherscan.io/tx/0xa3d771b3dbc24305c6d5750e3f554b31c6d1d42fc62666851553f6ecfe57c0a5

**Comment by GalloDaSballo** [comment]
Closing as succesful
