### ISSUE TITLE
graviAURA upgrade: Brib Recycling

### ISSUE THREAD

**Issue by Tritium-VLK** [Badger-Finance/badger-strategies#72]
#  Change request

### Description
**Justification**
- We want to enable any DAO to use frax-style brib recycling on graviAURA pairs.
- Bribs earned by graviAURA and sent to HODLers is misallocated, as the bribes were earned by graviAURA in pools.
- We need more revenue streams

**How it works**

- All bribs earned by graviAURA should be used to rebrib for the same pool instead of being sent to the BribsProcessoooor to pay out HODLers.`
- A fee of x% should be taken for this service, and sent to the treasury-ops multisig or wherever @gosuto-inzasheru wants

**Note on fees**
Hidden hands currently charges a 4% fee.  We shouldn't take less then them. So then we would charge 4%.  This does not make brib recycling very useful/attractive for most DAOs.  I will be making a proposal to redacted governance to charge our strategy a reduced fee.   I will provide more details as they become available but the fee should be defined as one of 2 things.

- A absolute percentage value ranging from 0.5%-10%
- A multiple of the Hidden Hands fee ranging from 1x-3x

Please get in touch with Tritium with questions.

### Code Link 
Not sure where graviAURA codebase is.

## Due Diligence Document  (Link, but could also just be a .md file in repo)
Not sure where Aura DD documentation is.

## Review By
* Ongoing: 
* Completed:

## Review by Security Board
* Not started / ongoing / completed

## Launch Checklist
-- Need upgrade checklist ---

**Comment by GalloDaSballo** [comment]
@Tritium-VLK 
How do you:
- Collect a Bribe from Pool X?
- Rebribe?

**Comment by Tritium-VLK** [comment]
- This is a good question
- Rebribe should easy if you know what pool it came from

Not urgent, but I think it can make some good money and will become more wanted over the quarter.

**Comment by Tritium-VLK** [comment]
Will close this ticket for now as there is not a clear spec, and the original ask seems not easy to do onchain.
