### ISSUE TITLE
[AURA]: rETH/ETH Staking Optimizer

### ISSUE THREAD

**Issue by sajanrajdev** [Badger-Finance/badger-strategies#74]
# Strategy Review

### Description
Strategy Aura Staking Optimizer vaults for the following Balancer Pool:
rETH/ETH https://app.balancer.fi/#/pool/0x1e19cf2d73a72ef1332c882f20534b6519be0276000200000000000000000112
Want: 0x1E19CF2D73a72Ef1332C882F20534B6519Be0276
PID: 21

Performance Fee: 10%
Withdrawl fee: 0.1%

Feature Request: https://github.com/Badger-Finance/Badger-Project-Planning/issues/100

### Code Link 
Vault logic: https://etherscan.io/address/0x55918a84eb7fd1d930e098a8e86d0206549fa8c3#code (with fee events)
Strategy logic: https://etherscan.io/address/0x83897f8892244b406346cc3811712275e2005694#code

## Due Diligence Document  (Link, but could also just be a .md file in repo)
NA

## Review By
* Ongoing: 
* Completed:

## Review by Security Board
* Not started / ongoing / completed

## Test Checks (screen shot of all test passing)
![image](https://user-images.githubusercontent.com/25463788/189965206-f139241d-2977-4cbc-aee7-00d55373afab.png)

## Launch Checklist
- [x] Strategy development - Strategist
- [x] Strategy fork testing - Strategist/QA Pod
- [x] Strategy review - Solidity Pod/QA pod
- [x] Contracts deployment and initialization - Strategist/QA Pod
- [x] Addition of vault to the Badger Registry - Strategist/QA Pod
- [x] Wire-up of contracts to the UI (On-chain with RegistryV2) - UI/API pod
- [x] Guestlist deployment and setup (If guarded launch) - Strategist/QA Pod
- [x] Test deposit through the UI - Strategist/QA Pod
- [x] Production tests of operational functions (Earn, Harvest, Tend) - Strategist/QA Pod
- [x] Add vault/strategy addresses to the keeper bot - Emissions Pod
- [x] Test a rewards claim (If new reward token is emitted) - Strategist/QA Pod
- [x] APY and balance on UI verification - Strategist/QA Pod
- [x] User Guide and Strategy diagram - Comms pod
- [x] Contract addresses additions to Docs - Comms/QA pod
- [x] Contracts delegation - Strategist/QA Pod
- [x] Contracts' Production parameters and delegation verification - Solidity/QA pod
- [x] Production launch - UI/API Pod
- [x] Announcements - Comms pod

**Comment by sajanrajdev** [comment]
## Deployed Contracts
Vault: 0xA484427CF91bbd945c39eF87dF0A02Bb8625dC97
Want: 0x1E19CF2D73a72Ef1332C882F20534B6519Be0276
Strategy: 0xE6153AdD9913c7D25a6d475acFfACc5Eb570D8bE

**Comment by sajanrajdev** [comment]
Setup transactions:
- Initialize vault: https://etherscan.io/tx/0xdc4f65ebefb8df7d401097139e880ad8fcbff05e5b3db4142c01b7636c3d89fe
- Initialize strat: https://etherscan.io/tx/0x94b548c1fe1c76f593f70f5925e2e7d441414bf38a0c42c1abc5d55568488dd4
- setStrategy: https://etherscan.io/tx/0x57a286318aaa8a30f4df69d3c54b3433a20722c8f9ee6e91d4d82b2735ea44eb

**Comment by sajanrajdev** [comment]
Added to registry through RegistryACL: https://etherscan.io/tx/0x79a3b5bb4bfc6fabd1c6c7be2d063ba087d6fac35164ea0604a5ae759ac6bcac
![image](https://user-images.githubusercontent.com/25463788/189989082-077766ea-bb5d-4d9a-b21a-0adf9460e7bc.png)

**Comment by sajanrajdev** [comment]
Guestlist: 0xBD79595f391E9bb3124212244caA5e7C83552fB3
- Init: https://etherscan.io/tx/0xfa5e18ab580de6e206850a3b03ac246ab172a2ef7c6d95f9ec98b381f89b8024
- User cap: https://etherscan.io/tx/0xdb6fa3dd6b7b3dd39775cbd54d4edcda5f48bae91594c3ace3263e477ae5f014
- Total cap: https://etherscan.io/tx/0x4b83d9d2afa4d9c69165f705afba27da2b6ce618f55cbcf98859704acbd40294
- setGuestlist: https://etherscan.io/tx/0x9bbcbd95305282dd69b7c05fc736c88f38ead65099856793cf1c6bb7e42b45f2

$Cap = \frac{cap USD * TotalSuppy}{TVLUSD} = \frac{1,000,000*10169.058778774688368637}{16,446,123} = 618.325594352826399792644138682411 BPT$

**Comment by sajanrajdev** [comment]
On-Chain testing:
- earn: https://etherscan.io/tx/0xe6d0c2bc4e958bd2f07893d78ed1abbb0a9456126f87582c8e4790c1b941492f
- 1 harvest: https://etherscan.io/tx/0x7871f566ba04c044376818d97120292d1229805f9ff0d845ef7a032e9e19e95c
- 2 harvst: https://etherscan.io/tx/0xaaca88d5087a681b2c0c8854f8efb18c12aacc3fcfa447762392b8b5989b5d2b

**Comment by shuklaayush** [comment]
Governance on vault and guestlist yet to be delegated. All other params LGTM

**Comment by sajanrajdev** [comment]
Promoted vault to experimental (same status but indexed by governance): https://etherscan.io/tx/0x8b787661dc1d80b12f8fc1af10f1c28aa54b18621822e9eeb499b5a82c24bfc1

**Comment by GalloDaSballo** [comment]
<img width="842" alt="Screenshot 2022-09-22 at 17 37 45" src="https://user-images.githubusercontent.com/13383782/191790995-452b3eca-d519-4f34-a4a9-7dc1d3511f2e.png">

**Comment by GalloDaSballo** [comment]
All settings LGTM

Logic is same as prev strats

Let's gooooo

**Comment by sajanrajdev** [comment]
Vault launched in guarded
