### ISSUE TITLE
[AURA]: wstETH/ETH Staking Optimizer

### ISSUE THREAD

**Issue by sajanrajdev** [Badger-Finance/badger-strategies#75]
# Strategy Review

### Description
Strategy Aura Staking Optimizer vaults for the following Balancer Pool:
wstETH/ETH: https://app.balancer.fi/#/pool/0x32296969ef14eb0c6d29669c550d4a0449130230000200000000000000000080
Want: 0x32296969Ef14EB0c6d29669C550D4a0449130230
PID: 3

Performance Fee: 10%
Withdrawl fee: 0.1%

Feature Request: https://github.com/Badger-Finance/Badger-Project-Planning/issues/100

### Code Link 
Vault logic: https://etherscan.io/address/0x55918a84eb7fd1d930e098a8e86d0206549fa8c3#code (with fee events)
Strategy logic: https://etherscan.io/address/0x83897f8892244b406346cc3811712275e2005694#code

## Due Diligence Document  (Link, but could also just be a .md file in repo)
NA

## Review By
* Ongoing: 
* Completed:

## Review by Security Board
* Not started / ongoing / completed

## Test Checks (screen shot of all test passing)
![image](https://user-images.githubusercontent.com/25463788/189965206-f139241d-2977-4cbc-aee7-00d55373afab.png)

## Launch Checklist
- [x] Strategy development - Strategist
- [x] Strategy fork testing - Strategist/QA Pod
- [x] Strategy review - Solidity Pod/QA pod
- [x] Contracts deployment and initialization - Strategist/QA Pod
- [x] Addition of vault to the Badger Registry - Strategist/QA Pod
- [x] Wire-up of contracts to the UI (On-chain with RegistryV2) - UI/API pod
- [x] Guestlist deployment and setup (If guarded launch) - Strategist/QA Pod
- [x] Test deposit through the UI - Strategist/QA Pod
- [x] Production tests of operational functions (Earn, Harvest, Tend) - Strategist/QA Pod
- [x] Add vault/strategy addresses to the keeper bot - Emissions Pod
- [x] Test a rewards claim (If new reward token is emitted) - Strategist/QA Pod
- [x] APY and balance on UI verification - Strategist/QA Pod
- [x] User Guide and Strategy diagram - Comms pod
- [x] Contract addresses additions to Docs - Comms/QA pod
- [x] Contracts delegation - Strategist/QA Pod
- [x] Contracts' Production parameters and delegation verification - Solidity/QA pod
- [x] Production launch - UI/API Pod
- [x] Announcements - Comms pod

**Comment by sajanrajdev** [comment]
## Deployed Contracts
Vault: 0x41466b8ec544e3192Aa1aA30f65fC60FAb4D52Bf
Want: 0x32296969Ef14EB0c6d29669C550D4a0449130230
Strategy: 0x1cC3731d8f30341EF4527E7da1B6a4DA88ef71DF

**Comment by sajanrajdev** [comment]
Setup transactions:
- Initialize vault: https://etherscan.io/tx/0x558a02968391f709e6b0128ebd2ba8a27a23f4660f233ad6691cb59184e26b6f
- Initialize strat: https://etherscan.io/tx/0xff728f4a8f7ee28da3e297102680034ab46d3ea5ae934eda5ca127839f784596
- setStrategy: https://etherscan.io/tx/0xe9e676c69958a0885aea4e2e87c590822ab88f10c75b2da3ead2fd9338431b25

**Comment by sajanrajdev** [comment]
Added to registry through RegistryACL: https://etherscan.io/tx/0x0613696493a0f7f30d926713ab256e854fc2428a64989d8b34dc663fbca2a7eb
![image](https://user-images.githubusercontent.com/25463788/189989082-077766ea-bb5d-4d9a-b21a-0adf9460e7bc.png)

**Comment by sajanrajdev** [comment]
Guestlist: 0x348fc07475b5e55CC0B8F51cC004792d8A775B09
- Init: https://etherscan.io/tx/0xc11c71ed30ec0e202168a47e3cc4958aa9d74e5eabdc82979a5f7a1b440f016c
- User cap: https://etherscan.io/tx/0x61ff755233eb314775f5ccf314fe1e32caed7cc8757301827090aa1352c95d2b
- Total cap: https://etherscan.io/tx/0x9e9c2ced3caf743d1fe6485db142141f338498ff91ea3a928fa20ebae7edf70e

$Cap = \frac{cap USD * TotalSuppy}{TVLUSD} = \frac{1,000,000*85569.04342550608897611}{137,372,499} = 622.8979166019691392 BPT$

**Comment by sajanrajdev** [comment]
On-Chain testing:
- earn: https://etherscan.io/tx/0x17c2e3cac14d45fca4da83a21717a1cfcb30710c0dc0dc8df1358412056c5969
- 1 harvest: https://etherscan.io/tx/0x337f1b8203f1b8fb6aacb74e53afbd858efb8e1c559478064294f6b0283c2a2b
- 2 harvst: https://etherscan.io/tx/0xae7c2812beb606c31ee0813d1a111e330baed8cf005dd6fb1b248f8f5028c72a

**Comment by shuklaayush** [comment]
Governance on vault and guestlist yet to be delegated. All other params LGTM

**Comment by sajanrajdev** [comment]
Promoted vault to experimental (same status but indexed by governance): https://etherscan.io/tx/0x9c6eb251700d7d11002dea8182ca546fdc510d477d188d63f2e3c8a88978b522

**Comment by sajanrajdev** [comment]
- Governance delegation: https://etherscan.io/tx/0x50ebb89704602224fbd72afda1f9f45cc79db9897b1d736a1874eced9e75af85
- Guestlist owner delegation: https://etherscan.io/tx/0xf7f0105ea7a699503ae140132938bfd7592d3553abe6aa57365eda86b6a5247a

**Comment by GalloDaSballo** [comment]
<img width="844" alt="Screenshot 2022-09-22 at 17 38 45" src="https://user-images.githubusercontent.com/13383782/191791200-8734c009-53f4-4888-ab93-1a186856a99f.png">

**Comment by GalloDaSballo** [comment]
All settings LGTM

Logic is same as prev strats

Let's gooooo

**Comment by sajanrajdev** [comment]
Vault launched in guarded
