### ISSUE TITLE
Review: ARBITRUM WBTC-WETH-SLP-Arbitrum-Strategy

### ISSUE THREAD

**Issue by shuklaayush** [Badger-Finance/badger-strategies#8]
# Strategy Review

- [Spec](https://github.com/shuklaayush/WBTC-WETH-SLP-Arbitrum-Strategy#readme)
- [Code](https://github.com/shuklaayush/WBTC-WETH-SLP-Arbitrum-Strategy/blob/v0.5/contracts/MyStrategy.sol)
- [Release](https://github.com/shuklaayush/WBTC-WETH-SLP-Arbitrum-Strategy/releases/tag/v0.5)

**Comment by shuklaayush** [comment]
Tests passing:
![image](https://user-images.githubusercontent.com/27727946/132064031-cd30dd83-4708-45df-afbc-b9683863cc98.png)

**Comment by shuklaayush** [comment]
Modified strategy to deposit 50% Sushi rewards to Badger's Weth-Sushi SLP vault on behalf of the Badger Tree (instead of transferring rewards directly to Badger Tree). See [v0.4 release](https://github.com/shuklaayush/WBTC-WETH-SLP-Arbitrum-Strategy/releases/tag/v0.4)

**Comment by sajanrajdev** [comment]
Contracts deployed at:
```Vault: 0xFc13209cAfE8fb3bb5fbD929eC9F11a39e8Ac041
Strategy: 0xA6827f0f14D0B83dB925B616d820434697328c22```

Test tokens were deposited, vault was unpaused and contracts wired up.

Vault added to registry under:  `0xeE8b29AA52dD5fF2559da2C50b1887ADee257556`

Operational Test Txs:
- Strategy approved for interaction on WETH/SUSHI SLP helper vault: https://arbiscan.io/tx/0xc4627d74f8d5f78ac223a764c1d599d70f8c2f1846664bed21e5566de5ec3d91
- Earn: https://arbiscan.io/tx/0x150f861495fc1b3a622bf42ecb70e6d32a80d99d44da109898760414278d6600
- Harvest: https://arbiscan.io/tx/0xca73bd165378a1f1d70e85145b7f353cc208f96a6f2ed803708699b2b446bdb8
- Tend: https://arbiscan.io/tx/0x0f0ee64cb187e172ab04417140aa1891567544614154483e6db158f3c0f24ee5

**Comment by GalloDaSballo** [comment]
Strategy code LGTM

Strat will deposit `want` into miniChef

On harvest it will swap 50% of SUSHI to WETH
It will then provide liquidity to SUSHI / WETH and depositFor to tree
Lastly ill will swap 25% of Sushi to wBTC

It will then LP wBTC / WETH to auto-compound

I would have done all the swaps at the top and the LP at the end
But fundamentally it's the same thing

Also, we could have processedFees in shares of the helper vault so that we are autocompounding those rewards for treasury

All in all it's fine

**Comment by GalloDaSballo** [comment]
NOTE: WAS NOT ABLE TO RUN TESTS

**Comment by GalloDaSballo** [comment]
Tests are passing
<img width="1226" alt="Screenshot 2021-09-10 at 16 19 03" src="https://user-images.githubusercontent.com/13383782/132868105-2b9346c5-9b9a-42d0-8853-5db750fa19ab.png">

LGTM could have added a custom test to verify on `earn` that balance in miniChef increases

**Comment by GalloDaSballo** [comment]
Pls proceed with prod wire up with MULTISIG

**Comment by sajanrajdev** [comment]
Strategy review:
**Tend:** Deposits want (if any) into Sushi's MiniChef
**Harvest:** 
* Harvests SUSHI rewards from MiniChef
* Swaps 50% for WETH
* Provides liquidity to the WETH/SUSHI pool using half of the WETH acquired and 25% of the total SUSHI
* Process fees on Sushi/WETH SLP and depositFor the rest for the Badger Tree
* Swaps remaining SUSHI for wBTC using the WETH path (There is plenty of liquidity on both pairs)
* Adds liquidity to wBTC/WETH pool to get more want
* Process performance fees on generated want

Current liquidity in pairs:
![image](https://user-images.githubusercontent.com/25463788/132901217-d6ed42f0-bbe5-4da5-a0f3-3f42071190ef.png)


Notes:
- Withdraw function will take any want sitting on the strategy before fetching from the MiniChef position. 
- Liquidity provision uses `sl` for slippage check. This variable can be adjusted if required based on market conditions. One thing to note is that the same variable is used when providing liquidity to the two different pools; it would be safer to be able to set the slippage tolerance differently for each one of the two pools independently. For now, if the right value is used, it should work as it is for both pools.

Tests reveiw: 
Other than Alex's suggestion above, tests and resolver checks LGTM. 

NOTE: Haven't been able to run the tests but based on the [outputs on CI](https://github.com/shuklaayush/WBTC-WETH-SLP-Arbitrum-Strategy/runs/3548586096?check_suite_focus=true) it LGTM. Will keep trying to get them to run.
