### ISSUE TITLE
[Change Request] Balancer 2% gauge migration plan

### ISSUE THREAD

**Issue by dapp-whisperer** [Badger-Finance/badger-strategies#80]
## Migration Script
* Badger-Finance/badger-multisig#823 
* have migration script reviewed
* pre-load onto dev multisig for fast exec

# Order of operations
* gauges kiled (how will we know this has happened? @Tritium-VLK @GalloDaSballo )
* ensure new gauges have capital in them, before migrating strategies
  * if no one has deposited, we should from treasury or individual. if no one deposits before us, our rewards might be stolen
* Decide when to migrate based on rewards rate
  * existing gauge will have rewards for 0-7 days after the switchover, based on periodEnd
  * compare old emissionRate vs EV of new gauge and rewards pool to decide when to switch
  * math should be evaluated for this change

**Comment by Tritium-VLK** [comment]
Gauge will not receive votes anymore, so basically at 00:00 GMT on wednesday-thursday the balancer gauge should stop emitting veBAL.  As I understand it, the AURA gauge will continue to emit buffered tokens for a week.

At the same time rewards will start flowing to the new  capped gauge, which should have a new AURA gauge contract.

**Comment by sajanrajdev** [comment]
The new gauges for the capped pools were added to the AURA booster:
- BADGER/wBTC: https://etherscan.io/tx/0xbc83fd69f1b4772759739afd4b062012aadd656434e1d1ee3bf53895d6c65fca
- WBTC/DIGG/graviaURA: https://etherscan.io/tx/0x568c2fcf4da88cda0b66982936199de089375756c15cbc759d17bf1da95736b5

This created new pools for the gauges on Aura ecosystem (PIDS: 33 and 34 respectively):
![image](https://user-images.githubusercontent.com/25463788/191521639-296cbec4-cbdf-404d-98a7-5eb229b6e3e3.png)
![image](https://user-images.githubusercontent.com/25463788/191521659-6b9c7cc3-83d1-488a-b9ac-d224426fc182.png)

**Comment by GalloDaSballo** [comment]
Closing as succesful
