### ISSUE TITLE
Prepare Badger/FRAXBP Gauge Tasks

### ISSUE THREAD

**Issue by dapp-whisperer** [Badger-Finance/badger-strategies#81]
See https://github.com/Badger-Finance/badger-strategies/issues/78 for context

From Freddy:
two more actions are required:
* Please "Enact" the gauge on Curve: https://dao.curve.fi/vote/ownership/215
* Call addPool(guage address) on the Convex pool manager: https://discord.com/channels/820795644494610432/820795644494610435/1025408870098669648

**Comment by dapp-whisperer** [comment]
Enact has been confirmed and called, addPool() requires that the pool have weight

**Comment by sajanrajdev** [comment]
@dapp-whisperer 
BADGER/fraxbp LP has been added to the Convex Booster: 
https://etherscan.io/address/0xF403C135812408BFbE8713b5A23a04b3D48AAE31#readContract

PID: 123
![image](https://user-images.githubusercontent.com/25463788/194349313-70825928-c93f-4c28-9902-76ea679430f0.png)
