### ISSUE TITLE
Launch, fund, validate Badger/rETH pool

### ISSUE THREAD

**Issue by dapp-whisperer** [Badger-Finance/badger-strategies#82]
context https://github.com/Badger-Finance/Badger-Project-Planning/issues/102

Freddy: Can you take the ball on getting the factory pool created (BADGER/rETH 50/50)? Links below are for reference, they're all in original ticket:

New Balancer Factory Link: https://github.com/balancer-labs/balancer-v2-monorepo/tree/master/pkg/deployments/tasks/20220908-weighted-pool-v2
Factory on Etherscan: https://etherscan.io/address/0xcC508a455F5b0073973107Db6a878DdBDab957bC#writeContract
rETH/RPL Pool Sponsored by Solar: https://etherscan.io/address/0x0fd5663d4893ae0d579d580584806aadd2dd0b8b#code
rETH Rate Provider: https://etherscan.io/address/0x1a8f81c256aee9c640e14bb0453ce247ea0dfe6f
I'm working on the gauge proposal for the Balancer forum and will have that ready to go as soon as the pool is created.

1. Review factory and existing rETH pool
2. Test, launch, funding and swapping in fork
3. Launch pool
4. Fund

**Comment by dapp-whisperer** [comment]
Currently entering an external review for DD

**Comment by petrovska-petro** [comment]
deployment [tx](https://etherscan.io/tx/0x9a949a52e4179d0c57dcffd6884d5787febfb92f8f4b7e114ef8cfbda0292a79)

pool [address](https://etherscan.io/address/0xe340EBfcAA544da8bB1Ee9005F1a346D50Ec422e)

balancer ui given the pool id of *0xe340ebfcaa544da8bb1ee9005f1a346d50ec422e000200000000000000000396*: [link](https://app.balancer.fi/#/pool/0xe340ebfcaa544da8bb1ee9005f1a346d50ec422e000200000000000000000396)

![Screenshot 2022-10-12 at 17 35 18](https://user-images.githubusercontent.com/84875062/195386443-fe4e2604-c985-4dac-b3b8-ad9c38d0742a.png)

**Comment by petrovska-petro** [comment]
init join [tx](https://etherscan.io/tx/0x1aa2382435947e8d6f736e2496cfae69352e2adbfeb290d72e83ffdafe7fc305)

for those which may require to do the same interaction the steps i followed from cli are the following:

```
badger.approve(vault.address, badger.balanceOf(dev), {"from": dev})

reth.approve(vault, reth.balanceOf(dev), {"from": dev})

underlyings = [badger, reth]
mantissas = [badger.balanceOf(dev), reth.balanceOf(dev)]
data_encoded = eth_abi.encode_abi(["uint256", "uint256[]"], [0, mantissas])

vault.joinPool(0xe340ebfcaa544da8bb1ee9005f1a346d50ec422e000200000000000000000396, dev, dev, (underlyings, mantissas, data_enco
ded, False), {"from": dev})
```

Docs ref for type of joins. [link](https://dev.balancer.fi/resources/joins-and-exits/pool-joins#stablepool-joinkinds)

**Comment by GalloDaSballo** [comment]
https://etherscan.io/tx/0xc1eefb8479f131227240945cc87e852eee75cbc4aec2d869e6d858e730e92e90
