### ISSUE TITLE
[Aura]: Aura Booster and Rewards Contracts migrations

### ISSUE THREAD

**Issue by sajanrajdev** [Badger-Finance/badger-strategies#85]
# Strategy Review

## Description
Aura Finance will conduct a migration of their Booster and, therefore, all of their reward pool contracts. This means that all BPT tokens staked within Aura will cease to receive rewards after this. According to their [announcement](https://discord.com/channels/952228254910136330/971913083326967808/1050622931958501376), the migration will take place on December 13th but rewards will continue to be distributed to the old contracts for ~7days. Anybody that stakes and claims rewards during the 7 days after migration, will be airdropped AURA in proportion to their staked amount. On December 20th, once the old contracts dry up, our strategies should be pointing to the new contracts to continue accruing rewards.

### Live strategies affected
- 80BADGER20wBTC
- graviAURA/DIGG/wBTC
- bauraBAL

### Code Link 
Commit / Hash / Repo should be known from this.

## Due Diligence Document  (Link, but could also just be a .md file in repo)
This document evaluates the protocols that are interacted with as strategy positions.

## Review By
* Ongoing: 
* Completed:

## Review by Security Board
* Not started / ongoing / completed

## Check Contract Delegation Tool (Only after wireup, before Beta)
https://github.com/Badger-Finance/badger-vaults-mix-v1.5/blob/main/scripts/7_single_vault_proxy_check.py

## Launch Checklist
- [x] Strategy development - Strategist
- [x] Strategy fork testing - Strategist/QA Pod
- [x] Strategy review - Solidity Pod/QA pod
- [x] Contracts deployment and initialization - Strategist/QA Pod
- [x] Contract addresses additions to Docs - Comms/QA pod
- [x] Contracts delegation - Strategist/QA Pod
- [x] Contracts' Production parameters and delegation verification - Solidity/QA pod
- [x] Execute migration/upgrade from the devMultisig/timelock
- [x] Production launch - UI/API Pod
- [x] Announcements - Comms pod

**Comment by sajanrajdev** [comment]
Migration summary (addresses): https://whimsical-snowman-458.notion.site/LP-Migration-Summary-c024ece456df4940bb3ac8162c70f9dc

**Comment by sajanrajdev** [comment]
Logic deployments:
- StrategyAuraStaking ([diff](https://www.diffchecker.com/f6UuSuhj)): https://etherscan.io/address/0xe9c74a2bf2c7586885188087b7df51c86d0191f1#readContract
- AuraBalStakerStrategy ([diff](https://www.diffchecker.com/eDoucwUO)): https://etherscan.io/address/0xb16c5b8bbba2de6a7ee77820ca5bef50425ab93b#code

**Comment by sajanrajdev** [comment]
Proxies deployments and init:

- b80BADGER_20WBTC strat: https://etherscan.io/address/0xdf30a25b5dbcb8e19d05973661a729a07c1c65bf#readProxyContract
- b40WBTC_40DIGG_20graviAURA strat: https://etherscan.io/address/0xc10bf5ec2e0d2a1a91e184ffef228334b0c06023#code
- bauraBAL strat: https://etherscan.io/address/0xfecb580dd17b54537b3965010335343fb6d8f894

Initializations:
- https://etherscan.io/tx/0xf54721a6213ae6b45121b192fc036fd7074a47f929d702f51215075c85470f02
- https://etherscan.io/tx/0xe4806a4b4cec732f3d8ce339ae5c285a79f440b596e4116b3bdc6af3b4d74231
- https://etherscan.io/tx/0x1c670932c8b7ecde2208a5d9182b30246547bb7151d0c8d40f1e975ca977a22f

**Comment by shuklaayush** [comment]
Verified addresses and parameters. LGTM

**Comment by sajanrajdev** [comment]
Executed:

DIGG/wBTC/gravi: https://etherscan.io/tx/0x9ea99b3aa7fec31ae1c47c45520616e024e75867cb586a470b1406ffd9f8cf11
WBTC/BADGER: https://etherscan.io/tx/0xdfbe641a569020faf06e2dc3d4437cf56edbe926aa7136d401d8d01e6737c329
auraBAL: https://etherscan.io/tx/0x71086b8282fc3a73ae0b017a1d0f42dcb7a7e3772433256f0fc538fbaaeb347d
